### ISSUE TITLE
HediffDef-HediffGiverSetDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#101]
Проверить все изменения текста:
HediffDef
HediffGiverSetDef

Обновить:
HediffDef\Hediffs_Global_Drugs.xml
HediffDef\Hediffs_Global_Misc.xml

**Comment by Dimonasdf** [comment]
https://github.com/Ludeon/RimWorld-ru/tree/branch-4

**Comment by Elevator89** [comment]
```
Looking for missing files... 
1 files only in ../RimWorld-de/DefInjected/HediffDef: 
	/Hediffs_Global_Temperatures.xml
1 files only in ../RimWorld-ru/DefInjected/HediffDef: 
	/Hediffs_Global_Temperature.xml

Looking for missing xml tags...
File: /Hediffs_Global_Drugs.xml:
	16 tags only in ../RimWorld-de/DefInjected/HediffDef: 
		AlcoholHigh.stages.2.label
		AlcoholAddiction.label
		AlcoholHigh.stages.4.label
		AlcoholHigh.stages.0.label
		AlcoholHigh.stages.1.label
		GoJuiceAddiction.label
		LuciferiumAddiction.stages.0.label
		AlcoholHigh.stages.3.label
		PsychiteAddiction.stages.0.label
		AlcoholAddiction.stages.0.label
		SmokeleafAddiction.stages.0.label
		GoJuiceAddiction.stages.0.label
		AlcoholHigh.stages.5.label
		WakeUpAddiction.stages.0.label
		GoJuiceHigh.label
		AlcoholHigh.label
	22 tags only in ../RimWorld-ru/DefInjected/HediffDef: 
		WakeUpTolerance.stages.2.label
		SmokeleafTolerance.stages.2.label
		Alcohol.stages.5.label
		Alcohol.stages.2.label
		PsychiteTolerance.label
		PsychiteTolerance.stages.2.label
		Alcohol.stages.0.label
		LuciferiumAddiction.stages.1.label
		SmokeleafTolerance.stages.1.label
		SmokeleafTolerance.stages.3.label
		Alcohol.stages.4.label
		SmokeleafTolerance.label
		Alcohol.stages.3.label
		WakeUpTolerance.stages.1.label
		SmokeleafAddiction.stages.1.label
		Alcohol.stages.1.label
		Alcohol.label
		WakeUpAddiction.stages.1.label
		PsychiteAddiction.stages.1.label
		WakeUpTolerance.stages.3.label
		PsychiteTolerance.stages.1.label
		PsychiteTolerance.stages.3.label
File: /Hediffs_Global_Misc.xml:
	6 tags only in ../RimWorld-de/DefInjected/HediffDef: 
		DrugOverdose.stages.2.label
		DrugOverdose.comps.0.discoverLetterText
		DrugOverdose.stages.1.label
		DrugOverdose.label
		DrugOverdose.comps.0.discoverLetterLabel
		DrugOverdose.stages.0.label
File: /Hediffs_Local_Injuries.xml:
	2 tags only in ../RimWorld-de/DefInjected/HediffDef: 
		SurgicalCut.injuryProps.destroyedOutLabel
		SurgicalCut.injuryProps.destroyedLabel
	1 tags only in ../RimWorld-ru/DefInjected/HediffDef: 
		Gunshot.comps.2.instantlyOldLabel
```

**Comment by Elevator89** [comment]
Вроде это всё делали в №61, разве нет?

**Comment by Dimonasdf** [comment]
Ну так и в ветке большая часть сделана.

**Comment by Dinoabunai** [comment]
> Looking for missing files... 
1 files only in ../RimWorld-de/DefInjected/HediffDef: 
    /Hediffs_Global_Temperatures.xml
1 files only in ../RimWorld-ru/DefInjected/HediffDef: 
    /Hediffs_Global_Temperature.xml

Проверил - у нас названо правильно.

**Comment by Dinoabunai** [comment]
Актуальное задание:

1) **HediffDef\Hediffs_Global_Drugs.xml**
Объект **Alcohol** теперь называется **AlcoholHigh**. Переименовать соответственно.

2) **HediffDef\Hediffs_Global_Misc.xml**
Добавить перевод для объекта **DrugOverdose**.

3) **HediffDef\Hediffs_Local_Chronic.xml**
Опционально: поправить перевод объекта **Carcinoma**
"**Carcinoma**" переведена как "**рак**", хотя "**карцинома**" это отдельный его вид.

4) **HediffDef\Hediffs_Local_Infections.xml**
Опционально: поправить перевод объекта **SensoryMechanites**.
"**Sensory mechanites**" переведено как "**нейронные механиты**".

5) **HediffDef\Hediffs_Local_Injuries.xml**
Под вопросом: "**Crush**" переведено как "**перелом**".
Удалить перевод группы **injuryProps** у объекта **SurgicalCut**, т.к. у него нет таких тэгов.
Под вопросом: "**Shredded**" переведено как "**раздроблено взрывом**"

Актуальное задание полностью сформировано.

**Comment by Dinoabunai** [comment]
@Elevator89 

> 2) HediffDef\Hediffs_Global_Misc.xml
Добавить перевод для объекта DrugOverdose.

По поводу этого. В оригинале так:
`<label>drug overdose</label>`

Стоит нам перевести как "передозирока препаратом(ами)", "передозировка наркотиком(ами)" или поставить просто "передозировка"?
При этом я не могу сказать точно вызывает ли передозировку антималярин и алкоголь. Я целый день кормил поселенца антималярином (пока он не впал в ступор из-за смерти друга). Он съел 19 штук подряд и хоть бы хны. Но при этом у **MalariBlock** есть тэги:
```
`<overdoseSeverityOffset>
  <min>0.08</min>
   <max>0.14</max>
</overdoseSeverityOffset>`

```
Хотя они и относятся к **ThingDef**, их эффект все равно может учитываться в **HediffDef**.

Я предлагаю написать просто "передозировка".

**Comment by Dinoabunai** [comment]
@Elevator89 
Так же что скажешь по пунктам 3, 4, и 5?

**Comment by Elevator89** [comment]
2. Принимая во внимание всю неоднозначность перевода слова "drugs", предлагаю остановиться на варианте "передозировка"
3. Карцинома - вполне себе официальное название заболевания. Пусть оно и будет. Если кому из игроков будет непонятно - погуглят.
4. Не могу пока ответить - надо думать. "Сенсорные механиты"? Есть у нас где-то ещё переведённые "mechanites"?
5. "Crush" - "раздроблено", "раздавлено", "размозжено"
"Shredded" - "искромсано", "раздроблено", "разорвано"
Надо смотреть в игре, что для чего применяется, и делать выводы.

**Comment by Dimonasdf** [comment]
Посмотрите, что в [branch-4](https://github.com/Ludeon/RimWorld-ru/commits/branch-4) (Там один [коммит](https://github.com/Ludeon/RimWorld-ru/commit/bf8cc0e3f714887c63090689d6ef73edb697e8e2)). Должно быть сделано многое, если не всё.

1,2 исправлено/добавлено.

Насчёт терминов:

3. Не вижу смысла путать людей словом карцинома лишь потому, что:
"[Carcinoma](https://en.wikipedia.org/wiki/Carcinoma) is _a type_ of cancer that develops from epithelial cells."
С тем же успехом:
"[Карцинома](https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D1%86%D0%B8%D0%BD%D0%BE%D0%BC%D0%B0) — _вид злокачественной опухоли **(рак)**_, развивающейся из клеток эпителиальной ткани различных органов (кожи, слизистых оболочек и многих внутренних органов)".
Эта ткань есть и во внутренних органах, и таким образом всё равно покрываются все случаи.

4. Есть `fibrous mechanites` и `sensory mechanites`. Они заражают бионические органы, являясь эдаким специальным видом болезней для биоников. После некоторых раздумий и изучений я остановился на переводах `волоконные механиты` и `сенсорные механиты`. Хоть и видно, что перевод практически по тексту, могу пояснить.
Наиболее перспективные протезы конечностей - не металлические трубки и тросы, а искуственная мышечная ткань - волокно, обладающее свойствами мышц сокращаться и расслабляться в зависимости от получаемого сигнала. Вот механиты и волоконные.
Механиты сенсорные заражают другие типы бионических улучшений - воспринимающие и обрабатывающие. На данные момент в игре это глаза, но может появиться и ещё чего. Сенсорные, потому что 1. по тексту 2. поражение воспринимающих частей, сенсоров. Так что тоже просто всё. В четвёртом пункте не вижу смысла что-то менять.

5. Это переводите как хотите, тут никаких обоснований/предвзятостей не имею.

**Comment by Elevator89** [comment]
Карцинома - это рак, но не каждый рак - это карцинома. Поэтому рак - не катит здесь.
В то же время Carcinoma и Карцинома замечательно переводятся друг в друга без потери смысла. 
Вопрос закрыт.

**Comment by Dimonasdf** [comment]
@Elevator89 лады, по третьему пункту вопросов нет.
Надеюсь, по 4 тоже ни у кого больше нет сомнений.

**Comment by Dinoabunai** [comment]
@Elevator89 

> 1) "Пьяный", "пьян"?

Да не, текст нормальный там боле-менее. Поменялось именно:
**`<defName>AlcoholHigh</defname>`**
Раньше было просто:
**`<defName>Alcohol</defname>`**
А сам текст соответствует.

> 4) Не могу пока ответить - надо думать. "Сенсорные механиты"? Есть у нас где-то ещё переведённые "mechanites"?

Есть и используется. Так и переведено - "**механиты**". Вопрос был в основном про прилагательное.
Так как не понятно откуда взялось слово "**нейронные**" (по английски нейроны это "**neurons**")

>5) "Crush" - "раздроблено", "раздавлено", "размозжено". "Shredded" - "искромсано", "раздроблено", "разорвано"

Потестирую.

**Comment by Dimonasdf** [comment]
А, нейронные, точно.
Как раз вспомнил, чем мне сенсорные не понравились.
Их можно воспринять как сéнсорные, типа механиты, которые можно (и нужно) трогать. А на самом деле они тогда должны быть сенсо́рными, чтобы иметь отношение к сенсо́рике, т.е. восприятию. Отсюда я расширил понятие до "воспринимающие и обрабатывающие", и со второго попал на мозг. Ну и сделал их нейронными. Чтобы вконец диаметрально разделить "мышечные" и "мозговые".

В принципе, можно и сенсорные сделать, вроде нормально. Но можно оставить и как было. Смотрите сами.

**Comment by Ohar** [comment]
Давайте их так и назовём — _мышечные_ и _мозговые_, чем играться с ударениями.

**Comment by Dimonasdf** [comment]
@Ohar Не, вот это будет в корне не верно. Потому что они и не мышечные, и не мозговые.

**Comment by Dinoabunai** [comment]
Мне кажется лучше сделать "сенсорные". У игрока все равно не будет выбор - трогать их или нет. Они или заведутся в организме, либо нет. А к мозгу они не факт что имеют отношение. Может речь идет про то что у них есть некие сенсоры.

**Comment by Elevator89** [comment]
"Сенсорные механиты" - нормальный вариант, учитывая, что они действуют именно на сенсоры. Переводится в обе стороны однозначно.

**Comment by Ohar** [comment]
Так они не _се́нсорные_, а _сенсо́рные_ — ударение меняет смысл. Предлагаю его везде добавить.

**Comment by Dinoabunai** [comment]
@Ohar 
А с чего ты взял? В оригинале-то просто "sensory".

**Comment by Elevator89** [comment]
> А с чего ты взял? В оригинале-то просто "sensory".

**Сенсо́рный**, то есть связанный с органами чувств, переводится на английский как **sensory** (sensory deficits), а вот **се́нсорный**, то есть содержищий сенсоры, - как просто **sensor** (sensor panel)

Два разных понятия из разных областей. По русски пишутся одинаково. Поэтому нужно добавить ударение: **сенсо́рный**. Главное, чтобы игра это нормально переварила и показала.

**Comment by Dinoabunai** [comment]
ОК

**Comment by Dinoabunai** [comment]
@Elevator89 
Потестировал немного ранения. 4 человека были жестоко избиты дубинами. У всех травмы вида "**Bruise**" (сейчас переведено как "**ушиб**"). Про "**shredded**" вы и сами знаете.

В итоге - чего будем делать с **Crush** и **Shredded**?

**Comment by Elevator89** [comment]
**Bruise** я бы перевёл как "синяк". Более живописно и красочно, чем просто "ушиб".
**Crushed** - раздавлено
**Shredded** - взрывная травма/ранение

**Comment by Dinoabunai** [comment]
ОК

**Comment by Ohar** [comment]
@Elevator89 Shredded → это не просто «взрывная травма», а иссечение осколками от взрыва, [множество грубоких порезов](https://www.google.ru/search?q=Shredded+wound&newwindow=1&safe=off&source=lnms&tbm=isch&sa=X&ved=0ahUKEwilrZD127bPAhUsIpoKHQWUAb8Q_AUICCgB). Перевести предлагаю как _«иссечение осколками»_ либо _«осколочное ранение»_.

**Comment by Dinoabunai** [comment]
Кто найдет как травмировать поселенцев, чтобы у них осталось **Crushed** - получит пирожок.
