### ISSUE TITLE
HistoryAutoRecorderDef-IncidentDef // Branch 5

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#102]
Проверить все изменения текста:
HistoryAutoRecorderDef
HistoryAutoRecorderGroupDef
IncidentDef

**Comment by Dimonasdf** [comment]
https://github.com/Ludeon/RimWorld-ru/tree/branch-5

**Comment by Elevator89** [comment]
Всё на месте. Всё переведено. Закрываю.

**Comment by Dimonasdf** [comment]
Можно было подождать, например.
