### ISSUE TITLE
Royal favor

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1020]
Это ресурс, который даётся за выполнение квестов для Империи. Надо его как-то назвать.
Милость?
Благосклонность?
Расположение?

**Comment by kamadz** [comment]
Расположение лично мне больше нравится, но так теряется в некоторой степени смысл непосредственной зависимости игрока от главы фракции. В то время как "расположение" означает категорию отношения в целом, милость передаёт ту самую "überposition", в которой находится Император, относительно нас (игрока), и как мы, его подчинённые, должны быть благодарны за его благосклонность. Милость придаёт более подходящий стилистический окрас.
