### ISSUE TITLE
JobDefs-LifeStageDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#104]
Проверить все изменения текста:
JobDef
JoyKindDef
KeyBindingCategoryDef
KeyBindingDef
LifeStageDef

Должно быть уже сделано:
JobDef

**Comment by Elevator89** [comment]
```
1 files only in ../RimWorld-de/DefInjected/JobDef: 
	/Jobs_Gathering.xml
1 files only in ../RimWorld-ru/DefInjected/JobDef: 
	/Jobs_Gatherings.xml
```
Остальное на месте

**Comment by Elevator89** [comment]
Выполнено и смерджено:
SHA-1: 612adfbd1d304df70e50cb0da0c724d212658840
* Merge pull request #118 from Ludeon/job-keybinding
[0.15.1284] Closes #104. Fix name and format
