### ISSUE TITLE
MainTabDef-NeedDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#105]
Проверить все изменения текста:
MainTabDef
MapConditionDef
MentalStateDef

Должно быть уже сделано:
NeedDef

**Comment by Elevator89** [comment]
```
File: /MainTabs.xml:
	2 tags only in ../RimWorld-ru/DefInjected/MainTabDef: 
		Statistics.label
		Statistics.description

File: /MentalStates_Mood.xml:
	7 tags only in ../RimWorld-de/DefInjected/MentalStateDef: 
		BingingFood.baseInspectLine
		FireStartingSpree.baseInspectLine
		Berserk.baseInspectLine
		WanderSad.baseInspectLine
		WanderPsychotic.baseInspectLine
		GiveUpExit.baseInspectLine
		WanderOwnRoom.baseInspectLine
	12 tags only in ../RimWorld-ru/DefInjected/MentalStateDef: 
		FireStartingSpree.inspectLine
		BingingAlcohol.label
		BingingAlcohol.inspectLine
		WanderOwnRoom.inspectLine
		BingingFood.inspectLine
		BingingAlcohol.beginLetterLabel
		Berserk.inspectLine
		WanderSad.inspectLine
		GiveUpExit.inspectLine
		BingingAlcohol.beginLetter
		BingingAlcohol.recoveryMessage
		WanderPsychotic.inspectLine

File: /MentalStates_Special.xml:
	4 tags only in ../RimWorld-de/DefInjected/MentalStateDef: 
		PanicFlee.baseInspectLine
		SocialFighting.baseInspectLine
		WanderConfused.baseInspectLine
		Manhunter.baseInspectLine
	4 tags only in ../RimWorld-ru/DefInjected/MentalStateDef: 
		Manhunter.inspectLine
		SocialFighting.inspectLine
		PanicFlee.inspectLine
		WanderConfused.inspectLine
```

**Comment by Dinoabunai** [comment]
Актуальное задание полностью сформировано.

1) **MainTabDef\MainTabs.xml**
* В русском файле указан перевод для устаревшего объекта **Statistics**. Удалить строки, относящиеся к нему.
* **Под вопросом:** "**architect**" переведено как "**создать**".  Возможно стоит заменить на "**проектировать/проектирование**"?
* **Под вопросом:** "**restrict**" переведено как "**разрешения**". Возможно стоит заменить на "**ограничения**"?

2) **MapConditionDef\MapConditions_Misc.xml**
* **PsychicDrone** и **PsychicSoothe** переведены одинаково.
* В файле много текста. Проверить перевод и исправить смысловые и грамматические ошибки.

3) **MentalStateDef\MentalStates_Mood.xml**
* Все тэги, которые раньше назывались **inspectLine** теперь называются **baseInspectLine**. Необходимо произвести замену для каждого объекта.
* **Под вопросом:** Слово "**berserk**" переведено как "**психоз**", что терминологически неверно. Провести необходимые исследования и изменить перевод.
* Вместо старого объекта **BingingAlcohol** теперь используется объект **BingingDrugExtreme**.
Привести перевод в соответствии с этим изменением.
* В файле много текста, местами он спорный и не всегда согласуется с оригиналом. Проверить перевод и исправить смысловые и грамматические ошибки.

4) **MentalStateDef\MentalStates_Special.xml**
* Все тэги, которые раньше назывались **inspectLine** теперь называются **baseInspectLine**. Необходимо произвести замену для каждого объекта.
* В файле много текста. Проверить перевод и исправить смысловые и грамматические ошибки.

5) **NeedDef\Needs_Drugs.xml**
* Удалить перевод для объекта **Chemical_GoJuice**, т.к. он вынесен в отдельное задание.
* Поправить кривую табуляцию в файле.
* **Опционально:** Проверить текст в файле на наличие ошибок.

6) **NeedDef\Needs_Misc.xml**
* **Опционально:** Проверить текст в файле на наличие ошибок.

**Comment by Dinoabunai** [comment]
@Elevator89 
Согласен с актуальным заданием?

**Comment by Dinoabunai** [comment]
@Elevator89 

1) **MainTabDef\MainTabs.xml**
> Под вопросом: "architect" переведено как "создать". Возможно стоит заменить на "проектировать/проектирование"?

> Под вопросом: "restrict" переведено как "разрешения". Возможно стоит заменить на "ограничения"?

2) **MapConditionDef\MapConditions_Misc.xml**
> PsychicDrone и PsychicSoothe переведены одинаково.

3) **MentalStateDef\MentalStates_Mood.xml**
> Под вопросом: Слово "berserk" переведено как "психоз", что терминологически неверно. Провести необходимые исследования и изменить перевод.

Что скажешь по этим пунктам?

**Comment by Elevator89** [comment]
1. По поводу "Создать". Когда я пытался искать что-то в официальной англоязычной вики, я не сразу понял что "Architect" соответствует пункту меню "Создать". Думаю, заменить на более близкий и дословный вариант - хорошая идея. Надо только определиться, что мы будем использовать: глаголы или существительные.
"architect" - "проектировать/проектирование"
"restrict" - "ограничить/ограничения"
На мой взгляд существительные будут смотреться лучше, но лучше потестить.
2. Чуть позже посмотрю.3. Сходу могу предложить "Буйство".

**Comment by Elevator89** [comment]
2. PsychicDrone и PsychicSoothe переведены одинаково неправильно. Там не "зонд" должен быть, а "гул" и "успокоение" соответственно. В немецкой версии именно так.

**Comment by Elevator89** [comment]
Возьму себе

**Comment by Dinoabunai** [comment]
@Elevator89 
>Сходу могу предложить "Буйство".

Можно еще "неистовство", "приступ ярости", "ярость", "впал в ярость" или просто "берсерк" - слово знакомо публике и вполне литературное.

**Comment by Dimonasdf** [comment]
> Там не "зонд" должен быть, а "гул" и "успокоение"

Полгода назад же это исправил, где дрон опять?

**Comment by Elevator89** [comment]
> Полгода назад же это исправил, где дрон опять?

А теперь погугли значение слова drone, и ты увидишь "гул". Это не тот дрон, который квадрокоптер )!

**Comment by Dinoabunai** [comment]
@Elevator89 
Что выберем для "**berserk**"?
Мне больше всего понравились варианты "**неистовство**" и "**берсерк**".

**Comment by Elevator89** [comment]
Переносим обсуждение в [пулреквест](https://github.com/Ludeon/RimWorld-ru/pull/149).

**Comment by Elevator89** [comment]
Выполнено
