### ISSUE TITLE
После патча апрельского (28.04) пропали описания части квестов

### ISSUE THREAD

**Issue by Blinnna** [Ludeon/RimWorld-ru#1057]
Я не смогла найти в каких конкретно файлах ошибка, т.к. пока не очень разбираюсь что и где.

Квесты разные, погода, пленники, схроны, постройки и т.п.
![2020-05-05_19-15-07](https://user-images.githubusercontent.com/8790596/81089427-06358280-8f05-11ea-9384-103102dc8b77.jpg)

**Comment by Maxatma** [comment]
может будет полезно в поисках причины, скрины с квестами, где не переведено, а в одном Could  not resolve any root. 
Перевод качал сегодня.


<img width="1680" alt="Screen Shot 2020-05-07 at 21 06 40" src="https://user-images.githubusercontent.com/7135226/81304117-d6be7b80-90a6-11ea-8477-59bc6a25f1fb.png">



<img width="1680" alt="Screen Shot 2020-05-07 at 21 06 14" src="https://user-images.githubusercontent.com/7135226/81304287-108f8200-90a7-11ea-9bd7-38a14c381b37.png">

<img width="1680" alt="Screen Shot 2020-05-07 at 21 06 51" src="https://user-images.githubusercontent.com/7135226/81304214-f786d100-90a6-11ea-8b30-8bfd63567072.png">

**Comment by Elevator89** [comment]
Тут очень помог бы вывод консоли об этой ошибке

**Comment by Elevator89** [comment]
Какая версия игры? Когда скачан перевод?

**Comment by Blinnna** [comment]
Версия  [1.1.2618] перевод отдельно не скачивался, т.е. то, что включается в игре при выборе русского языка.

**Comment by Maxatma** [comment]
-----------------
Id: 168
State: Ongoing
Data:
<saveable Class="Quest">
  <id>168</id>
  <name>Указ о Производстве (дамская Шляпка)</name>
  <appearanceTick>48683579</appearanceTick>
  <acceptanceTick>48683579</acceptanceTick>
  <acceptedBy>null</acceptedBy>
  <initiallyAccepted>True</initiallyAccepted>
  <challengeRating>2</challengeRating>
  <description>Could not resolve any root: QuestDescription</description>
  <root>Decree_ProduceItem</root>
  <signalsReceivedDebug IsNull="True" />
  <parts>
    <li Class="QuestPart_Letter">
      <inSignal>Quest168.OuterNodeCompleted</inSignal>
      <letter Class="StandardLetter">
        <ID>2607</ID>
        <def>NeutralEvent</def>
        <label>&lt;color=#D09B61FF&gt;Pawulon&lt;/color&gt;'s decree forgotten</label>
        <lookTargets IsNull="True" />
        <relatedFaction>null</relatedFaction>
        <text>&lt;color=#D09B61FF&gt;Pawulon&lt;/color&gt; has forgotten about его decree.</text>
        <quest>Quest_168</quest>
        <hyperlinkThingDefs IsNull="True" />
      </letter>
      <useColonistsOnMap>null</useColonistsOnMap>
    </li>
    <li Class="QuestPart_QuestEnd">
      <inSignal>Quest168.OuterNodeCompleted</inSignal>
      <outcome>Fail</outcome>
    </li>
    <li Class="QuestPart_Delay">
      <inSignalEnable>Quest168.Initiate</inSignalEnable>
      <outSignalsCompleted>
        <li>Quest168.OuterNodeCompleted</li>
      </outSignalsCompleted>
      <state>Enabled</state>
      <enableTick>48683579</enableTick>
      <delayTicks>4800000</delayTicks>
      <inspectStringTargets />
    </li>
    <li Class="QuestPart_Letter">
      <inSignal>Quest168.OuterNodeCompleted2</inSignal>
      <letter Class="StandardLetter">
        <ID>2608</ID>
        <def>NeutralEvent</def>
        <label>Decree cancelled</label>
        <lookTargets IsNull="True" />
        <relatedFaction>null</relatedFaction>
        <text>&lt;color=#D09B61FF&gt;Pawulon&lt;/color&gt; has grudgingly cancelled the decree 'Указ о Производстве (дамская Шляпка)' since it cannot be completed.</text>
        <quest>Quest_168</quest>
        <hyperlinkThingDefs IsNull="True" />
      </letter>
      <useColonistsOnMap>null</useColonistsOnMap>
    </li>
    <li Class="QuestPart_QuestEnd">
      <inSignal>Quest168.OuterNodeCompleted2</inSignal>
      <outcome>Unknown</outcome>
    </li>
    <li Class="QuestPart_Pass">
      <inSignal>Quest168.Incompletable</inSignal>
      <outSignal>Quest168.OuterNodeCompleted2</outSignal>
    </li>
    <li Class="QuestPart_QuestEnd">
      <inSignal>Quest168.OuterNodeCompleted3</inSignal>
      <outcome>Fail</outcome>
    </li>
    <li Class="QuestPart_Pass">
      <inSignal>Quest168.asker.ChangedFaction</inSignal>
      <outSignal>Quest168.OuterNodeCompleted3</outSignal>
    </li>
    <li Class="QuestPart_SituationalThought">
      <inSignalEnable>Quest168.OuterNodeCompleted4</inSignalEnable>
      <def>DecreeUnmet</def>
      <pawn>Thing_Human661</pawn>
      <delayTicks>300000</delayTicks>
    </li>
    <li Class="QuestPart_Delay">
      <inSignalEnable>Quest168.Initiate</inSignalEnable>
      <outSignalsCompleted>
        <li>Quest168.OuterNodeCompleted4</li>
      </outSignalsCompleted>
      <state>Enabled</state>
      <enableTick>48683579</enableTick>
      <delayTicks>300000</delayTicks>
      <inspectStringTargets />
    </li>
    <li Class="QuestPart_AddMemoryThought">
      <inSignal>Quest168.OuterNodeCompleted5</inSignal>
      <addToLookTargets>True</addToLookTargets>
      <def>DecreeMet</def>
      <pawn>Thing_Human661</pawn>
      <otherPawn>null</otherPawn>
    </li>
    <li Class="QuestPart_ChangeNeed">
      <inSignal>Quest168.OuterNodeCompleted5</inSignal>
      <pawn>Thing_Human661</pawn>
      <need>Authority</need>
      <offset>0.5</offset>
    </li>
    <li Class="QuestPart_QuestEnd">
      <inSignal>Quest168.OuterNodeCompleted5</inSignal>
      <outcome>Success</outcome>
      <sendLetter>True</sendLetter>
    </li>
    <li Class="QuestPart_ThingsProduced">
      <inSignalEnable>Quest168.Initiate</inSignalEnable>
      <outSignalsCompleted>
        <li>Quest168.OuterNodeCompleted5</li>
      </outSignalsCompleted>
      <state>Enabled</state>
      <enableTick>48683579</enableTick>
      <def>Apparel_HatLadies</def>
      <stuff>Cloth</stuff>
      <count>59</count>
    </li>
  </parts>
  <tags />
</saveable>

Active QuestParts:
QuestPart_Delay (index=2)
QuestPart_Delay (index=9)
QuestPart_ThingsProduced (index=13)

Перевод скачан/добавлен сегодня, v 1.1.2618

**Comment by Elevator89** [comment]
> v 1.1.2618

Это кривая весрия игры. Нужно обновлять до хотя бы 1.1.2624

**Comment by Maxatma** [comment]
@Elevator89 понял, спасибо.

**Comment by Elevator89** [comment]
Излечилось апдейтом игры
