### ISSUE TITLE
PawnCapacityDef-RaidStrategyDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#106]
Проверить все изменения текста:
PawnCapacityDef
PawnKindDef
PawnRelationDef
RaidStrategyDef

Узнать, куда ушёл RaidStrategies.xml

**Comment by Elevator89** [comment]
Все файлы и теги на месте.  RaidStrategies.xml - в DefInjected\RaidStrategyDef

**Comment by Elevator89** [comment]
Ишью предлагается к закрытию

**Comment by Ohar** [comment]
@Elevator89 Закрываем?

**Comment by Elevator89** [comment]
Закрыл

**Comment by Dinoabunai** [comment]
1) **PawnKindDefs_Humanlikes\PawnKinds_Mercenary.xml**
* **Опционально:** **`<MercenarySniper.label>снайпер</MercenarySniper.label>`**
У всех **Mercenary** в файле стоит приставка "**наёмник**", в оригинале у **MercenarySniper** в лейбле тоже указано "**mercenary sniper**".

2) **PawnKindDefs_Humanlikes\PawnKinds_Player.xml**
* "**colonist**" переведено как "**житель**" с пометкой:
**`<!--Необходимо для избежания тавтологии "поселенец Поселения"-->`**
Хотя технически тавтология будет только до того момента, когда поселению назначат название.

3) **PawnKindDefs_Humanlikes\PawnKinds_Tribal.xml**
* В русском все переведено как:
"**воин племени**"
"**лучник племени**"
"**вождь племени**"
"**торговец племени**"
Хотя в файле оригинала стоят просто:
"**warrior**"
"**trader**"
"**archer**"
"**chief**"

4) **PawnRelationDefs\PawnRelations_FamilyByBlood.xml**
* В русском написано:
  <HalfSibling.label>сводный брат</HalfSibling.label>
  <HalfSibling.labelFemale>сводная сестра</HalfSibling.labelFemale>
Хотя в оригинале просто:
    <defName>HalfSibling</defName>
    <label>brother</label>
    <labelFemale>sister</labelFemale>
	
* Слово "grandmother" переведено как "бабка". Это как вообще?
Причем не только в этом файле. До кучи "grandfather" переведен как "дед",
можно перевести как "дедушка" (опционально). То же с "прадедом" и "пробабкой".

* "cousin once removed" перевено как "двоюродный брат другого поколения"
Не знакомый для меня оборот, возиожно все правильно, но хорошо бы перепроверить.

5) RaidStrategyDef\RaidStrategies.xml
* <StageThenAttack.letterLabelEnemy> переведен отлично от <ImmediateAttack.letterLabelEnemy> и <ImmediateAttackSmart.letterLabelEnemy>
Хотя в оригинале во всех 3 лейблах стоит "Raid"

* Опционально: 
<Siege.arrivalTextFriendly>Похоже, что они хотят использовать тактику осады, чтобы помочь вам.</Siege.arrivalTextFriendly>
"тактику осады" можно заменить на "осадную тактику.

**Comment by Dinoabunai** [comment]
@Elevator89 

На всякий случай проверил это дело. Нашел такие спорные места:

1) **PawnKindDefs_Humanlikes\PawnKinds_Mercenary.xml**
* **Опционально:** **`<MercenarySniper.label>снайпер</MercenarySniper.label>`**
У всех **Mercenary** в файле стоит приставка "**наёмник**", в оригинале у **MercenarySniper** в лейбле тоже указано "**mercenary sniper**".

2) **PawnKindDefs_Humanlikes\PawnKinds_Player.xml**
* "**colonist**" переведено как "**житель**" с пометкой:
**`<!--Необходимо для избежания тавтологии "поселенец Поселения"-->`**
Хотя технически тавтология будет только до того момента, когда поселению назначат название.

3) **PawnKindDefs_Humanlikes\PawnKinds_Tribal.xml**
* В русском все переведено как:
"**воин племени**"
"**лучник племени**"
"**вождь племени**"
"**торговец племени**"

   Хотя в файле оригинала стоят просто:
"**warrior**"
"**trader**"
"**archer**"
"**chief**"

4) **PawnRelationDefs\PawnRelations_FamilyByBlood.xml**
* В русском написано:
**`  <HalfSibling.label>сводный брат</HalfSibling.label>`**
**`  <HalfSibling.labelFemale>сводная сестра</HalfSibling.labelFemale>`**
   
   Хотя в оригинале просто:
**`  <defName>HalfSibling</defName>`**
**`  <label>brother</label>`**
**`  <labelFemale>sister</labelFemale>`**
	
* Слово "**grandmother**" переведено как "**бабка**". Это как вообще?
Причем не только в этом файле. До кучи "**grandfather**" переведен как "**дед**",
можно перевести как "**дедушка**" (опционально). То же с "**прадедом**" и "**пробабкой**".

* "**cousin once removed**" переведено как "**двоюродный брат другого поколения**"
Не знакомый для меня оборот, возможно все правильно, но хорошо бы перепроверить.

5) **RaidStrategyDef\RaidStrategies.xml**
* **`<StageThenAttack.letterLabelEnemy>`** переведен отлично от `**<ImmediateAttack.letterLabelEnemy>**` и `**<ImmediateAttackSmart.letterLabelEnemy>**`.
У **StageThenAttack** написано "**Атака**", когда в 2 остальных случаях написано "**Налёт**".
Хотя в оригинале во всех 3 лейблах стоит "**Raid**"

* **Опционально:** 
`**<Siege.arrivalTextFriendly>Похоже, что они хотят использовать тактику осады, чтобы помочь вам.</Siege.arrivalTextFriendly>**`
"**тактику осады**" можно заменить на "**осадную тактику**".

**Comment by Ohar** [comment]
> В русском написано:
```xml
<HalfSibling.label>сводный брат</HalfSibling.label>
<HalfSibling.labelFemale>сводная сестра</HalfSibling.labelFemale>
```
Хотя в оригинале просто:
```xml
<defName>HalfSibling</defName>
<label>brother</label>
<labelFemale>sister</labelFemale>
```

Дык _HalfSibling_ и есть наполовину родной, сиречь сводный.

**Comment by Elevator89** [comment]
Возьму на себя тогда

**Comment by Dinoabunai** [comment]
@Ohar 
>Дык HalfSibling и есть наполовину родной, сиречь сводный.

Да, только почему русские игроки будут знать о том, что павн сводный, а английские - нет?

 
> Ну там какбэ различается «появились и бегут сюда» и «появились и полдня тусуют за холмом» — эти события требуют разной реакции игрока и называть их следует различно.

Опять таки почему только русские игроки будут знать об этом?

**Comment by Ohar** [comment]
>Да, только почему русские игроки будут знать о том, что павн сводный, а английские - нет?

Плохо быть англоязычным игроком, правда?

**Comment by Dinoabunai** [comment]
Угу.

**Comment by Elevator89** [comment]
Выполнено
