### ISSUE TITLE
Смена "королевская милость" на "милость короны"

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1063]
Таким образом устраняется противоречие "королевского" в империи

**Comment by kamadz** [comment]
Добавляю к этому ишью предложение заменить также "королевскую помощь" на "военную помощь" или хотя бы "помощь короны"

**Comment by Elevator89** [comment]
Звучит дельно. Мне тоже "милость короны" больше нравится, и звучит солиднее
