### ISSUE TITLE
RecipeDef-ResearchProjectDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#107]
Брать это задание стоит после того, как будет выполнено задание #111.

Проверить все изменения текста:
RecipeDef
RecordDef
ResearchProjectDef

**Comment by Elevator89** [comment]
```
File: /Recipes_Add.xml:
	48 tags only in ../RimWorld-ru/DefInjected/RecipeDef: 
		Make_Gun_PumpShotgun.label
		Make_Apparel_VestPlate.description
		Make_Gun_AssaultRifle.label
		Make_Apparel_PowerArmorHelmet.label
		Make_Apparel_PowerArmor.jobString
		Make_Gun_SurvivalRifle.jobString
		Make_Apparel_PowerArmor.description
		Make_Apparel_VestPlate.jobString
		Make_Apparel_PowerArmorHelmet.description
		Make_Gun_Minigun.label
		Make_Apparel_KevlarHelmet.description
		Make_Gun_HeavySMG.label
		Make_Apparel_PowerArmorHelmet.jobString
		Make_Gun_Minigun.description
		Make_Gun_Minigun.jobString
		Make_Gun_PumpShotgun.jobString
		Make_Gun_SurvivalRifle.label
		Make_Gun_Pistol.jobString
		Make_Apparel_MilitaryHelmet.label
		Make_Apparel_PowerArmor.label
		Make_Gun_HeavySMG.jobString
		Make_Gun_HeavySMG.description
		Make_Apparel_MilitaryHelmet.jobString
		Make_Gun_PDW.label
		Make_Gun_ChargeRifle.jobString
		Make_Gun_IncendiaryLauncher.jobString
		Make_Gun_IncendiaryLauncher.label
		Make_Gun_LMG.description
		Make_Gun_SniperRifle.jobString
		Make_Gun_Pistol.description
		Make_Gun_ChargeRifle.description
		Make_Apparel_KevlarHelmet.label
		Make_Gun_AssaultRifle.description
		Make_Gun_SniperRifle.description
		Make_Gun_SurvivalRifle.description
		Make_Apparel_KevlarHelmet.jobString
		Make_Gun_SniperRifle.label
		Make_Gun_LMG.jobString
		Make_Apparel_VestPlate.label
		Make_Gun_PDW.description
		Make_Gun_PumpShotgun.description
		Make_Gun_ChargeRifle.label
		Make_Gun_AssaultRifle.jobString
		Make_Gun_PDW.jobString
		Make_Gun_LMG.label
		Make_Gun_Pistol.label
		Make_Apparel_MilitaryHelmet.description
		Make_Gun_IncendiaryLauncher.description

File: /Recipes_Cremation.xml:
	3 tags only in ../RimWorld-de/DefInjected/RecipeDef: 
		BurnApparelCampfire.jobString
		BurnApparelCampfire.description
		BurnApparelCampfire.label

File: /Recipes_Drugs.xml:
	6 tags only in ../RimWorld-de/DefInjected/RecipeDef: 
		BurnDrugs.label
		BurnDrugs.jobString
		MakeWort.jobString
		MakeWort.description
		BurnDrugs.description
		MakeWort.label
	3 tags only in ../RimWorld-ru/DefInjected/RecipeDef: 
		BrewBeer.description
		BrewBeer.label
		BrewBeer.jobString
```

**Comment by Dinoabunai** [comment]
Перевод исследование PassiveCooler не согласуется с предметом. Исправить описание исследования.

**Comment by Dinoabunai** [comment]
@Elevator89 
Очень много текста для проверки и правки. Очень громоздко.
Предлагаю разбить на задания "**RecipeDef-RecordDefs**" и "**ResearchProjectDef **".

**Comment by Ohar** [comment]
@Dinoabunai Поддерживаю, чем атомарнее задачи, тем лучше.

**Comment by Dinoabunai** [comment]
1) **RecipeDef\Recipes_Add.xml**

* Добавить рецепты для:
**smokeleaf joint**
**Machine pistol**
**malari-block**
**flake**
**yayo**
**wake-up**
**medecine**

Согласовывать их с папкой **ThingDef**.

2) **RecipeDef\Recipes_Cremation.xml**
* Добавить перевод для объекта **BurnApparelCampfire**.

3) **RecipeDef\Recipes_Drugs.xml**
* Добавить перевод для объектов **MakeWort** и **BurnDrugs**.
* Удалить перевод для устаревшего объекта **BrewBeer**.

4) **RecipeDef\Recipes_Food.xml**
* **MakePemmican** - исправить на "**пеммикан**".

5) **RecipeDef\Recipes_Production.xml**
* Объект **SmeltWeapon** переведен как "**извлечь исходный материал из оружия**".
В оригинале просто "**smelt metal from weapon**".

* Объект **MakeArtilleryShell** можно исправить с "**сделать снаряд**" на "**сделать артиллерийский снаряд**".

* Объекты **MakeWoodPlanks_Hand** и **MakeWoodPlanks_Electric** - закомментированы и более не используются. Можно их удалить.

6) **RecipeDef\Recipes_Surgery.xml**
* Объект **ExciseCarcinoma**. **Carcinoma* теперь называется "**карцинома**". Соответственно исправить перевод.

7)**RecordDef\Records_Misc.xml**
* Под вопросом: "**убийства (животные)**" и прочие убийства со скобочками можно переделать в "**убито животных**" иди "**убийств животных**" и т.д.
Хотя в оригинале тоже использованы скобки: "**kills (animals)**"

* Опционально: **TimesOnFire** переведено как "**горений пережито**" (оригинал - "**times on fire**").

* В **TimesOnFire.description** кто-то из переводчиков оставил вот этого молодого человека: **ʕ •̀ ᴥ •́ ʔ**
Убрать его. Для справки - в оригинале его тоже нет.

8) **RecordDef\Records_Time.xml**
* **Опционально:** **TimeInBedForMedicalReasons** переведено как "**времени в кровати (мед.)**".
В оригинале "**time in a bed for medical reasons**". Можно хотя бы раскрыть скобки или поставить более полную фразу.
Места хватит.

* **Опционально: TimeInMentalState** переведено как "**времени в сост. душевного срыва**".
Можно раскрыть фразу "**в состоянии**". Протестировать - нормально ли она влезает в игровое окно.

**Comment by Dinoabunai** [comment]
@Ohar добавил актуальное задание.

**Comment by Dinoabunai** [comment]
Разбито на задания #161 - RecipeDef-RecordDefs и #162 - ResearchProjectDef.
