### ISSUE TITLE
2635 Core Keyed

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1078]
Автоформатированные файлы: 
[2635 - Core Keyed 1.zip](https://github.com/Ludeon/RimWorld-ru/files/4638212/2635.-.Core.Keyed.1.zip)

Порядок действий:

1. Распаковать архив в Core/Keyed с заменой существующих файлов
2. Просмотреть изменения при помощи diff-инструмента
3. Модифицировать перевод в соответствии этими изменениями

**Comment by kamadz** [comment]
Взял
