### ISSUE TITLE
2635 Royalty DefInjected ThingDef 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1083]
Автоформатированные файлы:
[2635 - Royalty DefInjected ThingDef 2.zip](https://github.com/Ludeon/RimWorld-ru/files/4639213/2635.-.Royalty.DefInjected.ThingDef.2.zip)

Порядок действий:

1. Распаковать архив в Royalty/DefInjected/ThingDef с заменой существующих файлов
2. Просмотреть изменения при помощи diff-инструмента
3. Модифицировать перевод в соответствии этими изменениями

Удалить Royalty/DefInjected/ThingDef/Hediffs_BodyParts_Archotech.xml

**Comment by kamadz** [comment]
взял
