### ISSUE TITLE
2635 Royalty Keyed

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1084]
Автоформатированные файлы:
[2635 - Royalty Keyed.zip](https://github.com/Ludeon/RimWorld-ru/files/4639216/2635.-.Royalty.Keyed.zip)

Порядок действий:

1. Распаковать архив в Royalty/Keyed с заменой существующих файлов
2. Просмотреть изменения при помощи diff-инструмента
3. Модифицировать перевод в соответствии этими изменениями

**Comment by kamadz** [comment]
взял
