### ISSUE TITLE
Goodwill

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1088]
Надо перевести единообразно. Выбрать "отношения" или "репутация"

**Comment by Blinnna** [comment]
Мне больше нравится вариант уровень отношений, чем репутация.

**Comment by Elevator89** [comment]
Сейчас в игре есть два термина:
"Relations" - отношения. 
"Goodwill" - репутация.
> **Репутация** отображает **отношения** между вами и другими фракциями.

Во всём переводе это соответствие соблюдается. Менять это не вижу смысла.
