### ISSUE TITLE
SkillDef-StatDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#109]
Проверить все изменения текста:
SkillDef
SpecialThingFilterDef
StatCategoryDef
StatDef

Тут тоже что-то поменялось местами, посмотреть подробно.
Основное внимание на StatDef.
Сообщить, если необходимо разделить issue.

**Comment by Elevator89** [comment]
```
1 files only in ../RimWorld-ru/DefInjected/TaleDef: 
	/Tales_NoPawn.xml

File: /Storytellers.xml:
	1 tags only in ../RimWorld-de/DefInjected/StorytellerDef: 
		Tutor.label
	3 tags only in ../RimWorld-ru/DefInjected/StorytellerDef: 
		Randy.quotation
		Cassandra.quotation
		Phoebe.quotation

File: /ThingCategories.xml:
	1 tags only in ../RimWorld-de/DefInjected/ThingCategoryDef: 
		CorpsesInsect.label
	1 tags only in ../RimWorld-ru/DefInjected/ThingCategoryDef: 
		Resources.label
```

**Comment by Dinoabunai** [comment]
Беру.

**Comment by Dinoabunai** [comment]
Актуальное задание:

1) **File: /Skills.xml.**
В **~Russian\DefInjected\SkillDef\Skills.xml** указаны старые теги **`<X.label>`**.
Они больше не используются. Их нужно удалить.

**Comment by Dinoabunai** [comment]
Актуальное задание полностью сформировано.

**Comment by Dinoabunai** [comment]
Задание выполнено.
Пул-реквест: https://github.com/Ludeon/RimWorld-ru/pull/119

**Comment by Dinoabunai** [comment]
@Elevator89 
По сути из ораклового скрипта было актуально только:

File: /Skills.xml:
    12 tags only in ../RimWorld-ru/DefInjected/SkillDef: 
        Melee.label
        Mining.label
        Artistic.label
        Social.label
        Growing.label
        Shooting.label
        Construction.label
        Research.label
        Animals.label
        Crafting.label
        Medicine.label
        Cooking.label
File: /Stats_Pawns_WorkRecipes.xml:
    2 tags only in ../RimWorld-de/DefInjected/StatDef: 
        DrugProductionSpeed.label
        DrugProductionSpeed.description

**Comment by dragomano** [comment]
Удаление якобы не используемых <X.label> из файла Skills.xml приведёт к появлению в игре непереведенных строчек типа этой:
![default](https://cloud.githubusercontent.com/assets/229402/18466765/6e8e2dd6-79b6-11e6-9431-c5834eeaefca.png)
Так что всё очень даже используется, спешить не надо.

**Comment by Ohar** [comment]
И их там дофига

**Comment by Dinoabunai** [comment]
```
	<SkillDef>
		<defName>Shooting</defName>
    <description>Use of all kinds of ranged weapons.</description>
    <skillLabel>Shooting</skillLabel>
    <pawnLabel>Shooter</pawnLabel>
  </SkillDef>
```

**Comment by Dinoabunai** [comment]
Но, тем не менее, тесты показали что так оно и есть.

**Comment by Dinoabunai** [comment]
Задал вопрос на форуме: https://ludeon.com/forums/index.php?topic=2933.msg263515#msg263515
Спасибо @dragomano за разведку.

**Comment by Dinoabunai** [comment]
Задание выполнено.
