### ISSUE TITLE
psylink neuroformer

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1095]
Следует согласовать перевод:
Первые варианты: 
Нейроналадчик пси-связи
Нейроусилитель пси-связи
Нейростимулятор пси-связи
Нейроустановщик пси-связи
Нейроформировщик пси-связи

**Comment by Elevator89** [comment]
@kamadz, предложил вариант "нейроформер пси-связи" в реквесте https://github.com/Ludeon/RimWorld-ru/pull/1092

**Comment by Blinnna** [comment]
Мне кажется можно просто Стимулятор/Формирователь пси-связи, т.к. то, что он нейро и так следует из его описания и описания пси-связи. Не могу решить как лучше стимулятор значит, что она уже какая-то была. Формирователь по смыслу лучше, но слово корявое, как и установщик.

**Comment by kamadz** [comment]
Оставьте кальку, потому что это безальтернативная лексика
Нет ничего стыдного в заимствовании-кальке

**Comment by Elevator89** [comment]
Оставили "нейроформер пси-связи".
Я убедился, что он используется везде.
