### ISSUE TITLE
2653 Royalty/DefInjected

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1118]
Автоформатированные файлы:
[2653-Royalty-DefInjected.zip](https://github.com/Ludeon/RimWorld-ru/files/4723305/2653-Royalty-DefInjected.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Просмотреть изменения при помощи diff-инструмента
3. Модифицировать перевод в соответствии этими изменениями

**Comment by kamadz** [comment]
взял
