### ISSUE TITLE
2653 Royalty Titles

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1119]
Автоформатированные файлы:
[2653-Royalty-Empire-Titles.zip](https://github.com/Ludeon/RimWorld-ru/files/4723306/2653-Royalty-Empire-Titles.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Просмотреть изменения при помощи diff-инструмента
3. Модифицировать перевод в соответствии этими изменениями

**Comment by kamadz** [comment]
взял
