### ISSUE TITLE
ThoughtDef-WorkTypeDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#112]
Проверить все изменения текста:
ThoughtDef
TimeAssignmentDef
TradeDialogSorterDef
TraderKindDef
TrainableDef
TraitDef
WeatherDef
WorkGiverDef
WorkTypeDef

Сообщить, если много.

**Comment by Elevator89** [comment]
```
File: /Thoughts_Memory_Misc.xml:
	2 tags only in ../RimWorld-ru/DefInjected/ThoughtDef: 
		WitnessedDeathFamily.stages.0.label
		WitnessedDeathFamily.stages.0.description

File: /Thoughts_Situation_Drugs.xml:
	12 tags only in ../RimWorld-de/DefInjected/ThoughtDef: 
		SmokeleafHigh.description
		FlakeHigh.label
		AlcoholWithdrawal.stages.1.description
		GoJuiceHigh.label
		GoJuiceWithdrawal.stages.1.description
		GoJuiceHigh.description
		YayoHigh.description
		YayoHigh.label
		SmokeleafHigh.label
		GoJuiceWithdrawal.stages.1.label
		AlcoholWithdrawal.stages.1.label
		FlakeHigh.description
	6 tags only in ../RimWorld-ru/DefInjected/ThoughtDef: 
		FlakeHigh.stages.0.label
		YayoHigh.stages.0.description
		SmokeleafHigh.stages.0.description
		SmokeleafHigh.stages.0.label
		YayoHigh.stages.0.label
		FlakeHigh.stages.0.description

File: /WorkGivers.xml:
	15 tags only in ../RimWorld-de/DefInjected/WorkGiverDef: 
		DoBillsProduceDrugs.label
		FillFermentingBarrel.label
		DoBillsProduceDrugs.verb
		Drill.verb
		FillFermentingBarrel.verb
		Drill.gerund
		FillFermentingBarrel.gerund
		TakeBeerOutOfFermentingBarrel.gerund
		Drill.label
		DoBillsProduceDrugs.gerund
		TakeBeerOutOfFermentingBarrel.label
		TakeBeerOutOfFermentingBarrel.verb
		DoBillsHaulCampfire.gerund
		DoBillsHaulCampfire.verb
		DoBillsHaulCampfire.label
```

**Comment by Dinoabunai** [comment]
Принял. Разработаю актуальное задание.

**Comment by Dinoabunai** [comment]
1) **ThoughtDef\Thoughts_Exotic.xml**
Опционально. Поставить тире в последнем предложении **`<PsychicDrone.stages.4.description>`**

**Comment by Dinoabunai** [comment]
Актуальное задание полностью сформировано.

**Comment by Ohar** [comment]
> 3) ThoughtDef\Thoughts_Situation_Social.xml
Объект Affair скорее всего переведен неправильно.

Тут скорее всего подразумевается «крутит роман»/«влюблённость».

**Comment by Dinoabunai** [comment]
> Тут скорее всего подразумевается «крутит роман»/«влюблённость».

Думаю что да. Потестирую.

**Comment by Ohar** [comment]
> В файле много "vs.". Переделать на что-то более приятное.
Раз уж у нас UTF-8, то грех не пользовать юникод. Предлагаю заменить на скрещенные мечи `vs.` → `⚔`.

Было | Стало
------------ | -------------
трудяга vs. ленивец | трудяга ⚔ ленивец
трезвенник vs. алкоголик | трезвенник ⚔ алкоголик
алкоголик vs. трезвенник | алкоголик ⚔ трезвенник

**Comment by Dinoabunai** [comment]
Идея неплоха. Но поймут ли игроки?
В оригинальном файле слово "versus" вообще не стали сокращать.
Там так и есть: "alcoholic versus sober" и т.д.

**Comment by Elevator89** [comment]
"Алкоголик ⚔ трезвенник", "алкоголик против трезвенника" для русского уха звучит как объявление соперников в боях без правил. А в игре это всего лишь дебаф к отношениям. Не обязательно же они будут гаситься.
"Алкоголик и трезвенник" вроде норм. Учитывая контекст появления этой строки, игроки должны понять смысл.

**Comment by Ohar** [comment]
Я вот ещё не понял, почему есть пара `трезвенник vs. алкоголик` и `алкоголик vs. трезвенник`. а вот второго компонента для `трудяга vs. ленивец` нету?

**Comment by Dimonasdf** [comment]
Потому что ленивец болт клал на трудяг. А им выпендриться надо, что они дофига работящие.

**Comment by Elevator89** [comment]
Стоп, какой ещё "ленивец", народ?! Этот, что ли?
http://cs5.pikabu.ru/post_img/2014/10/21/5/1413869522_1973751830.jpg
Или вот этот:
http://sclmodels.ru/foto/russia/t-34-76/46.jpg
Может, всё-таки "лентяй" )?

**Comment by Dinoabunai** [comment]
@Ohar 
> Я вот ещё не понял, почему есть пара трезвенник vs. алкоголик и алкоголик vs. трезвенник. а вот второго компонента для трудяга vs. ленивец нету?

Лентяю пофиг что другие работают :) Только трудяги ненавидят лентяев.

**Comment by Dinoabunai** [comment]
> В оригинальном файле слово "versus" вообще не стали сокращать.

Вру. Там "vs" у них стоит. Но заменить все равно стоит.

**Comment by Dinoabunai** [comment]
Задание сделано. В процессе тестирования.

**Comment by Dinoabunai** [comment]
Протестировано.

**Comment by Dinoabunai** [comment]
Сделано. См. реквест #128

**Comment by Dinoabunai** [comment]
Задание выполнено.
