### ISSUE TITLE
Keyed+Strings

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#113]
Должны быть уже сделаны.
Тут много больших файлов, можно просто пройтись свежим взглядом.
Если будет желание заняться масштабными правками - сообщить о необходимости разбиения Issue.

**Comment by Ohar** [comment]
Это вообще про что?
@Elevator89 Может закрыть?

**Comment by Elevator89** [comment]
Нет, не закрывать. Это про папки Keyed и Strings в репозитории перевода.

**Comment by Ohar** [comment]
А что с ними делать? Все файлы прошерстить или что?

**Comment by Dimonasdf** [comment]
Можно.
Касательно обновления они должны быть up to date, поскольку я их ещё давно сделал, до введения заданий и прочего.

**Comment by Dinoabunai** [comment]
@Elevator89 
@Ohar 
Ненене куда закрывать. Там дофига проверить и что-то поменялось.

**Comment by Elevator89** [comment]
Буду разбивать ишью на более мелкие, иначе невозможно работать

**Comment by Elevator89** [comment]
Разбито на задачи #168, #169, #170, #171, #172, #173, #174, #175 и закрыто.
