### ISSUE TITLE
Унификация названий каменных блоков

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#120]
В данный момент названия каменных блоков [не унифицированы](https://github.com/Ludeon/RimWorld-ru/blob/5ab9c414ee1cb053e85aec2e68b877357090b4d6/DefInjected/ThingDef/Various_Stone.xml).

* блоки песчаника
* гранитные блоки
* блоки известняка
* блоки сланца
* мраморные блоки

То есть 3 из них в формате `блоки КАМНЯ`, а 2 других — `КАМЕННЫЕ блоки`. Это неудобно, т. к. в игре они показываются списком.

Никто не против, если я их унифицирую к виду `блоки КАМНЯ` (так они будут вместе находиться в списке материалов)?

**Comment by Dinoabunai** [comment]
Мне нравится эта идея.

**Comment by Ohar** [comment]
Закрывайте тогда

**Comment by Dinoabunai** [comment]
Закрыто #122
