### ISSUE TITLE
Актуализация ридми

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#121]
Господа, давайте пользоваться ридми по назначению — как _кратким описанием работы с проектом_, а не как _списком переводчиков_.

Предлагаю список перенести в вики, а в ридми писать:

1. Название текущей рабочей ветки и ссылка на неё — [Alfa-15-Clean](https://github.com/Ludeon/RimWorld-ru/tree/Alfa-15-Clean).
2. Номер текущей версии игры (`0.15.1284`), который надо писать в сообщении коммита.
3. Ссылки на вики-статьи.
  1. [Организация командной работы с Гитом](https://github.com/Ludeon/RimWorld-ru/wiki/%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%93%D0%B8%D1%82%D0%BE%D0%BC).
  2. [Форматирование инъекций](https://github.com/Ludeon/RimWorld-ru/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%8A%D0%B5%D0%BA%D1%86%D0%B8%D0%B9). Что вообще за инъекции такие?
  3. [Перевод в новый формат](https://github.com/Ludeon/RimWorld-ru/wiki/%D0%9F%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4-%D0%B2-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82). Почему новый? Для чего? Куда делся старый?

**Comment by Dimonasdf** [comment]
https://github.com/Ludeon/RimWorld-de

**Comment by Dinoabunai** [comment]
> Что вообще за инъекции такие?

Есть 2 вида перевода:
1) Injection - инъекции. Игра заменяет перевод с помощью некого метода в самой программе. Это все то, что хранится в **DefInjected**.
2) Keys - Замена ключа. Это все что лежит в папке **Keyed**.

> Почему новый? Для чего? Куда делся старый

Раньше было актуально. Старый уже не используется. Все файлы (я надеюсь) переведены в новый формат.

**Comment by Ohar** [comment]
@Dimonasdf это к чему? Немцы так делают, значит норм? Так ведь не норм.

**Comment by Dinoabunai** [comment]
> 1. Ага, это неплохо бы расписать попонятнее.

Да.

> 2. Так может и убрать это, раз не используется?

Может и стоит.
