### ISSUE TITLE
PeriodYears

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1227]
Если в файле Keyed/Time.xml написать безобидную строчку:
```
<PeriodYears>{0_numCase ? год : года : лет}</PeriodYears>
```
, это выльется в исключение:
```
Exception from asynchronous event: System.FormatException: Input string was not in a correct format.
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00251] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00023] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.String.Format (System.String format, System.Object arg0) [0x00008] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Verse.ColoredText.ResetStaticData () [0x0001c] in <eb03c2d15d854698949b53c08ba7db97>:0 
  at Verse.PlayDataLoader.DoPlayLoad () [0x00206] in <eb03c2d15d854698949b53c08ba7db97>:0 
  at Verse.PlayDataLoader.LoadAllPlayData (System.Boolean recovering) [0x00093] in <eb03c2d15d854698949b53c08ba7db97>:0 
  at Verse.Root+<>c.<Start>b__6_1 () [0x00000] in <eb03c2d15d854698949b53c08ba7db97>:0 
  at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00008] in <eb03c2d15d854698949b53c08ba7db97>:0  
```
и в кучу NullReferenceException'ов каждый кадр, заспамливая лог
Насколько я могу судить, дело в строчках кода класса Verse.ColoredText:
```
public static void ResetStaticData()
{
    DateTimeRegexes = new Regex[5]
    {
        new Regex("(" + string.Format("PeriodYears".Translate(), "\\d+\\.?\\d*") + "|" + "Period1Year".Translate() + ")"),
        new Regex("(" + string.Format("PeriodQuadrums".Translate(), "\\d+\\.?\\d*") + "|" + "Period1Quadrum".Translate() + ")"),
        new Regex("(" + string.Format("PeriodDays".Translate(), "\\d+\\.?\\d*") + "|" + "Period1Day".Translate() + ")"),
        new Regex("(" + string.Format("PeriodHours".Translate(), "\\d+\\.?\\d*") + "|" + "Period1Hour".Translate() + ")"),
        new Regex("(" + string.Format("PeriodSeconds".Translate(), "\\d+\\.?\\d*") + "|" + "Period1Second".Translate() + ")")
    };
    string str = "(" + FactionDefOf.PlayerColony.pawnsPlural + "|" + FactionDefOf.PlayerColony.pawnSingular + ")";
    ColonistCountRegex = new Regex("\\d+\\.?\\d* " + str);
}
```
Вызов Translate() осуществляется без параметров, строка {0_numCase ? год : года : лет} возвращается без изменения, синтаксис символа перемешивается с синтаксисом регэкспа, и получается нежелательная инъекция.

Надо дождаться исправления этого косяка, и использовать символ numCase как должно.

**Comment by CandyFiend** [comment]
![Screenshot_20210717_104511](https://user-images.githubusercontent.com/16528385/126024586-bfc36bb4-e208-4b03-9b6e-0cf5b58104c9.png)
![Screenshot_20210717_104522](https://user-images.githubusercontent.com/16528385/126024589-c98a7277-dfe7-4ede-91ab-0f8cb827fcc0.png)
На скриншотах чистая игра 1.2 с core и Royalty.

**Comment by KorDum** [comment]
@CandyFiend из-за того, что перевод сдвинулся с места и начал адаптироваться под версию 1.3, превнесшую некоторые изменения в код локализации, самая рабочая версия перевод для 1.2 живет вот в [этом](https://github.com/Ludeon/RimWorld-ru/tree/c30fda235a2027007a55d91d881578b41cd2e151) коммите.

**Comment by CandyFiend** [comment]
> @CandyFiend из-за того, что перевод сдвинулся с места и начал адаптироваться под версию 1.3, превнесшую некоторые изменения в код локализации, самая рабочая версия перевод для 1.2 живет вот в [этом](https://github.com/Ludeon/RimWorld-ru/tree/c30fda235a2027007a55d91d881578b41cd2e151) коммите.

Я был бы очень рад, что она есть, если бы Стим не тянул обновления автоматически...

**Comment by KorDum** [comment]
Так в репозитории же есть инструкция, как установить поверх :)

**Comment by CandyFiend** [comment]
> Так в репозитории же есть инструкция, как установить поверх :)

Скачал архив "Последняя актуальная 1.2 + Royalty: архив", заменил файлы в архивах core royalty, проблема сохраняется. Сравнил файлы Keyed/Enums.xml Keyed/Dates.xml (из RimWorld-ru-mazter.zip и RimWorld/Data/Core/Languages/Russian (Русский) ) с помощью веб-сервиса, пишет отличий нет. Может разработчики что-то сломали в 1.2?

**Comment by Elevator89** [comment]
Добавил в Readme ссылку на локализацию 1.2

**Comment by Elevator89** [comment]
> 
> 
> ![Screenshot_20210717_104511](https://user-images.githubusercontent.com/16528385/126024586-bfc36bb4-e208-4b03-9b6e-0cf5b58104c9.png)
> ![Screenshot_20210717_104522](https://user-images.githubusercontent.com/16528385/126024589-c98a7277-dfe7-4ede-91ab-0f8cb827fcc0.png)
> 
> На скриншотах чистая игра 1.2 с core и Royalty.

Добавил в Readme ссылку на локализацию 1.2

**Comment by kazenosaga** [comment]
По состоянию на сегодня всё ещё всё падает.
То же касается строк про кварталы, дни, часы и секунды в Time.xml.
