### ISSUE TITLE
Тире и неразрывные пробелы

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#123]
Тексты плохо типографированы — дефисы вместо тире, нет неразрывных пробелов и прочие неприятности. Надо поправить.

**Comment by Ohar** [comment]
Проблема в том, что поправив их единожды, потом эти ошибки накопятся вновь. Нужен более системный подход. Подумаю над скриптом.

**Comment by Elevator89** [comment]
Выполнено
