### ISSUE TITLE
"Впечатлительность" помещений

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#124]
Впечатлительным может быть человек, но никак не помещение. Нужно найти и исправить на что-то более подходящее по всему переводу. Только на что?

**Comment by Ohar** [comment]
Не нашёл этого слова нигде, кроме как в [подсказках обучения](https://github.com/Ludeon/RimWorld-ru/blob/0899224f1f9b3382debc63b66ed551ae42967e4c/DefInjected/ConceptDef/Concepts_Noted.xml#L34). Откуда тогда берётся подпись при просмотре информации о комнате?

**Comment by Ohar** [comment]
Варианты
* презентабельность
* богатство

**Comment by Dinoabunai** [comment]
Можно привести контекст и оригинал?

**Comment by Ohar** [comment]
* **Оригинал подсказки**
_You can inspect the impressiveness, wealth, and beauty of individual rooms using the ROOM STATS INSPECT toggle in the bottom right._

* **Оригинал из окна информации о комнате**
_impressiveness_

**Comment by Dinoabunai** [comment]
Можно перевести как "производимое впечатление", "производимое комнатой впечатление".
Так же напомню, что мне понравился вариант @Ohar - "презентабельность"

**Comment by Ohar** [comment]
> "производимое впечатление", "производимое комнатой впечатление"

Длинновато для перевода одного слова

**Comment by Elevator89** [comment]
"Производимое впечатление" - самый точный перевод.
А почему длинновато? Думаешь, не влезет в нужное место?

**Comment by Ohar** [comment]
@Elevator89 Да нет, влезет. Просто длиннее раза в два. Но, с другой стороны, это такая фишка перевода на русский.

**Comment by Elevator89** [comment]
А кто-нибудь может вставить "производимое впечатление" в игру и потестить в боевых условиях?

**Comment by Dinoabunai** [comment]
Я смогу завтра потестить.

**Comment by Ohar** [comment]
@Dinoabunai как там результат?
