### ISSUE TITLE
StyleItemCategoryDefs

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1252]
Узнать, где оно используется и перевести грамотно

**Comment by kamadz** [comment]
Используется в стилях татуировок, причёски и мебели
![image](https://user-images.githubusercontent.com/57110948/126832776-207e7e79-ba86-4290-8a3b-9ffdbcdc5fe0.png)
![image](https://user-images.githubusercontent.com/57110948/126832899-0a2dee4d-f735-496f-8b4c-037460d4febc.png)
![image](https://user-images.githubusercontent.com/57110948/126832931-fc149094-a2d4-4982-b76a-c068813c20cd.png)
![image](https://user-images.githubusercontent.com/57110948/126832976-079677f8-107d-4f20-86c0-44b6395ed986.png)
![image](https://user-images.githubusercontent.com/57110948/126833045-83f15b50-90f9-40a9-82c4-eb0d5055f935.png)


Насколько я понимаю, все эти вещи меняются автоматически в зависимости от настроек идеолигии.

**Comment by kamadz** [comment]
Я кидал статью на реддите про стили построек, ты не читал что ли?

**Comment by kamadz** [comment]
Дополняю, если вдруг не понятно: 
У одежды и оружия тоже есть стили.

**Comment by kazenosaga** [comment]
Не вижу задачи и критериев исполнения
