### ISSUE TITLE
Beer

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#127]
Поправить и дополнить перевод пива.
Перевести **Drugs\Alcohol_Beer.xml**
Изменить Alcohol на Alcoh**o**lHigh в **HediffDef**.

**Comment by EcherArt** [comment]
Перевела Alcochol_Beer, осталось только протестировать.
Можно ли кидать ветку в пул реквест через Git GUI? На превью последний неадекватно отображает кодировку, хотя файл закодирован в UTF-8. Использовала Notepad ++.

**Comment by Dinoabunai** [comment]
@EcherArt 
Не надо делать это задание :) Оно уже было назначено на меня.
По всем интересующим вопросам можем проконсультировать в местном подобии чата: https://github.com/Ludeon/RimWorld-ru/issues/23

Но лучше спрашивать в телеграме:
https://telegram.me/joinchat/EBLEqgn9X2kXe_oDrrAMsA

**Comment by Dinoabunai** [comment]
@EcherArt 
Я пока тебя снимаю с этого задания.
Когда будешь брать новое задание - убедись, что оно уже ни на кого не назначено.

**Comment by EcherArt** [comment]
Ок, спасибо что просветили =)

**Comment by Elevator89** [comment]
Задание пересекается с #101.

**Comment by Elevator89** [comment]
Сделано в #101. Закрываю.
