### ISSUE TITLE
Ideology/DefInjected/PreceptDef, part 1

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1281]
Автоформатированные файлы:
[Ideology-DefInjected 7 PreceptDef 1.zip](https://github.com/Ludeon/RimWorld-ru/files/6904061/Ideology-DefInjected.7.PreceptDef.1.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by dutlist** [comment]
Взял
