### ISSUE TITLE
Ideology/DefInjected/PreceptDef, part 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1282]
Автоформатированные файлы:
[Ideology-DefInjected 7 PreceptDef 2.zip](https://github.com/Ludeon/RimWorld-ru/files/6904063/Ideology-DefInjected.7.PreceptDef.2.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by dutlist** [comment]
Взял
