### ISSUE TITLE
Ideology/DefInjected/ThingDef, part 1

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1288]
Автоформатированные файлы:
[Ideology-DefInjected 13 ThingDef 1.zip](https://github.com/Ludeon/RimWorld-ru/files/6904076/Ideology-DefInjected.13.ThingDef.1.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by EtoZheJih** [comment]
Взял
