### ISSUE TITLE
Ideology/DefInjected/ThingDef, part 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1289]
Автоформатированные файлы:
[Ideology-DefInjected 13 ThingDef 2.zip](https://github.com/Ludeon/RimWorld-ru/files/6904077/Ideology-DefInjected.13.ThingDef.2.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by EtoZheJih** [comment]
Взял
