### ISSUE TITLE
Gerund in WorkGiverDef\WorkGivers.xml

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#129]
**Russian\DefInjected\WorkGiverDef\WorkGivers.xml**
Герундии переведены на русский отлично от прочих языков.
В английском использован оборот:
**Prioritize (somethitng)**
Например - "**Prioritize cutting oak**"

В русском просто:
"**Срубить: дуб**"

В **Russian\Keyed\FloatMenu.xml** так и сказано в комментарии:
```
  <!-- e.g. Prioritize GERUND OBJECT, Prioritize repairing wall, prioritize hauling metal, etc-->
  <PrioritizeGeneric>{0}: {1}</PrioritizeGeneric>
  <!-- В русском это убрано и в gerund идёт просто "Починить" стену, "Отнести" металл... -->
```

**Comment by Dinoabunai** [comment]
Стоит рассмотреть - оставить все как есть или переделать ближе к оригиналу?

**Comment by Dinoabunai** [comment]
Я думаю что опустить слово "приоритезировать" и использовать герундии нестандартным образом - не самая плохая идея.

**Comment by Elevator89** [comment]
Вот как. Оказывается, не всё так просто, как я изначально думал, с этим герундием. Идею с нестандартным использованием поддерживаю, пока не будет найдено контрпримеров.

**Comment by Dinoabunai** [comment]
@Elevator89 
Поддерживаю. Думаю если завтра никто не будет сильно против - Issue можно закрыть.

**Comment by Elevator89** [comment]
...а описанный способ вынести в вики, создав страничку для подобных соглашений

**Comment by Elevator89** [comment]
Добавил на вики [страницу](https://github.com/Ludeon/RimWorld-ru/wiki/%D0%A1%D0%BE%D0%B3%D0%BB%D0%B0%D1%88%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BE-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D0%B5).

**Comment by Ohar** [comment]
@Elevator89 @Dinoabunai  Закрываем?

**Comment by Dinoabunai** [comment]
Думаю стоит закрыть.

**Comment by Elevator89** [comment]
Закрываю
