### ISSUE TITLE
Russian Names for Skills

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#130]
**Russian\DefInjected\WorkTypeDef\WorkTypes.xml**
Рассмотреть и согласовать перевод навыков.
Например "**Plant cutting**" переведено на русский как "**Садоводство**"
Так же возможно стоит согласовать **`<Skill.gerundLabel>`** с прочими строками.

**Comment by LatKrostov** [comment]
Еще актуально? Мог бы заняться.

**Comment by Elevator89** [comment]
Уже неактуально
