### ISSUE TITLE
Update Defs\ThingsDef_Building

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#131]
Проверить и дополнить перевод всех файлов из директории **Defs\ThingsDef_Building**.
Является частью задания #111.

**Comment by Dinoabunai** [comment]
Актуальное задание (не сфориировано полностью):

1) **ThingDef/Buildings_Exotic.xml**
Исправить перевод **CrashedPoisonShipPart**.

2) **ThingDef/Buildings_Furniture.xml**
Исправить перевод **SleepingSpot**.
Добавить перевод объекта **SunLamp**.

Опционально. Можно изменить перевод объекта **Stool** на "**табуретка**", а перевод объекта **DiningChair** на "**стул**" или "**обеденный стул**". 

3) **ThingDef/Buildings_Joy.xml**
Перевод для объектов HorseshoesPin и ChessTable не согласуется с оригиналом. Исправить.

**Comment by Dinoabunai** [comment]
```
File: /Buildings_Furniture.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        SunLamp.label
        SunLamp.description
File: /Buildings_Misc.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        GroundPenetratingScanner.description
        GroundPenetratingScanner.label
    5 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        SunLamp.label
        AncientCryptosleepCasket.label
        FirefoamPopper.comps.1.useLabel
        AncientCryptosleepCasket.description
        SunLamp.description
File: /Buildings_Security.xml:
    3 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        Gun_TurretImprovised.label
        Bullet_TurretImprovised.label
        Gun_TurretImprovised.description
    2 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        TurretGun.description
        TurretGun.label
File: /Buildings_Temperature.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        PassiveCooler.description
        PassiveCooler.labelFile: /Buildings_Furniture.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        SunLamp.label
        SunLamp.description
File: /Buildings_Misc.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        GroundPenetratingScanner.description
        GroundPenetratingScanner.label
    5 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        SunLamp.label
        AncientCryptosleepCasket.label
        FirefoamPopper.comps.1.useLabel
        AncientCryptosleepCasket.description
        SunLamp.description
File: /Buildings_Security.xml:
    3 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        Gun_TurretImprovised.label
        Bullet_TurretImprovised.label
        Gun_TurretImprovised.description
    2 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        TurretGun.description
        TurretGun.label
File: /Buildings_Temperature.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        PassiveCooler.description
        PassiveCooler.label
```

**Comment by Dinoabunai** [comment]
Актуальное задание (не сфориировано полностью):

1) **ThingDef/Buildings_Exotic.xml**
Исправить перевод **CrashedPoisonShipPart**.

2) **ThingDef/Buildings_Furniture.xml**
Исправить перевод **SleepingSpot**.
Выяснить, где должна находиться **SunLamp**.

Опционально. Можно изменить перевод объекта **Stool** на "**табуретка**", а перевод объекта **DiningChair** на "**стул**" или "**обеденный стул**". 

3) **ThingDef/Buildings_Joy.xml**
Перевод для объектов **HorseshoesPin** и **ChessTable** не согласуется с оригиналом. Исправить.

**Comment by Dinoabunai** [comment]
Актуальное задание полностью сформировано.

**Comment by Dinoabunai** [comment]
@Elevator89 

> Опционально. Можно изменить перевод объекта Stool на "табуретка", а перевод объекта DiningChair на "стул" или "обеденный стул".

Что скажешь? "Stool" он и выглядит как табуретка, так же табуретка переводится как "Stool". А если бы это был обычный "стул", то он по-английски так бы и назывался "chair". Так что я думаю там явно о табуретке шла речь. И так - "табуретка", "табурет" или оставим "стул"?

 Так же как назовем DinnerChair в таком случае - "обеденный стул" или просто "стул"? В английском указывается что это именно "DINNER chair", потому что у них и компьютерное кресло тоже будет "chair". Т.е. служит для обозначения классического стула с ножками. Но можно оставить и "обеденный" вариант. Но мне кажется, будет лучше просто "стул".

**Comment by Elevator89** [comment]
"Stool" пусть будет табуреткой. 
А вот "dinner chair" я бы перевёл как просто "стул". "Табуретка" и "стул", на мой взгляд в меню рядом будут органичнее смотреться, чем "Табуретка" и "обеденный стул".
Есть, кстати, ещё и [office chair](http://www.ikea.com/us/en/catalog/categories/departments/workspaces/20652/). Если его введут в игру, мы сможем его перевести как "офисное кресло".
Вышеописанное, на мой взгляд, вполне соответствует бытовому опыту русскоязычных игроков, и в переводе будет хорошо смотреться.

**Comment by Dinoabunai** [comment]
Добро.
