### ISSUE TITLE
Update Defs\ThingDefs_Items

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#132]
Проверить и дополнить перевод всех файлов из директории **Defs\ThingsDef_Items**.
Является частью задания #111.

**Comment by Dinoabunai** [comment]
```
File: /Items_Artifacts.xml:
    4 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        PsychicInsanityLance.comps.1.useLabel
        PsychicAnimalPulser.comps.1.useLabel
        PsychicShockLance.comps.1.useLabel
        PsychicSoothePulser.comps.1.useLabel
File: /Items_Drugs.xml:
    6 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        GoJuice.description
        Wort.label
        Beer.label
        GoJuice.label
        Wort.description
        Beer.description
    12 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        Flake.ingestible.ingestCommandString
        Flake.ingestible.ingestReportString
        SmokeleafJoint.ingestible.ingestReportString
        WakeUp.ingestible.ingestReportString
        Luciferium.ingestible.ingestReportString
        Yayo.ingestible.ingestReportString
        SmokeleafJoint.ingestible.ingestCommandString
        Luciferium.ingestible.ingestCommandString
        WakeUp.ingestible.ingestCommandString
        MalariBlock.ingestible.ingestReportString
        MalariBlock.ingestible.ingestCommandString
        Yayo.ingestible.ingestCommandString
File: /Items_Exotic.xml:
    1 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        Neurotrainer.comps.1.useLabel
File: /Items_Luxury.xml:
    2 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        Beer.description
        Beer.label
File: /Items_Resource_Manufactured.xml:
    2 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        Neutroamine.label
        Neutroamine.description
File: /Items_Resource_RawPlant.xml:
    4 tags only in ../RimWorld-de/DefInjected/ThingDef: 
        SmokeleafLeaves.description
        PsychoidLeaves.description
        SmokeleafLeaves.label
        PsychoidLeaves.label
File: /Items_Resource_Stuff.xml:
    1 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        Plasteel.stuffProps.stuffAdjective
```

**Comment by Dinoabunai** [comment]
Актуальное задание:

1) **Thing Def\Items_Food.xml**
Исправить перевод объекта **MealSurvivalPack**.
**Опционально**: Исправить перевод объекта **Pemmican**.

2) **Thing Def\Items_Luxury.xml**
Исправить перевод объекта **Chocolate**.

3) **Thing Def\Items_Resource_AnimalProduct.xml**
Исправить перевод объекта **Milk**.
Опечатка в слове "**Неоплодотворённое**" объекта **EggChickenUnfertilized**.

4) **Thing Def\Items_Resource_Manufactured.xml**
Добавить перевод объекта Neutroamine.

5) **Thing Def\Items_Resource_RawPlant.xml**
Привести структуру файла к структуре оригинала.

Добавить перевод объектов **PsychoidLeaves** и **SmokeleafLeaves**.

**Опционально**: Исправить перевод объекта **RawCorn**.
В оригинале: "Raw corn." Переведено как "Сырая кукуруза. Приятно есть даже в сыром виде."
Второе предложение осталось, по всей видимости от копипаста перевода RawBerries: "Assorted berries. Nice to eat, even when raw."

**Comment by Dinoabunai** [comment]
@Elevator89 

> Опционально: Исправить перевод объекта Pemmican.

Сейчас пеммикан переведен как "вяленое мясо". Но пеммикан, - он как бы и в Африке [пеммикан](https://ru.wikipedia.org/wiki/%D0%9F%D0%B5%D0%BC%D0%BC%D0%B8%D0%BA%D0%B0%D0%BD).
 С другой стороны пеммикан - это вяленое мясо...
Как оставим?

> Опционально: Исправить перевод объекта RawCorn.
В оригинале: "Raw corn." Переведено как "Сырая кукуруза. Приятно есть даже в сыром виде." Второе предложение осталось, по всей видимости от копипаста перевода RawBerries: "Assorted berries. Nice to eat, even when raw."

Мне кажется тут явный прогляд и надо исправить.

**Comment by Dinoabunai** [comment]
Кому дорога судьба Psychoid - милости просим: https://github.com/Ludeon/RimWorld-ru/issues/138

**Comment by Dinoabunai** [comment]
Сделал все кроме Pammican, RawCorn и PsychoidLeaves. Так что как только вопросы разрешатся - доделаю и запушу.

**Comment by Elevator89** [comment]
С вяленым мясом-пеммиканом логично поступить так же, как с раком-карциномой, а именно, выбираем самый частный и точный вариант.
То есть пеммикан.

**Comment by Elevator89** [comment]
> В оригинале: "Raw corn." Переведено как "Сырая кукуруза. Приятно есть даже в сыром виде." Второе предложение осталось, по всей видимости от копипаста перевода RawBerries: "Assorted berries. Nice to eat, even when raw."

Это явный прогляд и надо исправить.

**Comment by Ohar** [comment]
> Сейчас пеммикан переведен как "вяленое мясо". Но пеммикан, - он как бы и в Африке пеммикан.
С другой стороны пеммикан - это по сути вяленое мясо...
Как оставим?

>С вяленым мясом-пеммиканом логично поступить так же, как с раком-карциномой, а именно выбрать самый частный и точный вариант.
То есть пеммикан.

Термин всегда лучше, поскольку точнее.

**Comment by Elevator89** [comment]
На забываем про "психолистья" психолиста из #134
