### ISSUE TITLE
Update Defs\ThingsDef_Races

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#135]
Проверить и дополнить перевод всех файлов из директории **Defs\ThingsDef_Races**.
Является частью задания #111.

**Comment by Dinoabunai** [comment]
```
File: /Races_Animal_Birds.xml:
    2 tags only in ../RimWorld-ru/DefInjected/ThingDef: 
        Turkey_Meat.description
        Turkey_Meat.label
```

**Comment by Ohar** [comment]
# Пещерный жук #

В настоящий момент _Spelopede_ переведено как _пещерный жук_. Предлагаю заменить на _пещерник_, так как _spelo_ (греч.) — пещера, а окончание _ped_ в английском примерно обозначает _ноги_, т. е. буквальный перевод — _пещероход_, _пещеролаз_, _пещероног_.

**Comment by Ohar** [comment]
Готово, проверяйте
