### ISSUE TITLE
Стилистические правки описания фракций

### ISSUE THREAD

**Issue by maxqwerty** [Ludeon/RimWorld-ru#1374]
- [ ] Описание фракции **Раздробленная империя**
Royalty\DefInjected\FactionDef\Faction_Empire.xml

![image](https://user-images.githubusercontent.com/4933297/157525875-75284fbc-6c04-4b83-b88c-291a12b67baa.png)

Предлагаю заменить на 
`Они пережили катастрофу, расколовшую софийское общество`

- [ ] Описание фракции **Рой механоидов**
Core\DefInjected\FactionDef\Factions_Hidden.xml
**Mechanoid.description**

![image](https://user-images.githubusercontent.com/4933297/157526353-dc03ffc5-c757-4972-9a97-ac00c55c8d42.png)

Предлагаю убрать "же" и заменить на 
`А в легендах диких племён...`

- [ ] Фракция **Насекомые**
Core\DefInjected\FactionDef\Factions_Hidden.xml
**Insect.description**

заменить описание на 
`Гигантские насекомоподобные существа, живущие под землёй, но выходящие на поверхность привлекаемые шумом или феромонами. Межзвёздным предпринимателям удалось поймать их на родной планете Сорн, генетически модифицировать и взрастить несколько колоний, чтобы использовать в качестве оружия. Неясно, кто привёз на эту планету насекомых Сорна, но точно известно, что они здесь есть и они опасны как никогда.`

- [ ] Описание племенных фракций
Core\DefInjected\FactionDef\Factions_Misc.xml
**TribeCivil.description**
**TribeRough.description**
**TribeSavage.description**

Ideology\DefInjected\FactionDef\Factions_Misc.xml
**NudistTribe.description**
**TribeCannibal.description**

Фразу
`В любом случае`
заменить на
`Во всяком случае`

- [ ]  Фракции **Пиратов**
Core\DefInjected\FactionDef\Factions_Misc.xml
- Pirate.description
Ideology\DefInjected\FactionDef\Factions_Misc.xml
- CannibalPirate.description

`Их культура основана на понятиях «крови и чести», а такие качества, как сила и беспощадность, у них в большом почёте.\n\nПираты обогащаются за счёт более успешных групп в регионе, и их уровень технологий зависит, по большей части, от тех, кого им недавно удалось ограбить.`
заменить на более приближённый к оригиналу вариант
`Ведомые принципами «крови и чести», которые ценят такие качества, как сила и беспощадность, они обогащаются за счёт набегов и грабежей своих более продуктивных соседей.\n\nИх технологический уровень зависит, по большей части, от тех, кого им удалось недавно ограбить.`

**Comment by Elevator89** [comment]
Согласился почти со всеми предложениями
