### ISSUE TITLE
Термин "близость" в контексте негативного отношения

### ISSUE THREAD

**Issue by BlitDev** [Ludeon/RimWorld-ru#1377]
Слово **близость** имеет скорее **позитивный окрас** и в случае **негативного отношения** не подходит.
Нужно заменить его на что-то более подходящее.

**Comment by kamadz** [comment]
У нас появились изнасилования?

**Comment by BlitDev** [comment]
> У нас появились изнасилования?

По идее, в игре такого нет. Чисто есть обобщение "физическая близость", и всё.
