### ISSUE TITLE
Обсуждение перевода Psychoid

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#138]
Как переведем слово "psychoid" (это растение из которого получают наркотическое вещество - психин (ранее это был кокаин)).
Я не против так и перевести "психоид". Хотя может показаться, что это какой-то очень нервный человек.

**Comment by Ohar** [comment]
В русском есть уже термин [_психоид_](http://analiticheskaya_psichologiya.academic.ru/188/%D0%9F%D0%A1%D0%98%D0%A5%D0%9E%D0%98%D0%94) — это психологический термин, обозначающий инстинктивную модель поведения. Вроде как называть так растение не очень разумно. С другой стороны, это калька с заимствованного оригинала _psychoid_ — в основе греческий корень, но я не понял, из какого языка само слово. Если английский (что вероятно), то можно (как поступили разработчики) взять уже существующее слово _психоид_ и не париться. Если не английский — надо смотреть особенности заимствования слов из этого языка.

**Comment by Dinoabunai** [comment]
Я думаю они просто обкатали английское слово "psycho". Само слово "писхо" по латыни означает "душа".

**Comment by Ohar** [comment]
1. Слово Психо (Ψυχή) не латинское, а греческое.
2. Гадать на кофейной гуще, что там кто-то имел в виду — дело малоосмысленное, так можно очень далеко зайти. Лучше исходить из того, что слово взято не просто так.

**Comment by Dimonasdf** [comment]
А что с `психит`ом стало?

**Comment by Dinoabunai** [comment]
@Ohar 
> Слово Психо (Ψυχή) не латинское, а греческое.

Пардон.

@Dimonasdf 
> А что с психитом стало?

Ты его забраковал:
https://github.com/Ludeon/RimWorld-ru/pull/82#issuecomment-245392020

**Comment by Ohar** [comment]
В общем, в [коммите](https://github.com/Ludeon/RimWorld-ru/pull/125/files#diff-fbc7619f5cf9eb65699fb67a606cfd7bR37) щас перевод _psychoid plant_ → _психо-трава_, но обсуждение ещё открыто.

**Comment by Ohar** [comment]
Решили перевести как _психолист_, т. к. на спрайтах видны ветки, т. е. это не трава

**Comment by Ohar** [comment]
Закрываем?

**Comment by Elevator89** [comment]
Да
