### ISSUE TITLE
Лишняя переменная в Script_ReliquaryPilgrims.xml?

### ISSUE THREAD

**Issue by Janitor53** [Ludeon/RimWorld-ru#1386]
В английской версии используется переменная hasHave:
    <li>hasHave(pilgrimCount==1)->has</li>
    <li>hasHave(pilgrimCount>=2)->have</li>
В русской версии она не нужна, но в файле она осталась в 25й строке. Из-за этого квест выбрасывает ошибку в момент когда пилигрим уходит с карты:
Grammar unresolvable. Root 'root'

GRAMMAR RESOLUTION TRACE
    root → [pilgrimsLeftMessage]
      pilgrimsLeftMessage → [pilgrimsLabelSingularOrPlural] [hasHave] left the map.
        pilgrimsLabelSingularOrPlural → [pilgrimsLabel]
          pilgrimsLabel → [pawns0_nameDef]
            pawns0_nameDef → <color=#D09B61FF>Gild</color>
         hasHave → UNRESOLVABLE
       pilgrimsLeftMessage → UNRESOLVABLE
     root → UNRESOLVABLE

**Comment by Elevator89** [comment]
Спасибо. Исправил.
