### ISSUE TITLE
Исправить перевод модификатора запугивания на носящего шмотку

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1387]
Нужны правки для ошейника и шлейки
![IMG_20220602_194056_880](https://user-images.githubusercontent.com/57110948/171681249-65e257b7-5cfb-4739-a7f5-98d1d3fcbe12.jpg)
![IMG_20220602_194052_920](https://user-images.githubusercontent.com/57110948/171681258-d03d94cc-4ad5-4daf-9dd5-fab1a1b23012.jpg)

**Comment by BlitDev** [comment]
Тут разве что **продолжительный эффект** можно заменить на **значительный эффект**, если это влияет именно на более низкий шанс восстания раба после подавления.
Но даже без этого, смысл вполне нормально передаётся, со стороны игрока **более значительный эффект** означает именно **менее частые восстания**.

**Comment by BlitDev** [comment]
Ошейник носят рабы, а **не те, кто их запугивают**. А в переводе подразумевается именно **это**.
