### ISSUE TITLE
Заключённый, пленник или узник?

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#139]
Сейчас во всём переводе используется слово _заключённый_, что немного некорректно, 
* _Заключённый_
Это человек, который сидит в тюрьме за преступление. Это больше юридический термин.
* _Пленник_
Это человек, захваченный во время боевых действий.
* _Узник_
Это абстрактный человек за решёткой, без обозначения причин.

Мне кажется, что в RimWorld, где в тюрьму можно посадить кого угодно и когда угодно, слово _узник_ подходит больше, чем _заключённый_.

**Comment by Dinoabunai** [comment]
Пленник мог бы быть, если в игре использовалось слово "**captive**", но использовано слово "**prisoner**". Хотя "**заключенный**" и немного юридический термин, слово "**узник**" лично мне режет слух, т.к. практически не употребляется в современной речи. Плюс в игре для того чтобы содержать данных лиц, требуется организовать специальное здание, которое, кстати в игре называется "**prison cell**", т.е. "**тюремная камера**".

**Comment by EcherArt** [comment]
Ну, а где еще содержат узников, как не в prison cell?
Лично мне это слово ухо не режет, но я прекрасно понимаю, что не все играющие в Rimworld - шизанутые гуманитарии.

**Comment by Ohar** [comment]
@Dinoabunai 

>Хотя "заключенный" и немного юридический термин, слово "узник" лично мне режет слух, т.к. практически не употребляется в современной речи.

Ты путаешь причину со следствием. Это как раз и связано с тем, что в современном мире сажают в тюрьму за преступления, поэтому все люди за решёткой — заключённые. В RimWorld это не так.

> Плюс в игре для того чтобы содержать данных лиц, требуется организовать специальную комнату, которая, кстати в игре называется "prison cell", т.е. "тюремная камера".

Видимо, ты тут подразумеваешь какой-либо значимый ввывод, нол я его не вижу. Это вообще к вопросу не имеет отношения.

**Comment by Dimonasdf** [comment]
Не вижу смысла отказываться от текущей пестроты терминов)

**Comment by Ohar** [comment]
Какой ещё пестроты?

**Comment by Dimonasdf** [comment]
Где-то заключённый, где-то пленник, где-то узник. Пусть везде будет по смыслу контекста, а не притянуто. Мм?

**Comment by Ohar** [comment]
Именно поэтому я и предлагаю везде поставить _узник_, как самое универсальное и подходящее для реальности RimWorld.

**Comment by Dimonasdf** [comment]
Как хотите. Я не против узника.

**Comment by Ohar** [comment]
@EcherArt @Dinoabunai @Elevator89 Господа?

**Comment by EcherArt** [comment]
Я за "узника".

**Comment by Dinoabunai** [comment]
Я склоняюсь к "заключённому".

**Comment by Elevator89** [comment]
Я не вижу принципиальной разницы. Лучше действительно применять и то, и другое, и третье исходя из контекста. Например "пленника" будем использовать, если речь идёт про захваченного налётчика. Остальные варианты - по обстановке. Игроки поймут о чём речь.

**Comment by Dinoabunai** [comment]
А там точно не 1 слово во всех случаях будет использоваться?

**Comment by Elevator89** [comment]
Как сделаем, так и будет использоваться.
Узник - заключенный - синонимы. Пленник - это тот узник, который стал таковым, будучи в бою захваченным в плен.
Не вижу причин делать везде одно и тоже слово. Пусть перевод будет чуть более богатым. Давайте разумно применять синонимы.
Ишью предлагается к закрытию.
