### ISSUE TITLE
Не пора ли начать переводить новое DLC?

### ISSUE THREAD

**Issue by MarisKori** [Ludeon/RimWorld-ru#1395]
Оно уже пару дней доступно в бета-ветке в Стиме.

**Comment by Elevator89** [comment]
В первую очередь будем переводить Core. 
DLC - когда оно у меня будет ).

**Comment by shikulja** [comment]
@Elevator89 не забудьте ветку 1.3 заморозить и в ридми ссылки добавить. 
Спасибо вам.

**Comment by RavenWWalker** [comment]
@MarisKori, @Elevator89, @shikulja, приветствую.
Я бы хотел присоединиться к вашей команде перевода, но пока мало что понимаю.
Есть ли у кого-нибудь из вас возможность связаться со мной и объяснить, что к чему? Очень хочется внести свой вклад в эту замечательную игру.
Глянул файлы переводов на GitHub. Не сказать, что понял всё, но, вроде как, уложил в своей голове основу.
