### ISSUE TITLE
Backstories: Special.xml

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1397]
Перевести биографии в файле Core\DefInjected\BackstoryDef\Special.xml
[BackstoryDef-Special.zip](https://github.com/Ludeon/RimWorld-ru/files/9838457/BackstoryDef-Special.zip)

**Comment by maxqwerty** [comment]
Взял

**Comment by EcherArt** [comment]
давай тогда разделим напополам, если вместе будем работать, я беру нижние до Newborn79.baseDesc, а ты верхние (я своё сегодня залью)

**Comment by maxqwerty** [comment]
Готова первая половина 
https://github.com/Ludeon/RimWorld-ru/pull/1410

**Comment by EcherArt** [comment]
Можно закрывать
