### ISSUE TITLE
Animal Bond

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#140]
В игре для обозначения английского слова "**bond**" в отношении между человеком и животным сейчас используется слово "**связь**". После коллективного совещания решили поменять на "**привязанность**".

Необходимо найти тексты, где используется слово "**связь**" в этом отношении и заменить его на слово "**привязанность**". Особенно важно заменить его на основной вкладке животного.

**Comment by Ohar** [comment]
Взял

**Comment by Dinoabunai** [comment]
Ура!!!
