### ISSUE TITLE
Backstories: part 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1400]
Автоформатированные файлы:
[Backstories2.zip](https://github.com/Ludeon/RimWorld-ru/files/9842816/Backstories2.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести весь английский текст в XML-элементах

**Comment by RavenWWalker** [comment]
Забираю.
