### ISSUE TITLE
DefInjected: Biotech desciption and genes

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1401]
Автоформатированные файлы:
[Biotech-elements.zip](https://github.com/Ludeon/RimWorld-ru/files/9842847/Biotech-elements.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by kamadz** [comment]
забрал
