### ISSUE TITLE
DefInjected: misc

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1403]
Автоформатированные файлы:
[DefInjected1.zip](https://github.com/Ludeon/RimWorld-ru/files/9842934/DefInjected1.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»
3. Обратить внимание не Mech_CentipedeBlaster. Оригинальный текст изменился

**Comment by kamadz** [comment]
забрал
