### ISSUE TITLE
DefInjected: Stats

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1404]
Автоформатированные файлы:
[DefInjected-Stats.zip](https://github.com/Ludeon/RimWorld-ru/files/9842965/DefInjected-Stats.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by maxqwerty** [comment]
забрал

**Comment by maxqwerty** [comment]
https://github.com/Ludeon/RimWorld-ru/pull/1409
