### ISSUE TITLE
DefInjected: ThingDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1405]
Автоформатированные файлы:
[DefInjected-ThingDef.zip](https://github.com/Ludeon/RimWorld-ru/files/9842974/DefInjected-ThingDef.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

Внимание на Corpse_Mech_CentipedeBlaster и Shelf.description: оригинал изменился

**Comment by gugr** [comment]
Взял

**Comment by gugr** [comment]
https://github.com/Ludeon/RimWorld-ru/pull/1408
