### ISSUE TITLE
DefInjected: misc 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1406]
Автоформатированные файлы:
[DefInjected2.zip](https://github.com/Ludeon/RimWorld-ru/files/9842992/DefInjected2.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все «TODO»

**Comment by gugr** [comment]
Взял: https://github.com/Ludeon/RimWorld-ru/pull/1407
