### ISSUE TITLE
Growing vat - вариант перевода

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1414]
Временный: резервуар для выращивания
Предложенные: искусственная матка/утроба, инкубатор, репликатор, капсула (???), чан для выращивания

**Comment by Alpenglow305** [comment]
Камера роста — это климатическая камера, которая моделируют и поддерживают климатические параметры, такие как температура, влажность, освещенность, для создания оптимальных условий при выращивании и культивировании растений и **других организмов**.

**Comment by EcherArt** [comment]
я за 1-е 2

**Comment by Alpenglow305** [comment]
Мне инкубатор больше нравится. Ну и моя версия, как вариант.

**Comment by Elevator89** [comment]
Инкубатор - самый лаконичный и точный вариант, по-моему

**Comment by EcherArt** [comment]
Принято

**Comment by EcherArt** [comment]
Закрываем?

**Comment by kamadz** [comment]
Закрываем - принятный вариант: инкубатор
