### ISSUE TITLE
Описание мода попердолилось

### ISSUE THREAD

**Issue by DartVeDroid** [Ludeon/RimWorld-ru#1415]
Строго говоря, я не знаю, в чём причина: в переводах вообще или в моде в частности. Если в моде - могу туда постучаться.
![изображение](https://user-images.githubusercontent.com/32579866/197353554-a32947e6-ccea-4cee-9ef0-17ab45384d32.png)

**Comment by DartVeDroid** [comment]
Есть два дополнения:
1. Русский Keyed-файл мода от английского отличается, в основном, несколькими недостающими записями, в целом же XML валиден.
2. Файлы KeyBindings и KeyBindingCategories мода тоже валидны.

**Comment by Elevator89** [comment]
Это косяк разрабов самого Римворлда. В локализации игры и мода на это повлиять нельзя

**Comment by DartVeDroid** [comment]
Даже если в других модах всё норм?

**Comment by Elevator89** [comment]
Всё так. Там какой-то хитрый метод, которых занимается выделением цветом. Скорее всего с багом

**Comment by DartVeDroid** [comment]
Тогда имеет смысл закрыть обращение.
