### ISSUE TITLE
Lung rot/stink - перевод связанных терминов

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1417]
Временные: 
lung rot - пнемония
rot stink exposure - поражение лёгких
rot stink gas - гнилогаз

**Comment by gugr** [comment]
Предлагаю для lung rot использовать термин "абсцесс легкого", подходит по описанию
https://ru.wikipedia.org/wiki/%D0%90%D0%B1%D1%81%D1%86%D0%B5%D1%81%D1%81_%D0%BB%D1%91%D0%B3%D0%BA%D0%BE%D0%B3%D0%BE

**Comment by kamadz** [comment]
![image](https://user-images.githubusercontent.com/57110948/197412225-9348d789-de91-439c-9219-88589735c6bc.png)

**Comment by kamadz** [comment]
пульмолютит

**Comment by kamadz** [comment]
Пульмоситоз

**Comment by kamadz** [comment]
Вариант "пульмолютит" всех устраивает? @EcherArt @Elevator89

**Comment by EcherArt** [comment]
*пишу много букв*

**Comment by EcherArt** [comment]
Гнилогаз звучит хорошо, у меня есть идея по "пульмолютиту": если лёгкие гниют, соответственно, есть некроз тканей -» пульмонекроз

**Comment by EcherArt** [comment]
Гнилогаз звучит очень понятно, мне нравится

**Comment by RavenWWalker** [comment]
lung rot - гнилорот
rot stink gas - гнилогаз, как предложил @kamadz
rot stink exposure - гнилотопь

**Comment by kamadz** [comment]
> если лёгкие гниют, соответственно, есть некроз тканей -» пульмонекроз

Лёгкие не гниют, нигде упоминания гнилостных процессов нет. Название lung rot - разговорное, rot используется (скорее всего) для обозначения самого процесса разрушения/поражения лёгких, а не гнилостных процессов. 

>окончание -лютит тоже норм, но я ещё не видела, чтобы она применялась (пульмонит, плеврит, гинингвит и другие страшные слова знаю). возможно, она действительно где-то используется


И не должна была, это выдуманное название для выдуманной болезни

>почему я к этому придираюсь: поражением лёгких Яндекс считает пневмонию (пример запроса https://www.yandex.ru/search/touch/?text=%D0%BF%D0%BE%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5+%D0%BB%D0%B5%D0%B3%D0%BA%D0%B8%D1%85&lr=213)
а у нас тут указание только на то, что гнилогазом надышались
https://en.m.wikipedia.org/wiki/Inhalation_exposure

Поражение лёгких – состояние, при которых какая-то часть лёгких не участвует в газообмене. Оно может быть вызвано приличным количеством заболеваний: https://pateroclinic.ru/pulmonologia/szst.
Фактически, никаких последствий для дыхания этот хедифф не имеет. С какой-то стороны может показаться, что тут допущена логическая ошибка.
Однако:
>поражение гнилогазом (нейтрально, если дебафф может быть разным); гнилогазовая пневмония (если дебафф всегда сильный); гнилогазовая интоксикация/отравление (как угарным газом);

использовать также нелогично, потому что: а) не развивается пневмония б) нет интоксикации

Биомеханика у процесса, как я понимаю, такая: в лёгких накапливается определённое количество отравляющих веществ, которые после достижения критической массы начинают разрушать слизистую оболочку лёгких, давая тем самым развиться бактериальной инфекции (пульмолютиту

**Comment by RavenWWalker** [comment]
> а почему рот и топь?

Топь - потому что в итоге гнилая жидкость внутри лёгких, как я понял, скапливается и убивает человека, т.е. он задыхается.
А рот - ну, "гнилолёгкие" и "гнилобронхи" не очень звучат, а гнилорот звучит концептуально так, будто у человека гниение внутри, отчего у него неприятно пахнет изо рта.
Просто варианты накидываю х)

**Comment by EcherArt** [comment]
Понятно, спасибо за разъяснения. Тогда "lung rot - пневмония" точно не подойдёт. А просто "поражение гнилогазом" нормально в этом контексте будет смотреться?

**Comment by EcherArt** [comment]
> 

Топь - потому что в итоге гнилая жидкость внутри лёгких, как я понял, скапливается и убивает человека, т.е. он задыхается, захлёбывается, тонет.


Кстати, а чем оно лечится - это может быть не бактериальная инфекция, а отёк лёгких? https://ru.m.wikipedia.org/wiki/Отёк_лёгких В зависимости от этого пульмолютит либо подходит больше, либо нет

**Comment by RavenWWalker** [comment]
> Есть ещё плеврит, он может возникнуть как от самого вдыхания газа, так и от последующей инфекции [https://ru.m.wikipedia.org/wiki/Плеврит](https://ru.m.wikipedia.org/wiki/%D0%9F%D0%BB%D0%B5%D0%B2%D1%80%D0%B8%D1%82) . Как по мне, очень подходит.

Да, говорил о плеврите в беседе, поэтому тоже склоняюсь к нему.

**Comment by maxqwerty** [comment]
Предложения:

lung rot - поражение лёгких
rot stink exposure - поражение гнилью
rot stink gas - гнильный газ

**Comment by kamadz** [comment]
Ещё раз, плеврит - это воспаление плевры. Плевра - не всё легкое, а отдельная его часть. Зачем делать такое уточнение, если о нём не говорится в оригинале, лично мне непонятно.

**Comment by EcherArt** [comment]
Справедливо, просто хочется сесть на 2 стула сразу: сохранить упоминание об источнике проблем и указать примерные симптомы

**Comment by maxqwerty** [comment]
Мысль появилась во время просмотра ролика с обзором обновения: **rot stink gas** появляется у гниющих трупов, а больезнь **lung rot** появляется от этого газа. Предлагаю не использовать сложные медицинские термины, и показать связанность этих двух понятий:
* rot stink gas - газ гниения
* lung rot - гниль в лёгких
* rot stink exposure - поражение гнилью

**Comment by RavenWWalker** [comment]
> Мысль появилась во время просмотра ролика с обзором обновения: **rot stink gas** появляется у гниющих трупов, а больезнь **lung rot** появляется от этого газа. Предлагаю не использовать сложные медицинские термины, и показать связанность этих двух понятий:
> * rot stink gas - газ гниения


А как насчёт...
rot stink gas - трупный яд?
Мне кажется, что газ гниения не очень сюда идёт, а вот трупный яд - вполне медицинский термин, причём несложный.
Не знаю только, как в таком случае перевести lung rot и rot stink exposure.

**Comment by EcherArt** [comment]
тогда трупный газ? или это плохая идея?

**Comment by RavenWWalker** [comment]
> тогда трупный газ? или это плохая идея?

Почему именно газ? Если труп начинает разлагаться, то это трупный яд.
https://ru.wikipedia.org/wiki/Птомаины

**Comment by maxqwerty** [comment]
Про трупный яд говорят, когда он в воду попадает. А в игре это явление прям испарениями изображено, так что лучше как-то газ обозначить, если прямо не сказать.

**Comment by EcherArt** [comment]
> > тогда трупный газ? или это плохая идея?
> 
> Почему именно газ? Если труп начинает разлагаться, то это трупный яд. [https://ru.wikipedia.org/wiki/Птомаины](https://ru.wikipedia.org/wiki/%D0%9F%D1%82%D0%BE%D0%BC%D0%B0%D0%B8%D0%BD%D1%8B)

потому что в оригинале rot stink GAS. @maxqwerty верно говорит, трупный яд обычно находится в трупе и им нельзя надышаться

**Comment by RavenWWalker** [comment]
> потому что в оригинале rot stink GAS. @maxqwerty верно говорит, трупный яд обычно находится в трупе и им нельзя надышаться (если только не прилагать к этому особых усилий)

Понял, тогда спасибо за разъяснение, не знал.

**Comment by Elevator89** [comment]
А для "rot stink exposure" вообще не надо придумывать терминов. Дословно это просто "нахождение в гнилогазе". Тут не подразумевается никакой болезни.

"Пульмолютит" неплох. Но чтобы сохранить связь между терминами, для "lung rot" можно вообще прямую кальку сделать — "лёгочная гниль". И разговорное, и описанию соответствует, и связь с гнилогазом сохраняется.

**Comment by EcherArt** [comment]
По-моему, идеально, давайте так и сделаем

**Comment by kamadz** [comment]
![image](https://user-images.githubusercontent.com/57110948/198899293-5ab2254d-a675-44e1-ab9c-325c4de5d0f7.png)

**Comment by kamadz** [comment]
>А для "rot stink exposure" вообще не надо придумывать терминов. Дословно это просто "нахождение в гнилогазе". Тут не подразумевается никакой болезни.

На мой взгляд для игрока хедифф "нахождение в гнилогазе: лёгкое" будет не настолько информативным и призывающим к действию, как то же самое "поражение лёгких", тут бы я подумал над каким-то вариантом

Ну и пульмолютит я бы всё-таки оставил, "лёгочная гниль" выбивается на фоне других названий болезний, официальных или звучащих как официальные

**Comment by Elevator89** [comment]
> Ну и пульмолютит я бы всё-таки оставил, "лёгочная гниль" выбивается на фоне других названий болезний, официальных или звучащих как официальные

Пульмолютит плохо указывает потерял связь с гнилью. Не только лишь все знают латынь.

Насчёт выбивания из других названий — тоже не соглашусь. Есть blood rot, гнилокровие. Вролне себе разговорное название, такое же, как "лёгочная гниль".

**Comment by EcherArt** [comment]
Посмотрела глоссарий, blood rot у нас переведено как гнилокровие. Мне кажется, лёгочная гниль туда отлично впишется.

**Comment by kamadz** [comment]
А нам нужна специфическая связь с "гнилью"? В описании болезни, повторюсь в n-ый раз нигде не указано наличие гнилостных процессов. Оригинальное английское название - пример разговорного названия. Диабет называли "медовой болезнью" из-за сладковатого привкуса мочи больного, а не из-за появления в ней мёда.
Я не считаю лёгочную гниль плохим вариантом, но всё-таки провёл бы голосование.

**Comment by kamadz** [comment]
В то же время, гнилокровие отлично звучит, так как есть похожие прецеденты в языке: белокровие (рак крови), малокровие (анемия). С лёгочной гнилью в языке также непросто провести параллель в языке, но пульмолютит хотя бы звучит как диагноз.

**Comment by EcherArt** [comment]
> 
> Мысль появилась во время просмотра ролика с обзором обновения: **rot stink gas** появляется у гниющих трупов, 

как я понимаю (в игре ещё не натыкалась), болезнь связана с гнилью, и как минимум такое название указывает на её источник происхождения. Ну и вызывает она вряд ли что-то приятное для лёгких, учитывая её происхождение.

**Comment by kamadz** [comment]
>как я понимаю (в игре ещё не натыкалась), болезнь связана с гнилью, и как минимум такое название указывает на её источник происхождения. Ну и вызывает она вряд ли что-то приятное для лёгких, учитывая её происхождение.

Источник происхождения - не гной на трупах, а трупный газ, которым дышит человек.

>я считаю, что если в оригинале у некоторых болезней есть определённая рыба (blood rot, lung rot), и есть возможность ей следовать, то лучше так и сделать

Я бы согласился, если бы это были формы одной болезни, способной поражать разные системы тела, как туберкулёз. Есть лёгочный, есть костный, возбудитель один. Здесь же 2 разных болезни с похожим разговорным названием.

**Comment by kamadz** [comment]
Я напоминаю, что гнилогаз - тоже разговорное название, никакой гнили в нём не летает, просто ядовитые продукты разложения органики.

**Comment by EcherArt** [comment]
> Источник происхождения - не гной на трупах, а трупный газ, которым дышит человек.

трупный газ, возникающий на *гниющих* трупах

**Comment by kamadz** [comment]
Мы не ведём сейчас обсуждение гнилогаза, меня устраивает этот вариант

**Comment by EcherArt** [comment]
Я знаю, я к тому, что опускать гниль в lung rot не стоит имхо, потому что связь есть и должна быть понятна игроку

**Comment by kamadz** [comment]
"гнилогазовый пульмолютит", по сути, масло масляное
гнилогазовая пневмония? - не знаю, не уверен
я бы ещё подумал насчёт какого-то воркараунда, если корень "гнил-" все приниципиально хотят видеть в названии болезни

**Comment by kamadz** [comment]
>а какие аргументы были, чтобы не использовать гнилогаз в названии болезни?

не знаю, как-то никто ничего толком не предлагал

>мне почему-то кажется, что просто взять и дословно перевести именно здесь самый оптимальный вариант, а мы тут умничаем)

на мой взгляд, это субоптимальный вариант

**Comment by kamadz** [comment]
А как насчёт ещё фьюжена?
Пришёл в голову вариант, "трупная чахотка". Источник болезни сохранён, картина болезни передана

**Comment by EcherArt** [comment]
трупная чахотка звучит интересно, если она передаёт происходящее с пациентом, то почему бы и нет

**Comment by kamadz** [comment]
Мне кажется, для второго стоит оставить на рассмотрение варианты 1 и 3, "поражение гнилью" звучит как политический лозунг.
Не думаю, что нужны доп варианты для rot stink exposure, тут так не разойдёшься

**Comment by Elevator89** [comment]
> поражение гнилогазом vs поражение гнилью vs нахождение в гнилогазе vs ??? (rot stink exposure)

Я в одном из реквестов предложил "отравление гнилогазом". Больше подходит по описанию.

**Comment by EcherArt** [comment]
> гнилогазовая интоксикация/отравление (как угарным газом);
я тоже предлагала, мне сказали, что это некорректно
> использовать также нелогично, потому что: а) не развивается пневмония б) нет интоксикации
могу добавить в варианты (отдредактировать своё сообщение), если отравление тоже подходит

**Comment by Elevator89** [comment]
Есть lung rot - "трупная чахотка" или "лёгочная гниль"
А есть rot stink exposure - которое я и предлагаю перевести как "отравление гнилогазом"

Механика такая же, как с токсинами. Сначала отравление, которое даёт слабый дебаф и проходит со временем. А потом - химическое повреждение, уже постоянное увечье.

**Comment by Elevator89** [comment]
Итого имеем вариант:
- трупный газ
- отравление трупным газом
- трупная чахотка

И альтернативный вариант:
- гнилогаз
- отравление гнилогазом
- лёгочная гниль

Я бы выбрал первый, ибо мне не очень нравится "гнилогаз"

**Comment by kamadz** [comment]
Утверждённые варианты:

- **трупный газ
- отравление трупным газом
- трупная чахотка**

Закрываю ишью
