### ISSUE TITLE
Лишние строки в \ThingDef\Races_***.xml

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#142]
Во всех файлах типа Races_***.xml в папке ThingDef (15 шт.) есть такое:

![default](https://cloud.githubusercontent.com/assets/14166427/18785572/9984d718-81a1-11e6-9c31-5afcb0f99115.PNG)

![2](https://cloud.githubusercontent.com/assets/14166427/18785509/3f4ef44a-81a1-11e6-9cf4-452c50b5365c.PNG)

Красное нужно удалить
Синее нужно оставить
Чёрное - хз

**Comment by Dinoabunai** [comment]
Резать, резать и еще раз резать. ИМХО.

**Comment by Elevator89** [comment]
Закомментированный код - это всегда мусор.
А тут ещё и комментарий **явно** об это говорит.

**Comment by Elevator89** [comment]
Ещё не понятно, почему закомментированные строки в объектах Megascarab, Spelopede и Megaspider, выделенные синим, нужно оставлять.

**Comment by Dimonasdf** [comment]
Так-то это мой комментарий. Как и 95% по всей игре. Конкретно в этом ценности 0 на данный момент, и я бы его удалил, - поэтому оставил на ваш выбор.
Насчёт комментариев в синих скобках уже трижды пояснял.

**Comment by Elevator89** [comment]
Поясни четвёртый раз тут.

**Comment by Dinoabunai** [comment]
> Поясни четвёртый раз тут.

Хотел то же самое написать :)

**Comment by Dimonasdf** [comment]
Во-первых - это удобство. Графическая и логическая целостность делают элементарной проверку содержания (единая структура на все файлы: лейбл, деск, 3 кожи, 2 мита, 2 корпса). Просто мне пришлось переправлять эти файлы раз 10 после кого-то, потому что то содержательно они были не про то животное, то были лишние повторяющиеся дески/лейблы, то вообще не от того животного лейбл. Я плюнул искать ошибки и пропуски и переписал всё в единой наглядной структуре. Потом через репорты консоли закомментил всё лишнее. Это основное.
Во-вторых, (хотя я знаю, что для вас это не аргумент), это сделано навырост. Если эти части появятся в исходниках, нужно будет просто раскомментить. Легко, быстро и правильно.

**Comment by Ohar** [comment]
Удобства я тут не вижу, а вот про «на вырост» идея хорошая, но реализована неправильно. Под это надо было сделать отдельную ветку и в вики написать «Смержить как появится в игре».

**Comment by Elevator89** [comment]
Если в проекте нет соответствующей культуры, то закомментированный код никто не трогает из соображений "А вдруг когда понадобится?". Обычно когда над проектом работает больше чем один человек, то такие комментарии не правят и не обновляют ("Это делал не я, оно сейчас не используется, но наверно кому-то нужно, не буду удалять"). 
При этом нужный для раскомментирования момент может или не наступить, или за это время всё вокруг этого куска кода изменится так, что его уже будет там не применить. В первом случае имеет бесполезный мусор, а во втором - неработающий код. И хорошо, если его неработоспособность можно будет увидеть сразу.
Делать комментарии "на вырост" - ещё хуже. Этот код никогда и не был полезен, в отличие от просто закомментированного куска рабочего кода.
Ещё раз. Комментированный код это в лучшем случае мусор, в худшем - бомба замедленного действия. 
От таких вещей надо избавляться без раздумий!
