### ISSUE TITLE
Переименование бумалупы

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#143]
На данный момент животное **boomalope** у нас переведено как **"бумалупа"**.
Очевидно, что **"boomalope"** образовано от **"antilope"** и **"boom"**.
Но из чего исходил автор текущего перевода, решительно непонятно. Почему **"лупа"**?!
Перевод **"бумалупа"**, во-первых, не соответствует словообразованию оригинала, во-вторых наводит на ненужные ассоциации: "халупа", "Гваделупа", и т.д. Нелепо же )!
Варианты для переименования: **"бумалопа"**, **"бумолопа**, **"бум-антилопа"**, **"антилопа бум"** (калька с антилопы гну).

**Comment by Ohar** [comment]
Определённо, _бумалопа_

**Comment by Dinoabunai** [comment]
Когда жаждущая человеческой крови бумалупа приходит в поселение, понимаешь - это полная бумалупа. А так же что ты в полной бумалопе.
Мне нравится и "бумалупа" и "бумалопа". Можно еще "взрыволупа" или "взрыволопа" :)

**Comment by Elevator89** [comment]
Готово
