### ISSUE TITLE
Перевод скрытой фракции spacer

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#144]
На данный момент этот самый spacer переведен как "космоноид", предположительно по аналогии с механоидами. "Spacer" в данном случае не обозначение жуткого инопланетного монстра, а всего-навсего людей из далёкого космоса. Предлагаю (самой себе) исправить перевод и отыскать, не найдутся ли космоноиды где ещё.
Место конфуза: Definjected - FactionDef - Faction_Hidden
Пока рабочий вариант - "Космические странники". Если вдруг найдутся возражения - приводите.

**Comment by Dinoabunai** [comment]
Мне нравится вариант "космические странники".

**Comment by Ohar** [comment]
>космические странники

Предполагается что они странствуют. А они просто на голову падают по невыясненным причинам.

_Космоноид_ = космический гуманоид, не самый плохой вариант.

**Comment by EcherArt** [comment]
То есть на голову падают космические гуманоиды... Так моих бедных поселенцев еще никто не обывал =)
Они странствовали из пункта А в пункт Б по-любому, а не сидели у себя в Хоумворлде. Просто иногда в результате таких путешествий может случиться УПС!

**Comment by EcherArt** [comment]
космический путешественник сойдет?

**Comment by Ohar** [comment]
>Они странствовали из пункта А в пункт Б по-любому

А почему они не просто катапультировались из пролетавшего автобуса?

**Comment by EcherArt** [comment]
могли и просто.

**Comment by Elevator89** [comment]
"Космический странник" звучит более таинственно. Мне нравится этот вариант
