### ISSUE TITLE
Человек или животное "поглощает" пищу.

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#145]
Если кликнуть на поедающего что-либо поселенца или зверя, там будет написано примерно следующее:
![2016-09-24_00-04-06](https://cloud.githubusercontent.com/assets/22240259/18799902/50994616-81eb-11e6-8437-0e58d3a802ad.png)
Честно говоря, меня это слегка смущает. Могу ли я найти это место в игре и заменить поглощает на ест  ?

**Comment by Dinoabunai** [comment]
Я за "ест".

**Comment by Dinoabunai** [comment]
Я подозреваю это находится в **JobDef\Jobs_Misc.xml** тэг **`<Ingest.reportString>`**.

**Comment by Elevator89** [comment]
Я тоже за "ест"

**Comment by EcherArt** [comment]
Будет сделано =)

**Comment by Dimonasdf** [comment]
Сделайте тогда с двоеточием, как в "держит". Чтобы несхождения убрать.

**Comment by EcherArt** [comment]
Я не бодаюсь - а там точно они будут?
Нет, двоеточие поставить мне не лень, просто хочу знать, что упустила.

**Comment by Dimonasdf** [comment]
Ест трава.

**Comment by EcherArt** [comment]
Ок, понятно. Тогда буду писать с двоеточием.
