### ISSUE TITLE
Biotech DefInjected WorkGiver

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1453]
Автоформатированные файлы:
[Biotech DefInjected WorkGiver.zip](https://github.com/Ludeon/RimWorld-ru/files/9894081/Biotech.DefInjected.WorkGiver.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by RavenWWalker** [comment]
Забрал.

**Comment by kamadz** [comment]
Перехватил

**Comment by Reiquard** [comment]
Взял
