### ISSUE TITLE
Biotech DefInjected Xenotype

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1454]
Автоформатированные файлы:
[Biotech DefInjected Xenotype.zip](https://github.com/Ludeon/RimWorld-ru/files/9894082/Biotech.DefInjected.Xenotype.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
взял
