### ISSUE TITLE
Biotech DefInjected-Gene

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1455]
Автоформатированные файлы:
[Biotech DefInjected-Gene.zip](https://github.com/Ludeon/RimWorld-ru/files/9894084/Biotech.DefInjected-Gene.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
взял
