### ISSUE TITLE
Biotech DefInjected-Hediff

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1456]
Автоформатированные файлы:
[Biotech DefInjected-Hediff.zip](https://github.com/Ludeon/RimWorld-ru/files/9894089/Biotech.DefInjected-Hediff.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
Взял
