### ISSUE TITLE
Biotech DefInjected-Quests

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1457]
Автоформатированные файлы:
[Biotech DefInjected-Quests.zip](https://github.com/Ludeon/RimWorld-ru/files/9894090/Biotech.DefInjected-Quests.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by DmitryProskurin** [comment]
Возьму
