### ISSUE TITLE
Biotech DefInjected-Recipe

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1458]
Автоформатированные файлы:
[Biotech DefInjected-Recipe.zip](https://github.com/Ludeon/RimWorld-ru/files/9894091/Biotech.DefInjected-Recipe.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by UrekMazin0** [comment]
Взял
