### ISSUE TITLE
Biotech DefInjected ThoughtDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1460]
Автоформатированные файлы:
[Biotech DefInjected ThoughtDef.zip](https://github.com/Ludeon/RimWorld-ru/files/9894093/Biotech.DefInjected.ThoughtDef.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Nikuksis** [comment]
взял этот ишью на перевод
