### ISSUE TITLE
Biotech Keyed 1

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1461]
Автоформатированные файлы:
[Biotech Keyed 1.zip](https://github.com/Ludeon/RimWorld-ru/files/9894119/Biotech.Keyed.1.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Ylariel** [comment]
Забрал

**Comment by Elevator89** [comment]
Вернул обратно. Задача снова свободна

**Comment by Reiquard** [comment]
Взял
