### ISSUE TITLE
Biotech Keyed 2

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1462]
Автоформатированные файлы:
[Biotech Keyed 2.zip](https://github.com/Ludeon/RimWorld-ru/files/9894121/Biotech.Keyed.2.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Ylariel** [comment]
забрал

**Comment by DmitryProskurin** [comment]
Забрал
