### ISSUE TITLE
Biotech Keyed Alerts

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1463]
Автоформатированные файлы:
[Biotech Keyed Alerts.zip](https://github.com/Ludeon/RimWorld-ru/files/9894123/Biotech.Keyed.Alerts.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Ylariel** [comment]
Создал пуллреквест:  https://github.com/Ludeon/RimWorld-ru/pull/1472

**Comment by Elevator89** [comment]
Пулреквест не устроил нас по качеству перевода. Задача свободна

**Comment by Elevator89** [comment]
Пулреквест не устроил нас по качеству перевода. Задача свободна

**Comment by Reiquard** [comment]
Взял
