### ISSUE TITLE
Biotech Keyed Dialogs

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1464]
Автоформатированные файлы:
[Biotech Keyed Dialogs.zip](https://github.com/Ludeon/RimWorld-ru/files/9894124/Biotech.Keyed.Dialogs.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Ylariel** [comment]
Создал пуллреквест: https://github.com/Ludeon/RimWorld-ru/pull/1473

**Comment by Elevator89** [comment]
Пулреквест не устроил нас по качеству перевода. Задача свободна

**Comment by Elevator89** [comment]
Пулреквест не устроил нас по качеству перевода. Задача свободна

**Comment by Elevator89** [comment]
Автозакрылось по ошибке

**Comment by Elevator89** [comment]
Исправлено коммитом 4d08a6bd599111bf162abcefbb91ce606308cb94
