### ISSUE TITLE
Biotech Keyed FloatMenu

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1465]
Автоформатированные файлы:
[Biotech Keyed FloatMenu.zip](https://github.com/Ludeon/RimWorld-ru/files/9894128/Biotech.Keyed.FloatMenu.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Ylariel** [comment]
Создал пуллреквест: https://github.com/Ludeon/RimWorld-ru/pull/1474

**Comment by Elevator89** [comment]
Пулреквест не устроил нас по качеству перевода. Задача свободна

**Comment by Elevator89** [comment]
Взял себе
