### ISSUE TITLE
Biotech Keyed Gameplay

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1466]
Автоформатированные файлы:
[Biotech Keyed Gameplay.zip](https://github.com/Ludeon/RimWorld-ru/files/9894129/Biotech.Keyed.Gameplay.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
взял

**Comment by kamadz** [comment]
взял
