### ISSUE TITLE
Biotech Keyed ITabs

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1467]
Автоформатированные файлы:
[Biotech Keyed ITabs.zip](https://github.com/Ludeon/RimWorld-ru/files/9894131/Biotech.Keyed.ITabs.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
взял

**Comment by Nikuksis** [comment]
забрал
