### ISSUE TITLE
Biotech Keyed Letters

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1468]
Автоформатированные файлы:
[Biotech Keyed Letters.zip](https://github.com/Ludeon/RimWorld-ru/files/9894132/Biotech.Keyed.Letters.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by kamadz** [comment]
взял
