### ISSUE TITLE
Biotech Keyed Messages

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1469]
Автоформатированные файлы:
[Biotech Keyed Messages.zip](https://github.com/Ludeon/RimWorld-ru/files/9894135/Biotech.Keyed.Messages.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все TODO

**Comment by Nikuksis** [comment]
Забираю
