### ISSUE TITLE
Biotech Strings

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#1470]
Автоформатированные файлы:
[Biotech Strings.zip](https://github.com/Ludeon/RimWorld-ru/files/9894140/Biotech.Strings.zip)

Порядок действий:

1. Распаковать архив в корневую папку перевода с заменой существующих файлов
2. Перевести все части имён

**Comment by Ylariel** [comment]
Сделал пулреквест https://github.com/Ludeon/RimWorld-ru/pull/1475
