### ISSUE TITLE
Charger - перевод

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1485]
Временный: зарядная станция

**Comment by MarisKori** [comment]
Почему временный? Чем проще, короче, понятнее, тем лучше.

**Comment by RavenWWalker** [comment]
Почему не можем использовать "зарядник"?
Если ответ кроется в том, что "зарядник" - разговорное слово, то тогда вопросов нет.
А так, вот мои аргументы:
1) Кратко.
2) Пусть стиль разговорный, но так каждый игрок поймёт, о чём речь.

**Comment by Elevator89** [comment]
"Зарядная станция" больше на слуху. Используется реальной в жизни для электробритв, радиотелефонов и роботов-пылесосов. 
А ещё "Зарядная станция" лучше раскрывает смысл. "Зарядник" же не ассоциируется с чем-то стационарным. Просто абстрактное зарядное устройство.

**Comment by Elevator89** [comment]
Не вижу смысла что-то переделывать
