### ISSUE TITLE
Absorb xenogerm / implant xenogerm

### ISSUE THREAD

**Issue by kamadz** [Ludeon/RimWorld-ru#1487]
Временно для обоих: имплантировать ксеносемя
Есть проблема с одинаковым названием для двух разных действий (хоть и с одним результатом)

**Comment by Elevator89** [comment]
Absorb - забрать, собрать, присвоить ксеносемя

**Comment by RavenWWalker** [comment]
Implant xenogerm перевёл бы как "вживить ксеносемя".
А absorb xenogerm - "забрать ксеносемя".

**Comment by Elevator89** [comment]
"Забрать" выглядит как самый нейтральный и не скабрёзный вариант

**Comment by kamadz** [comment]
Absorb - насильственно вживить себе, implant - вживить 
Из обсуждения в телеге

**Comment by RavenWWalker** [comment]
Absorb xenogerm - "выкачать ксеносемя". Поскольку сама пересадка осуществляется при помощи органа-инъектора, который вживляет ксеносемя в человека, я бы мог сказать, что ксеносемя можно и выкачать из организма при помощи этого органа-инъектора.

**Comment by Elevator89** [comment]
### Процесс полностью

У пешки вырастает специальный орган (ксеносемя), который через другой орган-инъектор  можно вживить другому человеку. Если ксеносемя удалить до его полного "созревания", наступает смерть хозяина

И этот орган-инъектор можно насильственным образом использовать у жертвы, чтобы забрать ксеносемя себе.

### Наша задача

Найти органичный перевод процесса, **как со стороны жертвы, так и со стороны "насильника"**

**Comment by RavenWWalker** [comment]
Также могу по аналогии предложить для absorb xenogerm "выдавить ксеносемя".
Вот это уже выглядит более насильственно с точки зрения действия, что уточняет принудительный характер действия.

**Comment by EcherArt** [comment]
нейтральный вариант, может, уже обсуждался: получить ксеносемя (не вызывает отвращения, но не полностью передаёт процесс); 

либо (на основе комментария @Elevator89 ) забрать ксеносемя

инъецировать ксенсемя (сделать инъекцию; я проверила, что этот глагол существует)

**Comment by RavenWWalker** [comment]
> на основе комментариев @Elevator89 **забрать** ксеносемя звучит хорошо (absorb ) либо **извлечь**
> 
> выкачать и тем более выдавить возможно и хорошо передаёт процесс, но звучит отвратительно (не в плане качества перевода). **перекачать** тоже не фонтан, но имхо чуть менее противно. Возможно, выкачать, как и перекачать, плохая идея, если ксеносемя не жидкое. Не то чтобы мне хотелось уточнять этот момент.
> 
> если прямо нужно насильственность передать, то мб **отобрать** ксеносемя? если более официально, то **изъять**

Просто "отобрать" и "забрать" не отражают конечный результат процесса, а именно - самостоятельное вживление ксеносемени себе в организм, игнорируя волю обладателя ксеносемени.

**Comment by Elevator89** [comment]
Насчёт "выдавить" - сильно не уверен. Слишком физиологично. У тому же, вряд ли это именно так происходит, по задумке авторов.

Не могу придумать варианта, чтобы назвать процесс одним словом.
Единственное, что приходит на ум - `изъять и вживить себе` как активное действие
И `изъято ксеносемя у члена фракции` как причина порч отношений

**Comment by Elevator89** [comment]
Принятый вариант:
Для активного действия: `изъять и вживить себе`
Для пассивного `изъято ксеносемя`
