### ISSUE TITLE
Двоеточия в шаблонах

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#151]
В игре есть много строк-шаблонов вида:

```
вооружается TargetA.
подбирает TargetA.
надевает TargetA.
снимает TargetA.
раздевает TargetA.
открывает TargetA.
перезаряжает TargetA.
перезаправляет TargetA.
торгует с TargetA.
поджигает TargetA.
ест TargetA.
наполняет TargetA.
сливает пиво из TargetA.
```

Вместо TargetA игрой подставляется название объекта, над которым проводится действие, в **именительном падеже** вместо винительного. Из-за этого для существительных первого склонения в процессе игры появляются строки вида:

```
вооружается винтовка
наполняет бочка для ферментации
ест трава
```

Выглядит не очень. Чтобы избежать этого, предлагается использовать двоеточия:

```
вооружается: винтовка
наполняет: бочка для ферментации
ест: трава
```

Выглядит по прежнему не очень, но хотя бы используется одинаковая синтаксическая конструкция.
Вопрос: насколько оправдано добавление двоеточий для всех подобных случаев в переводе?

**Comment by Ohar** [comment]
> Вопрос: насколько оправдано добавление двоеточий для всех подобных случаев в переводе?

При отсутствии падежей — полностью оправдано.

**Comment by Dinoabunai** [comment]
Мне кажется с двоеточием - лучше.

**Comment by Elevator89** [comment]
А ничего, что даже с двоеточием конструкция синтаксически некорректна? Нет таких форм в русском языке.

**Comment by Dinoabunai** [comment]
А это мы, наверное, никак не сможем поправить.

**Comment by Elevator89** [comment]
Я больше за вариант без двоеточий, чтобы хотя бы для существительных 2 и 3 склонения винительный падеж выглядел прилично?
Видите разницу? Или мы, поставив двоеточие, сделаем одинаково хреново для всех существительных. Зато будет единообразие, да.
Или мы не будем использовать двоеточия, и для большей части слов сохраним "человеческий" синтаксис.
Мне кажется второй вариант правильнее.

**Comment by Ohar** [comment]
>Я больше за вариант без двоеточий, чтобы хотя бы для существительных 2 и 3 склонения винительный падеж выглядел прилично?

Не все 2 и 3 склонения, а только средний и женский род.

>Видите разницу? Или мы, поставив двоеточие, сделаем одинаково хреново для всех существительных. Зато будет единообразие, да.

Я бы с тобой согласился, но в интерфейсе они все описывают состояние поселенца — что он сейчас держит, ест, несёт. И единообразие тут важнее корректности, ибо упрощает восприятие информации. 

> Или мы не будем использовать двоеточия, и для большей части слов сохраним "человеческий" синтаксис.
Второй вариант будет разумнее, разве нет?

Если бы можно было сохранить как единообразие, так и корректность для всех случаев (то есть если бы были склонения) — я был бы очень рад. Но сейчас надо выбирать меньшее из двух зол и для меня это удобство игрока, то есть **двоеточия везде**.

**Comment by Elevator89** [comment]
Вопрос более не актуален.
