### ISSUE TITLE
Дефисы в сложных словах

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#152]
В переводе игры встречаются перлы вроде:
```
крипто-сон
энерго-сок
психо-корабль
```
В русском языке эти и многие другие иностранные приставки применяются без дефиса. Нужно найти в переводе все такие дефисы и убрать их.

**Comment by Dinoabunai** [comment]
Бумкрыса будет "бум-крыса". И не забудьте про детей ихних.
