### ISSUE TITLE
Ссылки на элементы интерфейса

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#153]
Нужно исправить ссылки на элементы интерфейса: вкладки, пункты меню, кнопки, - на страницах справки и обучения. Привсети их к единообразному виду, например:
`Откройте вкладку "ИССЛЕДОВАНИЯ"`,
то есть, в верхнем регистре и в кавычках.
Формат подлежит обсуждению и согласованию.

**Comment by Ohar** [comment]
*  Откройте вкладку «Исследования»<br>
в кавычках, с прописной буквы
*  Откройте вкладку И с с л е д о в а н и я<br>
Разрядкой через узкий неразрывный пробел ` `, с прописной буквы

**Comment by Elevator89** [comment]
Первый вариант мне нравится гораздо больше

**Comment by EcherArt** [comment]
@Ohar , нафиг неразрывный шрифт, но выглядит плохо, давай кавычки =)

**Comment by Dinoabunai** [comment]
Неразрывный пробел - чушь. Про остальное - я не понял о чем вообще речь.

**Comment by Elevator89** [comment]
Речь про унификацию формата подобных ссылок. У нас сейчас везде по-разному сделано, если что.

**Comment by Elevator89** [comment]
Остановимся на варианте `«Исследования»`

**Comment by Elevator89** [comment]
Прежде чем приступать, нужно сначала смержить #154.

**Comment by Ohar** [comment]
@Elevator89 не обязательно, можно просто от него бранчеваться.

**Comment by Dimonasdf** [comment]
Ещё есть вероятность, что в каком-то месте говорится: "Откройте вкладку N", а вкладка на самом деле называется "M". Я не утверждаю, что где-то конкретно такое есть, но чувство у меня присутствует.

`«Исследования»` - замечательный вариант.

**Comment by Elevator89** [comment]
@Dimonasdf, не испключено. В рамках выполнения этого задания за такими вещами надо будет следить.
