### ISSUE TITLE
AssaultRifle — «автомат», а не «штурмовая винтовка»

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#159]
Assault Rifle — это [англоязычное название оружия](https://ru.wikipedia.org/wiki/%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82_(%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D0%B5)), которое у нас сначала называлось «автоматическая винтовка», а позже [сократилось до «автомат»](http://piterhunt.ru/Library/gost_28653_90/index.htm). Фактически, название «штурмовая винтовка» — кривая калька с английского.

Предлагаю переименовать все соответствующие строки.

**Comment by Dinoabunai** [comment]
Согласен.
