### ISSUE TITLE
PowerClaw — «силовая клешня», а не «силовой коготь»

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#160]
_Силовая клешня_ — это такой механический манипулятор в виде щипцов, из нескольких (обычно двух, в RimWorld — трёх) когтей. 
Сравните примеры [силовых клешней](https://yandex.ru/images/search?text=%D1%81%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0%D1%8F+%D0%BA%D0%BB%D0%B5%D1%88%D0%BD%D1%8F&parent-reqid=1475252997792378-2157804327810998416130338-man1-4505) и [power claw](https://yandex.ru/images/search?text=power+claw&parent-reqid=1475252828053248-6107891655982169931137487-sas1-4219).
А _коготь_ — это лишь один из её элементов.

Собственно, это сказано и в описании PowerClaw

>Powerful hand replacement consisting of three deadly claws

В английском просто _claw_ имеет значение как _клешня_, так и _коготь_, эти слова не различаются. А в русском это разные слова для разных вещей и их не нужно путать.

**Comment by Dinoabunai** [comment]
Поддерживаю.

**Comment by Dinoabunai** [comment]
Так вроде наоборот - если "consisting of three deadly claws", то "состоящая из 3-х когтей", а не "состоящая из 3-х клешней". Как раз ими можно будет хватать все и на руку будет похоже. В вархаммере есть силовые когти, например.

**Comment by Ohar** [comment]
Именно.

>Клешня состоит из трёх когтей

а не как сейчас

> Коготь состоит из трёх когтей

**Comment by Dinoabunai** [comment]
> Коготь состоит из трёх когтей

Да, это дичь, конечно.

Мне всё же кажется что это скорее просто киберпротез с 3-мя острыми пальцами, а не клешня.
С другой стороны я не знаю как её в таком случае назвать без тавтологии, и, в принципе, можно отнести это чудо к "клешне".

Думаю "**силовая клешня**" с пивом покатит.

**Comment by Elevator89** [comment]
@Ohar, скурпулёзный подход к переводу. Жму вашу силовую клешню.

**Comment by Elevator89** [comment]
От себя могу предложить вариант "силовая лапа". У клешни всё же обычно два пальца: один напротив другого. А тут - просто три когтя. Видимо, как у Росомахи или Фреди Крюгера.
Но "клешня", конечно, звучит круче.

**Comment by Dinoabunai** [comment]
Мне кажется что 2 пальца и 1 противостоящий, чтобы брать все можно было. Как у черепашек-ниндзя.

**Comment by LatKrostov** [comment]
Клешня состоит из двух либо одной движущихся частей. 
"Claw" это еще и птичья лапа. Которая с когтями.
