### ISSUE TITLE
Неправильно отрабатывает автоустановщик.

### ISSUE THREAD

**Issue by Alexandr-Falcon99** [Ludeon/RimWorld-ru#1632]
Требуется небольшая корректировка автоустановщика, т.к. в текущем варианте от пытается удалить и распаковать в другое место, во всяком случае при запуске от администратора. Для корректной работы внес следующие коррективы:

`del /F /Q "%~dp0Data\Core\Languages\Russian (Русский).tar" >> nul
rd /S /Q "%~dp0Data\Core\Languages\Russian (Русский)\" >> nul
del /F /Q "%~dp0Data\Royalty\Languages\Russian (Русский).tar" >> nul
rd /S /Q "%~dp0Data\Royalty\Languages\Russian (Русский)\" >> nul
del /F /Q "%~dp0Data\Ideology\Languages\Russian (Русский).tar" >> nul
rd /S /Q "%~dp0Data\Ideology\Languages\Russian (Русский)\" >> nul
del /F /Q "%~dp0Data\Biotech\Languages\Russian (Русский).tar" >> nul
rd /S /Q "%~dp0Data\Biotech\Languages\Russian (Русский)\" >> nul
del /F /Q "%~dp0Data\Anomaly\Languages\Russian (Русский).tar" >> nul
rd /S /Q "%~dp0Data\Anomaly\Languages\Russian (Русский)\" >> nul

echo Распаковка обновлённой локализации...
xcopy "%TEMP%\RimWorld-ru-master\Core" "%~dp0Data\Core\Languages\Russian (Русский)\"  /H /Y /C /R /S >> nul
xcopy "%TEMP%\RimWorld-ru-master\Royalty" "%~dp0Data\Royalty\Languages\Russian (Русский)\"  /H /Y /C /R /S >> nul
xcopy "%TEMP%\RimWorld-ru-master\Ideology" "%~dp0Data\Ideology\Languages\Russian (Русский)\"  /H /Y /C /R /S >> nul
xcopy "%TEMP%\RimWorld-ru-master\Biotech" "%~dp0Data\Biotech\Languages\Russian (Русский)\"  /H /Y /C /R /S >> nul
xcopy "%TEMP%\RimWorld-ru-master\Anomaly" "%~dp0Data\Anomaly\Languages\Russian (Русский)\"  /H /Y /C /R /S >> nul`

**Comment by Alexandr-Falcon99** [comment]
А правильнее наверное будет так:
`if exist "%~dp0Data\Core\Languages\Russian (Русский).tar" del /F /Q "%~dp0Data\Core\Languages\Russian (Русский).tar" > nul
rd /S /Q "%~dp0Data\Core\Languages\Russian (Русский)\" > nul
if exist "%~dp0Data\Royalty\Languages\Russian (Русский).tar" del /F /Q "%~dp0Data\Royalty\Languages\Russian (Русский).tar" > nul
rd /S /Q "%~dp0Data\Royalty\Languages\Russian (Русский)\" > nul
if exist "%~dp0Data\Ideology\Languages\Russian (Русский).tar" del /F /Q "%~dp0Data\Ideology\Languages\Russian (Русский).tar" > nul
rd /S /Q "%~dp0Data\Ideology\Languages\Russian (Русский)\" > nul
if exist "%~dp0Data\Biotech\Languages\Russian (Русский).tar" del /F /Q "%~dp0Data\Biotech\Languages\Russian (Русский).tar" > nul
rd /S /Q "%~dp0Data\Biotech\Languages\Russian (Русский)\" > nul
if exist "%~dp0Data\Anomaly\Languages\Russian (Русский).tar" del /F /Q "%~dp0Data\Anomaly\Languages\Russian (Русский).tar" > nul
rd /S /Q "%~dp0Data\Anomaly\Languages\Russian (Русский)\" > nul

echo Распаковка обновлённой локализации...
xcopy "%TEMP%\RimWorld-ru-master\Core" "%~dp0Data\Core\Languages\Russian (Русский)\"  /H /Y /C /R /S > nul
xcopy "%TEMP%\RimWorld-ru-master\Royalty" "%~dp0Data\Royalty\Languages\Russian (Русский)\"  /H /Y /C /R /S > nul
xcopy "%TEMP%\RimWorld-ru-master\Ideology" "%~dp0Data\Ideology\Languages\Russian (Русский)\"  /H /Y /C /R /S > nul
xcopy "%TEMP%\RimWorld-ru-master\Biotech" "%~dp0Data\Biotech\Languages\Russian (Русский)\"  /H /Y /C /R /S > nul
xcopy "%TEMP%\RimWorld-ru-master\Anomaly" "%~dp0Data\Anomaly\Languages\Russian (Русский)\"  /H /Y /C /R /S > nul`

**Comment by Elevator89** [comment]
Авторы установщика не мы. Репозиторий установщика находится здесь: https://github.com/asidsx/RimWorldRuslangAutoUpdater

Напишите, пожалуйста, авторам напрямую
