### ISSUE TITLE
OperateDeepDrill — «производит бурение»

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#166]
Ужас какой, товарищи, вы видели, как оно выглядит? @Dinoabunai ну что же вы так?

![производит бурение](https://camo.githubusercontent.com/773ba856c103df52ea8819942be0dd703075756c/687474703a2f2f7075752e73682f72747249432f633262643863376361352e706e67)

**Comment by Dinoabunai** [comment]
Да, видели и обсуждали даже где-то. Есть предложения?

**Comment by Ohar** [comment]
>Есть предложения?

Очевидное _Бурит_.

**Comment by Elevator89** [comment]
Бурят дырку в зубе или в стене. А работая на буровой, _производят бурение_.

**Comment by Elevator89** [comment]
Ишью предлагается к закрытию

**Comment by Elevator89** [comment]
Не вижу ничего неверного в такой фразе. Что вас так смутило?

**Comment by Dinoabunai** [comment]
Меня ничего не смутило. "Производит бурение" - торт.

**Comment by Ohar** [comment]
Производят конфеты в кондитерской. 
А человек за бурильной установкой _бурит_. Откуда это канцелярит у вас берётся? 
Давайте ещё напишем _«Выполняет процесс бурения»_? Будет ещё канцеляристее, длиннее и бессмысленнее.

**Comment by Elevator89** [comment]
> Так же, как сверлит человек за сверлильным станком или копает человек на экскаваторе. Они не производят сверление и не производят копание.

Я на это уже ответил:

> Потому что это процесс гораздо гораздо более технически сложный, чем тупое механическое бурение-сверление.

**Comment by Elevator89** [comment]
Можно поправить на "выполняет бурение", но никак не на "бурит".

**Comment by EcherArt** [comment]
Моё мнение интересует или лучше не вмешиваться?

**Comment by Dimonasdf** [comment]
"Производит бурение" - наиболее удачный вариант при имеющихся обстоятельствах. Ничего не попишешь.

**Comment by Elevator89** [comment]
@EcherArt, участвовать в дискуссиях - важно. Но важность самой этой дискуссии для меня под большим вопросом.

**Comment by Ohar** [comment]
>Я на это уже ответил:
Потому что это процесс гораздо гораздо более технически сложный, чем тупое механическое бурение-сверление.

Нет, не ответил. Как сложность процесса влияет на его название?

**Comment by Elevator89** [comment]
Обычно, чем более формальной фразой описан процесс, тем сложнее и серьёзнее читателю этот процесс кажется. 
И наоборот, чем короче описан процесс, тем более простым и незамысловатым он видится читателю.
Глубокое бурение - процесс [сложный](http://www.mining-enc.ru/g/glubokoe-burenie/).

**Comment by Elevator89** [comment]
Цель этого обсуждения перестала оправдывать время, на него потраченное.
Давайте выберем из конкретных вариантов и прекратим эту дискуссию:
"производит бурение"
"выполняет бурение"
"осуществляет бурение"

**Comment by Ohar** [comment]
Да какая разница — сложный это процесс или нет? 
Это игровое _взаимодействие поселенца с постройкой_. Оно ничем не отличается от взаимодействия с любой другой постройкой.
Даже если допустить некую _сложность_ этого процесса (с чем я категорически не согласен), то тем самым вы утверждаете, что это самый сложный из выполняемых поселенцами процесс в игре. То есть он сложнее _производства силовой брони_, _постройки космического корабля_, _научных исследований_ и _производства плазменного оружия_. 
Верно я понимаю? Вам это не кажется абсурдным, нет?
Если не кажется, то тогда так _официозно_ надо переводить и действия поселенцев в этих процессах. 
А если кажется (я надеюсь), то не надо придумывать какие-то _сложные_ процессы, которые из-за своей _сложности_ внезапно стали требовать лишние слова для своего описания.

**Comment by Elevator89** [comment]
> Даже если допустить некую сложность этого процесса (с чем я категорически не согласен)

Я [пруф](http://www.mining-enc.ru/g/glubokoe-burenie/) предоставил, если ты не заметил. Если ты читал, то должен был увидеть, что процесс достаточно сложный.

> вы утверждаете, что это самый сложный из выполняемых поселенцами процесс в игре.

Про то, что это **самый** сложный процесс, никто не говорил. Про другие сложные процессы - давай в Телеграме обсудим конкретные примеры, и будем думать.
Например, текущий перевод "исследует" не отражает сложности работы. Выглядит так, как будто он не проводит научные изыскания, а исследует узор на обоях.

А по теме - выбирай вариант из предложенных, или я закрываю ишью.

**Comment by Ohar** [comment]
> Я пруф предоставил, если ты не заметил. Если ты читал, то должен был увидеть, что процесс достаточно сложный, чтобы не описывать его как просто "бурит".

Я достаточно [подробно разъяснил](https://github.com/Ludeon/RimWorld-ru/issues/166#issuecomment-251158681), что этот пруф пруфом не является, поскольку, если считать его пруфом, то надо по аналогии переписывать половину действий поселенцев.

>Про то, что это самый сложный процесс, никто не говорил. 

Да ну? Тогда почему только он выделен таким оборотом? Ни по чему? Тогда это нарушает единообразие названий и путает игрока и, как ошибка, должно быть исправлено.

>А по теме - выбирай вариант из предложенных, или я закрываю ишью.

Все варианты не лучше текущего.

**Comment by Elevator89** [comment]
> Я достаточно подробно разъяснил

Ты не предоставил ни одного агрумента, кроме нарушения так важного для тебя единообразия

> Тогда это нарушает единообразие названий и путает игрока и, как ошибка, должно быть исправлено.

Ты слишком преувеличиваешь значение этого единообразия для игроков. Если ты считаешь, что это должно быть исправлено, то создавай ишью, будем переделывать остальные описания работ.
Только этим нужно заниматься точно не сейчас. 
Первым делом - перевод. Все исправления - потом.
Ишью закрываю.
