### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#17]
Where is data for recipes stored?

![default](https://cloud.githubusercontent.com/assets/14166427/9793457/2969c016-57ee-11e5-813d-e6f3a2d5fe7b.png)

I've found:
https://github.com/Ludeon/RimWorld-Korean/blob/master/defInjected/RecipeDef/Recipes_Injection.xml
in Korean and
https://github.com/AlyxMS/RimWorld-cn/blob/master/DefInjected/RecipeDef/Recipes_add.xml
in Chinese folders, but I've tried them both and assume they are for older versions, since none of them worked. So, what is the solution?

**Comment by hazestalker** [comment]
Смотри с помощью программы TextReplacer. Слова глубоко зарыты

**Comment by Dimonasdf** [comment]
Начал искать этой программой, нашел вот это: 
![1](https://cloud.githubusercontent.com/assets/14166427/9815214/0a04d706-589d-11e5-805c-f6c249a0985c.PNG)
(то есть ничего). 

Но потом понял, что я те два файла закинул не в ту папку. Кинул китайский и корейский в русскую папку, и, о чудо,
![default](https://cloud.githubusercontent.com/assets/14166427/9815288/8952f286-589d-11e5-9c5a-a830f523db3e.png)
Теперь просто надо перевести Recipes_Add.xml, и все будет пучком.

При этом, что меня откровенно бесит, так это то, что нет отвечающего этому делу английского кода:
![3](https://cloud.githubusercontent.com/assets/14166427/9815495/31aaad6a-589f-11e5-877a-0bb1ac781b35.PNG)

Результат:
![2](https://cloud.githubusercontent.com/assets/14166427/9815827/c3aa0f38-58a1-11e5-99f6-0ac723f777db.png)
Все ок.

**Comment by Dimonasdf** [comment]
Гуд.

![default](https://cloud.githubusercontent.com/assets/14166427/9816415/8c113a20-58a5-11e5-8e60-86cba7e7fa9e.png)
