### ISSUE TITLE
Keyed/Grammar-Letters

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#172]
Просмотреть файл(ы):
1) добавить отстутвующие теги;
2) отрефакторить имеющийся перевод.

**Comment by Ohar** [comment]
Если речь идёт о `Keyed/Grammar.xml`, то не вижу в нём проблем. Ну, кроме того, что он очень плохо подходит не английскому языку.

**Comment by Elevator89** [comment]
Речь идёт обо всех файлах, начиная с Grammar.xml и заканчивая Letters.xml

**Comment by Ohar** [comment]
Оу, вот как это читается.
