### ISSUE TITLE
Убрать точки в конце предложений, которые не входят в тексты

### ISSUE THREAD

**Issue by Ohar** [Ludeon/RimWorld-ru#178]
Точка — это пунктуационный знак, отделяющий предложения друг от друга, как пробелы отделяют слова. 
Поэтому точки уместны только там, где такое разделение имеет смысл — в текстах, содержащих больше одного предложения. 
Во всех одиночных предложениях точки в конце не имеют никакого смысла и их нужно убрать.

**Comment by Dinoabunai** [comment]
Протестую. Законченное предложение тоже должно заканчиваться точкой.

**Comment by Dinoabunai** [comment]
https://ru.wikipedia.org/wiki/%D0%A2%D0%BE%D1%87%D0%BA%D0%B0_(%D0%B7%D0%BD%D0%B0%D0%BA_%D0%BF%D1%80%D0%B5%D0%BF%D0%B8%D0%BD%D0%B0%D0%BD%D0%B8%D1%8F)

**Comment by Ohar** [comment]
[Статья Шварцкопфа «Точка в заглавии»](http://www.gramota.ru/biblio/magazines/rr/28_563)
>В современной русской печати в конце заголовка употребление точки не принято. Это положение узаконено специальными пособиями и справочниками для корректоров и редакторов

[Ответ Грамоты](http://new.gramota.ru/spravka/buro/search-answer?s=274711)
>Точки в заголовке, согласно общему правилу, не ставятся.

[А. Э. Мильчин, Л. К. Чельцова, «Справочник издателя и автора»](https://orfogrammka.ru/OGL03/70091331.html#id-1%D0%A0%D1%83%D0%B1%D1%80%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F-1141%D0%97%D0%BD%D0%B0%D0%BA%D0%BF%D1%80%D0%B5%D0%BF%D0%B8%D0%BD%D0%B0%D0%BD%D0%B8%D1%8F%D0%B2%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%BE%D0%B2)
> Точку в заголовке, вынесенном в отдельную строку, опускают

[Большой толковый словарь](http://tolkslovar.ru/t3965.html)
> Точка <…> знак препинания, разделяющий предложения.

Там же [Словарь Ушакова](http://tolkslovar.ru/t3965.html)
> Точка <…> знак препинания (.), отделяющий законченную часть речи от последующего текста

**Comment by Dimonasdf** [comment]
Что-то я не очень понял, что это за грамматика 21 века. Можно, пожалуйста, скриншоты конкретных случаев, где нежелательно наличие точки в конце предложения?

**Comment by Ohar** [comment]
@Dinoabunai Этому нормативу [лет 80 уже](http://www.gramota.ru/biblio/magazines/rr/28_563). 

>Переход от старого правила оформления заголовка (...ставится точка) к новому (...не ставится точка), можно предполагать, произошел примерно на рубеже 1932–1933 гг.

Скриншоты сделаю попозже.

**Comment by Elevator89** [comment]
Точки из мест, где их точно не должно быть, удалены. Если найдётся что-то ещё, залью отдельно.
