### ISSUE TITLE
Stonecutting table

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#183]
Сейчас "**Stonecutting table**" переведён как "камнерезный станок".
Во-первых немного режет глаз, во-вторых технологически относится к неолиту по меркам игры. Поэтому предлагается к обсуждению корректность данного перевода.

**Comment by Dinoabunai** [comment]
Мне кажется вариант "стол для резки камня" подойдет больше.

**Comment by Ohar** [comment]
_камнерезный стол_
_камнерезный верстак_

_«Для резки камня»_ проще и лучше читается, но _«камнерезный»_ звучит более специализированно.

**Comment by LatKrostov** [comment]
Стол камнерезным быть не может. Камнерезной может быть пила или станок.

Но относительно неолита это все же "стол для обработки камней".
