### ISSUE TITLE
Tribe description

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#194]
В оригинале в описании племени говорится "nomadic people who live off the land", что означает "кочевники, живущие за счёт земли". 
Но, как известно, кочевники не занимаются земледелием.
Возможно, стоит перевести как-то по-другому, отойдя от оригинала в пользу здравого смысла?

**Comment by EcherArt** [comment]
Вариант 1:

Эти люди обитают на планете очень давно. Возможно, их предки разбились здесь тысячи лет назад. А может они пережили катаклизм, который разрушил более развитую цивилизацию. В любом случае, большинство аборигенов вечно скитаются по этой земле, используя примитивное оружие и орудия труда.\n\nОдни племена более агрессивны, другие открыты для торговли и альянсов, даже со странными народами вроде вас.

**Comment by EcherArt** [comment]
Вариант 2:

Эти люди обитают на планете очень давно. Возможно, их предки разбились здесь тысячи лет назад. А может они пережили катаклизм, который разрушил более развитую цивилизацию. В любом случае, большинство аборигенов живут за счёт даров природы, используя примитивное оружие и орудия труда.\n\nОдни племена более агрессивны, другие открыты для торговли и альянсов, даже со странными народами вроде вас.

**Comment by EcherArt** [comment]
Вариант 3: 

Эти люди обитают на планете очень давно. Возможно, их предки разбились здесь тысячи лет назад. А может они пережили катаклизм, который разрушил более развитую цивилизацию. В любом случае, большинство аборигенов ведут кочевой образ жизни, используя примитивное оружие и орудия труда.\n\nОдни племена более агрессивны, другие открыты для торговли и альянсов, даже со странными народами вроде вас.

**Comment by EcherArt** [comment]
Вариант 4:

Эти люди обитают на планете очень давно. Возможно, их предки разбились здесь тысячи лет назад. А может они пережили катаклизм, который разрушил более развитую цивилизацию. В любом случае, большинство аборигенов обживают эту землю, используя примитивное оружие и орудия труда.\n\nОдни племена более агрессивны, другие открыты для торговли и альянсов, даже со странными народами вроде вас.

**Comment by LatKrostov** [comment]
"live off the land" - в английском языке имеет более широкое значение чем в русском. Фактически сюда попадет всё, что получается из земли + скотоводство. Те же самые пресловутые ковбои тоже живут "live off the land". А вообще это словосочетание уже очень близко к идиоме. Так что вполне можно заменить этот пассаж на "живут за счет скотоводов и охотник-собирателей" или на " живут за счет  охоты и скотоводства".
