### ISSUE TITLE
Падежи в Strings/NameBanks

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#196]
Нужно сделать генеримые игрой предложения более согласованными. Для составления предложений используются правила, описанные в RulePackDef и строки из Strings. Для грамотных конструкций нужно прийти к целому ряду соглашений. 
Например, 
1. цвета, описанные Strings/NameBanks/Colors.txt стоят в именительном падеже.
2. Для нахождения мест использования названий цветов производится поиск всех вхождений метки "[color]".
3. Находим таким образом строку, например, "работа выполнена в оттенках [color] и [color]". 
4. Понимаем, что фраза "работа выполнена в оттенках **красный** и **синий**" плохо согласована, и придумаывем ей замену, например, "в работе присутствуют **красный** и **синий** цвета".
4`. Или же меняем падеж цветов в Strings/NameBanks/Colors.txt, чтобы пришлось менять меньше шаблонов. Тут есть риск запороть больше, чем исправить.

Задача сложная, требует много времени и усилий.

**Comment by fiziologus** [comment]
4` А можно поменять сами цвета на мало изменяющиеся аналоги (синь, лазурь, багрянец, как примеры). Просто цвета используются и как прозвища, но род при этом не учитывается (а все прилагательные в мужском роде, и получается что-то вроде Лиза "Красный" Тутыкина).

**Comment by Elevator89** [comment]
Цвета не только в именах используются, но и в названиях фракций, например, "синий убийца"

**Comment by Elevator89** [comment]
Сделал коммит: 22ecc01416d3e1a3043386af42a285be5515d945. В пулреквест не вносил. Извинияюсь.

**Comment by Elevator89** [comment]
Исправлено и смерджено: aa57c198e4f73c8f8d5b07525b80aea2d1d2c842
