### ISSUE TITLE
<Male> и <Female>

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#199]
В файле Keyed/Menus_main.xml находятся теги \<Male\>и \<Female\>. Строки из этих тегов применяются в разных местах и контекстах, и как прилагательное, и как существительное:
1. Животные: `<Male>, птенец индейки Хиалех`
2. Люди: `<Female>, житель Хиалех, возраст 31`
3. Описания, заголовки и уведомления для PsychicDrone и PsychicSoothe. Сейчас это выглядит как `В течение нескольких дней настроение у некоторых людей (он) будет немного лучше` и `Умиротворение (он)`
Это надо исправить.
Самое логичное и разумное, что приходит на ум, это:
```
  <Male>мужского пола</Male>
  <Female>женского пола</Female>
```
Вопрос к опытным переводчикам: где ещё применяются эти строки?

**Comment by EcherArt** [comment]
@Dimonasdf ? @LatKrostov ? @Ohar ??
