### ISSUE TITLE
Казармы

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#200]
"Barracks" сейчас переведено как "казармы". Что неверно, ибо к армии общие спальни не имеют отношения. Нужно найти вхождения "казарм" с исправить на "общую спальню".

**Comment by Ohar** [comment]
А почему не бараки?

**Comment by EcherArt** [comment]
Вероятно, потому что даже серебром и платиной отделанная спальня будет обозвана бараком. А барак в русском языке имеет негативную окраску.

**Comment by Elevator89** [comment]
Барак - это здание. А в игре общая спальня может быть лишь одним из помещений большого здания.
