### ISSUE TITLE
"Противный" человек

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#203]
В ThoughtDef\Thoughts_Memory_Social.xml фраза:
`Меня оскорбили! Какой противный человек!`
Жаль, что не "праативный". Исправить на **нормальный** вариант.

**Comment by EcherArt** [comment]
"неприятный человек" сойдёт?

**Comment by Elevator89** [comment]
Я думаю заменить на более естественное: 
`Меня оскорбили! Ну что за человек!`

**Comment by Dimonasdf** [comment]
> I've been directly insulted! What an awful person!

**Comment by Elevator89** [comment]
То, что это так по английски пишется, понятно.
Нам же нужен не дословный перевод, а тот, в который поверит игрок.

**Comment by Elevator89** [comment]
При этом цензурная

**Comment by Dimonasdf** [comment]
Ни на что не намекал, просто скинул текст для референса. _Верю_ в твой вариант.
