### ISSUE TITLE
Баглист перевода

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#206]
Различные ошибки перевода, с которыми встречаемся(юсь) по ходу игры.

**Comment by Dimonasdf** [comment]
Из моего файла с багами (не очень помню, что к чему относится, но раз отметил, значит что-то там было не так):

> 
> У Tail развилась зависимость от психин.
> У неё теперь есть потребность в психин.
> 
> люциферий - без повторного приёма в течении... течении?
> социальные наркотики - полная херня
> manage drug policy - управление приёмом препаратов
> Известен как Ла Лл Ла, и он торговец контрабандой. Запятая.

**Comment by Dimonasdf** [comment]
В обучении я написал:

> Вы можете увидеть много разных биомов, но давайте начнём с благоприятного.

Что тоже "полная херня".

Надо переписать

`<ChooseLandingSite.text>Здесь вы выбираете место для посадки.\n\nВы можете увидеть много разных биомов, но давайте начнём с благоприятного.\n\nВыберите место с умеренными лесами на равнине и нажмите кнопку «Выбрать место».</ChooseLandingSite.text>`

в DefInjected/InstructionDef/Instructions.xml по-человечески.

**Comment by Dimonasdf** [comment]
Тут есть предложение сделать `точную настройку` с большой буквы, чтобы выглядело покачественнее и, опционально, согласовать с `тонкой настройкой` в обучении.

![default](https://cloud.githubusercontent.com/assets/14166427/19458113/bc5cf484-94d2-11e6-8252-9db37af873ac.png)

**Comment by Dimonasdf** [comment]
Согласовать _научный стол_ <-> _верстак учёного_

![default](https://cloud.githubusercontent.com/assets/14166427/19458191/3f9115b0-94d3-11e6-82ca-dde1124cbc6c.png)

**Comment by Tibalbo** [comment]
![11](https://cloud.githubusercontent.com/assets/18379630/19484255/6ebd0202-9570-11e6-83d6-ef2c09002951.png)

**Comment by Elevator89** [comment]
@Dimonasdf, видишь ошибку - создавай для неё отдельное ишью.

**Comment by Elevator89** [comment]
> полная херня

без комментариев

**Comment by Dimonasdf** [comment]
@elevator89 наоборот потом подумал, что лишнюю создал, ибо уже есть #32. Но в той уже >100 комментариев и она подвисает, так что не стал туда всё переписывать.

Ну, разочаровался я в "социальных наркотиках") Это поменяли, кстати, или так и висят?

**Comment by Elevator89** [comment]
"Социальные наркотики" не меняли.
#32 я собираюсь закрыть за её бесполезностью. На 90% там просто болтовня.

**Comment by Elevator89** [comment]
@Dimonasdf, @Tibalbo, создавайте отдельные ишью. Общую свалку делать не надо.

**Comment by Elevator89** [comment]
Всё или уже неактаульно, или сделано, или создано отдельное ишью. Тема закрыта.
