### ISSUE TITLE
Строки про "привязанность" не помещаются

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#207]
1. Строка "Продали Цербер, а ведь я так привязался(ась)..." - не помещается в окне.
2. "Василич продал(а) моё животное, к которому я привязался(ась) всей душой" - слишком длинная строка для социального отношения.

**Comment by Elevator89** [comment]
Сейчас вот так:
![default](https://cloud.githubusercontent.com/assets/21694533/19576801/21bedf4e-971d-11e6-90da-415f2771fc4f.png)
И это всего лишь недлинная кличка "Цербер", а ведь есть ещё "Сорвиголова". 
@Dimonasdf, @EcherArt, Нужна помощь, ребят!

**Comment by EcherArt** [comment]
По Церберу - можно убрать любимый. Или "продан мой Цербер".

**Comment by Elevator89** [comment]
Цербер - это обезьяна женского пола

**Comment by EcherArt** [comment]
Возможно, сначала не надо обзывать самку Цербером =)
Продан питомец тогда.

**Comment by Elevator89** [comment]
> Возможно, сначала не надо обзывать самку Цербером =) 

это не я, оно само )

> Продан питомец

"продан питомец, Цербер" - вариант. Только вот у меня полно других питомцев: 15 индеек, 2 лабрадора и 1 альпака́. И к ним ни у кого нет привязанности.

**Comment by EcherArt** [comment]
Продано жывотное.

**Comment by Elevator89** [comment]
А с человеком как быть?

**Comment by EcherArt** [comment]
Продан(а) имя
Есть ещё вариант продали в рабство, но он 100% не влезет

**Comment by Elevator89** [comment]
тут важно сообщить, что продан именно любимый человек или животное

**Comment by EcherArt** [comment]
Сколько знаков влезет?

**Comment by Elevator89** [comment]
В игре не моноширинный шрифт. Примерно 29.

**Comment by EcherArt** [comment]
Продали любимого(ую) : имя
Ну или с тире.

**Comment by Dimonasdf** [comment]
Ну или так. Если влезет.

**Comment by Dimonasdf** [comment]
(Написал в закрытый реквест, сорян. Дублирую.)

```
<label>
<labelSocial>
<description>
```

> <label>bonded animal {0} sold</label>
> <labelSocial>sold my bonded animal</labelSocial>
> <description>My special bonded animal was sold to a trader!</description>

>   <SoldMyBondedAnimal.stages.0.label>Geliebtes Haustier {0} verkauft</SoldMyBondedAnimal.stages.0.label>
>   <SoldMyBondedAnimal.stages.0.labelSocial>Mein geliebtes Haustier wurde verkauft</SoldMyBondedAnimal.stages.0.labelSocial>
>   <SoldMyBondedAnimal.stages.0.description>Mein geliebtes Haustier wurde an einen Händler verkauft!</SoldMyBondedAnimal.stages.0.description>

>   <SoldMyBondedAnimal.stages.0.label>продан любимый питомец, {0}</SoldMyBondedAnimal.stages.0.label>
>   <SoldMyBondedAnimal.stages.0.labelSocial>продал(а) любимое животное</SoldMyBondedAnimal.stages.0.labelSocial>
>   <SoldMyBondedAnimal.stages.0.description>Животное, к которому я привязался(ась) всей душой, продали торговцу!</SoldMyBondedAnimal.stages.0.description>

Из разумный предложений было бы лишь сократить информационное содержание конкретно этой подписи с тем, чтобы расширить его в пояснении. Однако по сути, дескрипшн и так полностью описывает ситуацию. Так что можно просто:

> <label>{0} продан(а)</label>
> <labelSocial>продал(а) любимое животное</labelSocial>
> <description>Животное, к которому я привязался(ась) всей душой, продали торговцу!</description>

____________________________________________________________________________________________________________
Сейм стори тут:

> <label>loved one {0} sold</label>
> <labelSocial>sold my loved one</labelSocial>
> <description>Someone I love was sold to a trader like a piece of meat!</description>

> <SoldMyLovedOne.stages.0.label>{0} продан(а)</SoldMyLovedOne.stages.0.label>
> <SoldMyLovedOne.stages.0.labelSocial>продал(а) любимого человека</SoldMyLovedOne.stages.0.labelSocial>
> <SoldMyLovedOne.stages.0.description>Человека, которого я любил(а), продали торговцу, словно кусок мяса!</SoldMyLovedOne.stages.0.description>

Опционально:

> <SoldMyLovedOne.stages.0.label>{0} продан(а) в рабство</SoldMyLovedOne.stages.0.label>

Чтобы различать.

**Comment by Dimonasdf** [comment]
Ну или так, как вы предлагаете. Если влезет, то отлично.
