### ISSUE TITLE
"Недостаточно энергии" при нехватке материалов

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#215]
![default](https://cloud.githubusercontent.com/assets/21694533/19581023/e50a55ae-9732-11e6-8e53-b170ad2b4f3a.png)

**Comment by Dimonasdf** [comment]
Это в _Keyed\Misc_Gameplay.xml_, 21 строчка.
Возможно, когда-то там и была энергия, но не теперь.

`  <NotEnoughStoredLower>not enough stored</NotEnoughStoredLower>`
`  <NotEnoughStoredLower>недостаточно энергии</NotEnoughStoredLower>`

**Comment by Dimonasdf** [comment]
Вариант:

недостаточно на складе

**Comment by Elevator89** [comment]
> Возможно, когда-то там и была энергия, но не теперь.

Это многое меняет. Откуда такая уверенность?

**Comment by Dimonasdf** [comment]
@Elevator89 просто предположение. не могли же так с потолка перевести.
Что это меняет?

Если только оно и сейчас какое-то отношение к энергии имеет. Тогда про склад не пойдёт. Можно просто "недостаточно".

**Comment by Elevator89** [comment]
> Если только оно и сейчас какое-то отношение к энергии имеет. Тогда про склад не пойдёт.

Вот да, я про это и говорю. Вижу два варианта:
1. Написать всё-таки про склад или материалы:
`50 (недостаточно на складе)`
`50 (недостаточно материала)`
`50 (не хватает на складе)`
`50 (не хватает материала)`
и уже после, методом тыка, пытаться найти случай с энергией. 
2. Ломать голову над универсальным вариантом:
`50 (не хватает ресурса)`
`50 (недостаточно ресурса)`
Писать просто "недостаточно" или просто "не хватает", на мой взгляд, не стоит. Непонятно, чего недостаточно: накопленного ресурса или этих самых 50-ти единиц.

**Comment by Dimonasdf** [comment]
Там же ещё такая история, что ресурс-то может и быть, но если он не лежит на выделенном под него складе, он не считается. Так что про склад надо.

`недостаточно на складе`

**Comment by Elevator89** [comment]
На твоём скрине выделена плита, не подключённая к сети, и плита, подключённая и работающая.
Если тебе не трудно, проверь, пожалуйста, что написано на тех плитах, что подключены к сети, но которые не работают из-за перегруза (те, которые с тянущимся к ним проводом и с желтым значком).

**Comment by Dimonasdf** [comment]
Там то же самое, что и на работающей. Говорю же, невразумительно всё.

**Comment by Dimonasdf** [comment]
Немного разобрался.
Мощность сети, это свободная энергия. Подключено 8 плит по 350 Вт. Выработка панели 1700. Работает только 4 плиты -> 1400 Вт. потребляется, 300 свободно. Т.к. 300 не достаточно ни для одной  последующей плиты, они не работают. Но при этом об этом ничего кроме иконки не говорит. Описание на всю сеть одно.

**Comment by Elevator89** [comment]
Ясно. Тогда предлагаю остановиться на "недостаточно на складе".
