### ISSUE TITLE
Game doesn't use the translation given. Code problem?

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#22]
I'll describe the issue on the example of "power conduit".
Here is the original code (Buildings_Power.xml):
![1](https://cloud.githubusercontent.com/assets/14166427/10043807/88b8fde2-61fe-11e5-9f14-e824fde4a40d.PNG)

It is translated accordingly in our Buildings_Power.xml file:
![2](https://cloud.githubusercontent.com/assets/14166427/10043843/c0c59e20-61fe-11e5-8e70-8c4f9b10f2cf.PNG)

Jobs are done correctly too:
![3](https://cloud.githubusercontent.com/assets/14166427/10043857/daaefb06-61fe-11e5-8274-bcd413fd9f8c.PNG)
![4](https://cloud.githubusercontent.com/assets/14166427/10043859/dd9021a6-61fe-11e5-829b-40084bc8e287.PNG)

(By the way, `TargetA` can be changed to `{0}` and everything will still work. Is `TargetA` the old code style?)

Now, the problem is in game.
We can see it beeing translated correctly whether it's a building, a blueprint or a frame.

![screen1](https://cloud.githubusercontent.com/assets/14166427/10044272/394c09ee-6202-11e5-8a9c-043b6ddea8dd.png)
![screen3](https://cloud.githubusercontent.com/assets/14166427/10044273/3f677232-6202-11e5-90f7-5d5810011cb4.png)
![screen2](https://cloud.githubusercontent.com/assets/14166427/10044274/41c0b462-6202-11e5-9071-a91a86e5da8f.png)

Even prioritizing:
![screen5](https://cloud.githubusercontent.com/assets/14166427/10044277/46c7d97c-6202-11e5-8bac-e16345c667b8.png)

BUT. If we check the info panel of our colonist, we will see, that neither during building nor hauling, the translation is not being picked up by the game:
![screen4](https://cloud.githubusercontent.com/assets/14166427/10044283/4beb5636-6202-11e5-9510-7dd5ba84cf5b.png)
![screen6](https://cloud.githubusercontent.com/assets/14166427/10044284/4dcd7812-6202-11e5-8813-fe1f6a6a3ceb.png)

The same issue is in Ukrainian and German versions.
![screen7](https://cloud.githubusercontent.com/assets/14166427/10044285/51a8bc76-6202-11e5-9c6e-a1c300349f5f.png)

So, how can it be solved?

Also, as you can see, `<Colony>Поселения</Colony>` of Misc.xml doesn't change with the change of language. It's given once and forever at the stage of creation of characters. Can this be made dynamic, and, maybe, even change to the name that players give to their colony once they do that?

**Comment by hazestalker** [comment]
Если и искать решение, то тем способом о котором я говорил ранее. Как вариант - можно спросить у разработчиков, что с этим делать. Как мне показалось, некоторые строчки записываются в .dll файлах.
Кстати зачем писать на английском в __ru__ ветке?

**Comment by Dimonasdf** [comment]
Replacer ничего не находит. В dll... не думал об этом. Но это как-то стремненько бы было.
Я думал они заглядывают сюда, лол.

**Comment by Dimonasdf** [comment]
Это одна из нерешаемых проблем, завязанная на коде (или чём-то ещё). Щито поделать.
