### ISSUE TITLE
"Научный стол" или "верстак учёного"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#228]
Нужно сделать везде "верстак учёного" вместо "научного стола".

**Comment by MisterDvojka** [comment]
По моему, научный стол тоже нормально звучит

**Comment by Elevator89** [comment]
"Научный" стол - не совсем корректный вариант.
"Научным" может быть труд, доклад, метод... Но вряд ли стол или стул.
