### ISSUE TITLE
Медицинские и больничные кровати

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#235]
Нужно определиться, что назвать больничной, а что - медицинской кроватью.
Есть кровать, которая назначается для больных, а есть спецкровать, которая открывается после исследования.

**Comment by EcherArt** [comment]
А эта новая кровать что-нибудь делает, даёт какие-либо бонусы? Если да, то её - медицинской, простую - больничной.

**Comment by Elevator89** [comment]
Да, даёт небольшой бонус к лечению.

**Comment by Elevator89** [comment]
> Если да, то её - медицинской, простую - больничной.

Мне вот кажется наоборот. Больничная - особая, та, что устанавливается в больницах. А медицинской можно сделать любую. 
То есть больничная кровать - частный случай медицинской.
