### ISSUE TITLE
Косяк с дымолистом

### ISSUE THREAD

**Issue by MisterDvojka** [Ludeon/RimWorld-ru#246]
![image](https://cloud.githubusercontent.com/assets/22993802/19800922/971a4900-9d2f-11e6-9cfa-1e97b44675a2.png)

**Comment by Elevator89** [comment]
Во как. И как назовём "самокрутку"?

**Comment by Elevator89** [comment]
В [одном старом ишью](https://github.com/Ludeon/RimWorld-ru/issues/42) было обсуждение на эту тему.

**Comment by Elevator89** [comment]
Я не против варианта "Косяк из дымолиста" или ""Косяк с дымолистом""

**Comment by EcherArt** [comment]
Второй вариант предпочтительнее. А косяк - литературное слово? С другой стороны, ничего короче-то и нет.

**Comment by Dimonasdf** [comment]
Предпочтительнее без "косяков".

Не влезает, но прочитать можно. Вот если было бы нельзя - другое дело.

**Comment by Elevator89** [comment]
То, что "самокрутка" не влезает - вот настоящий косяк

**Comment by Elevator89** [comment]
> Не влезает, но прочитать можно. Вот если было бы нельзя - другое дело.

Категорически не согласен. Полстроки не видно там, полстроки нет здесь - в итоге перевод выглядит как говно. Я уже много таких мест нашёл и исправил. 
Таких вещей допускать нельзя.

**Comment by EcherArt** [comment]
Поддерживаю. Плюс там фиг что разглядишь. По крайней мере, с моим зрением.

**Comment by Dimonasdf** [comment]
Если бы это было только тут, можно было бы написать просто "Дымолист", т. к. было бы просто обозначение наркотика, позволенного к употреблению. Но фича в том, что эти места идут из названий конкретных предметов, и про это надо не забыть.

`Дымолист (самокрутка)` по аналогии с психином?

**Comment by Elevator89** [comment]
Ребят, какая "скрутка"? Вообще не гуглится. Ещё хуже, чем "самокрутка".
"Косяк" - самый близкий и правильный перевод слова "joint". Принципиально не вижу в нём ничего плохого. Это уже и не жаргонизм вовсе, а общеупотребительное слово. Вот даже [статья](https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%81%D1%8F%D0%BA_(%D0%BA%D0%BE%D0%BD%D0%BE%D0%BF%D0%BB%D1%8F)) во взрослой и серьёзной Википедии.

**Comment by Dimonasdf** [comment]
Аналогично: Ребят, какой "косяк"?
Я человек свободных взглядов, но даже мне этот вариант кажется перебором.

Не знаю, где они взяли этот синоним, сам первый раз слышу. Мой вариант - сигара. Благо она и в игре здоровая, как питон.

**Comment by Elevator89** [comment]
> даже мне этот вариант кажется перебором.

В каком месте тут перебор?

> Не знаю, где они взяли этот синоним, сам первый раз слышу. 

Какой ещё синоним? "Косяк" - уже давно общеупотребляемое слово, а не сленг наркоманов.

> Мой вариант - сигара.

Сигары делают из табака. У нас же - аналог конопли. Хуже того, дымолист можно спутать и с тем, и с другим: и то, и другое - дымит. Только вот действие... коноплёвое. Не надо вводить игрока в заблуждение.

**Comment by EcherArt** [comment]
Википедия википедией, а косяк и в самом деле не очень вариант. Посмотрите0ка сюда: https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%81%D1%8F%D0%BA
Мало того, что надзание ЖАРГОННОЕ, так и ещё с определённым веществом - МАРИХУАНОЙ.
Раз кое-кто забраковал сигару из=за табака, то и косяк по той же логике должен.
Предлагаю идти не от формы, а от свойства косяка с дымолистом. Например, курительный дымолист, или курит. дымолист для не влезающего.

**Comment by Elevator89** [comment]
Дымолист - это и есть марихуана. Переименованная из каких-то-там соображений корректности. Так что логика продолжает работать. А joint - это косяк, как его ни крути. Такое же жаргонное слово, как и в оригинале.
