### ISSUE TITLE
"Сшить одежду швейной машинкой"

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#247]
![default](https://cloud.githubusercontent.com/assets/22240259/19821707/925bdd8c-9d68-11e6-94bd-6293e7b669c5.png)
Сие моих рук дело, и выглядит оно ужасно, особенно в сочетании с портным.
Вариант исправления: "У портного или НА швейной машинке".

**Comment by Elevator89** [comment]
В игре есть стол портного и есть швейная машинка. Сам портной обычно не прилагается, поэтому "у портного" - не годится.

**Comment by EcherArt** [comment]
за столом портного или на швейной машинке. Но шить машинкой - нет.

**Comment by Elevator89** [comment]
> за столом портного или на швейной машинке

пусть так и будет
