### ISSUE TITLE
Частично переведённый шахматный стол (и другие предметы мебели)

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#248]
Здесь шахматный стол - это шахматный стол.
![default](https://cloud.githubusercontent.com/assets/22240259/19821793/01dcf010-9d69-11e6-8a7e-ef4b68b5d90b.png)
А здесь он - chess table.
![default](https://cloud.githubusercontent.com/assets/22240259/19821815/1905be34-9d69-11e6-8d59-9db09f2c1599.png)
Возможно, там переводить негде или я скачала что-то не то, но на всякий случай пишу - вдруг пропустили.

**Comment by Dimonasdf** [comment]
Это один из непереводимых случаев.

**Comment by Elevator89** [comment]
> Это один из непереводимых случаев.

Я тоже изучал эту проблему. Так и есть. Ишью закрываю.

**Comment by Dimonasdf** [comment]
Лучше бы это собрать где-то, чтобы не создавались подобные ишью.
(Создать ишью со списком ишью, которые не нужно создавать))

Из моего листочка:

1. предыстории
2. "строит chair (постройка)", "уже используется - stove", "несёт сталь для wall (проект)", "сталь стена (постройка)"
3. временной формат: "изготовка - s",	"высота - m", "осадки - mm"

**Comment by Elevator89** [comment]
Для этого есть вики

**Comment by Dimonasdf** [comment]
@Elevator89 пожалуйста.
Моё дело - скинуть инфу.
