### ISSUE TITLE
Заяц женского пола

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#249]
![default](https://cloud.githubusercontent.com/assets/22240259/19822077/552541d6-9d6a-11e6-839f-cff50308bdfb.png)
В принципе ничего страшного нет, особенно если это не применятся к животным. Но увы.
![default](https://cloud.githubusercontent.com/assets/22240259/19822199/f8496950-9d6a-11e6-9f10-348767159fdb.png)
Раз уж мы используем неразрывный пробел, почему бы нам не использовать ♀ и ♂ ? 
https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D1%8B_%D0%B3%D0%B5%D0%BD%D0%B4%D0%B5%D1%80%D0%B0

**Comment by Elevator89** [comment]
А чем не нравится "заяц мужского пола"? Вполне себе биологически корректно, разве нет?

**Comment by EcherArt** [comment]
Заяц мужского пола - самец!
Но к людям это, увы, некорректно применять.

**Comment by Elevator89** [comment]
Для многих животных есть специальная форма для самца или самки, типа "петух" и "курица". Возможно, эту форму можно для всех указывать, но это нужно проверить. 
Если так оно и есть, то проблема решится использованием форм для **всех** животных. Это может быть довольно кропотливым занятием. Плюс, придётся следить за новыми вводимыми в игру видами.

**Comment by EcherArt** [comment]
Я даже готова взять на себя эту кропотливую работу, когда закончу возиться с сессией, она в этом полугодии реально жёсткая =)
А пока нужно что-то придумать, чтобы никто не любовался на зайцев мужского пола. Или нет.
В любом случае ишью лучше не закрывать.

**Comment by Elevator89** [comment]
Если такая форма не указана, то по дефолту вставляется перевод для <male> или <female>.
Проблема в том, что эти <male> или <female> используются и для людей, и ещё в некоторых фразах.

**Comment by Dimonasdf** [comment]
Думается мне, половые варианты уже указаны везде, где можно.
Не могу сказать, что я в восторге от "Женского/Мужского пола", но мне норм. Впрочем меня и "Он/Она" устраивало. Подгоняйте, как нравится, только не чудите чересчур.

**Comment by EcherArt** [comment]
Её-богу, меня почему-то он-она вымораживало меньше. Но это только ИМХО.

**Comment by Elevator89** [comment]
Да ладно! А как вам: `В течение нескольких дней настроение у некоторых людей (он) будет немного хуже`?
Ну, и конечно, `Умиротворение (он)`

**Comment by Dimonasdf** [comment]
Щито поделать.

**Comment by Elevator89** [comment]
> она меня укусила

Слова "male" и "female" в игре не применятются в таком контексте.

**Comment by EcherArt** [comment]
Кхе-кхе, стоит ли начинать работу по ручному заданию прозвищ животинкам?

**Comment by Elevator89** [comment]
Если "мужского пола, заяц", по-твоему, не годится, то исправить это стоит. Но мне кажется, что это не самая приоритетная задача.

**Comment by fiziologus** [comment]
"Полы" легко правятся через _животное_**.lifeStage.**_число_.**labelMale||labelFemale** тег в DefInjected/PawnKindDef/PawnKinds_Animal_* (глобально почему то не подхватываются), но во всплывающих "полы" всё равно останутся.
А новой живности и так *lifeStage* теги придётся создавать.

**Comment by Elevator89** [comment]
Если оно для всех животных одинаково правится, будет здорово.

**Comment by fiziologus** [comment]
Правится для всех одинаково, но с одной "фичей" (в оригинале тоже самое, это баг движка).
![default](https://user-images.githubusercontent.com/25985986/28244967-77c9f496-6a03-11e7-9f40-925b806743f4.png)

**Comment by Elevator89** [comment]
"Самка здоров". Ну да, не очень. Тут надо переделывать "здоров"

**Comment by fiziologus** [comment]
"здоров" от "индивид", к тому же переделать это под род не получится (ограничение движка). Только вводить термин под оба пола.

Фича – это **labelMale||labelFemale**, ушедший в название животного (зайчиха-кабаниха etc также перепрыгнут), и исправить это нельзя: так работает поиск **label** в движке. (а во всплывающих будет каша вида "самка альпака женского пола").

Ещё один, не менее геморный, путь – править сам шаблон, **PawnMainDescGendered** в _Keyed/Misc_Gameplay.xml_ (**0** – gender-тег, **1** – "индивид"), и подсмотреть у других не получится: у чехов – **muz/zena: индивид**, у хохлов – **он/она** _(на мове естественно)_ **индивид**, а у остальных проблем с male/female нет (про азиатов ничего сказать не могу, но шаблон они не правили).

По другому на текущем состоянии движка здесь никак не решить (смотрел код ILSpy-ем).

**Comment by Elevator89** [comment]
Я не понял, что за "баг движка" ты имеешь в виду. В игре есть "свинья", есть "хряк", сделанные в PawnKinds* через labelMale|labelFemale. "Женского пола" и "мужского пола" при этом не подставляются, что логично.
Задача — добавить эти labelMale|labelFemale для всех животных. В чём проблема?

**Comment by fiziologus** [comment]
> В чём проблема?
Нэ красыво местами.

Возможно в будущем эта проблема решится.

> Hey thanks for the info! I'll be sure to add this to our long-term todo list for language support.
> But, be aware, there is still lots of work to do on the game and many languages that act differently so it could be a long time before this gets close to being implemented.
> Thanks
> Ty

(в чём-то прав, я предложил через отдельные теги гендера для животных, но в разных языках по-разному: где слова, а где и суффиксы, наподобие "кабан-кабаниха").

Отрихтую тестовые файлы – закину (можете взять и сами https://github.com/fiziologus/RimWorld-ru/commit/9634d3a9555d840e881353c3d389020dba1cfd5f и https://github.com/fiziologus/RimWorld-ru/commit/a04909f3e9c2e5782b4aa4ab1a2eff7cc4e01fdd).

**Comment by Elevator89** [comment]
Ждём пулреквеста. Только, пожалуйста, без "муйволов".

**Comment by fiziologus** [comment]
> Если "мужского пола, заяц", по-твоему, не годится, то исправить это стоит. Но мне кажется, что это не самая приоритетная задача.

> Возможно в будущем эта проблема решится.

Ждите. На подходе А18 (пока без сроков), если там не появится моя идея по этому поводу, то придётся втыкать "костыль."
