### ISSUE TITLE
Черезвычайно не влезающая комната отдыха

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#261]
Восторженные мысли поселенцев не помещаются в отведённое место на UI. Скрин будет позже.
Нужно провести рефакторинг DefInjected\ThoughtDef\Thoughts_Situation_RoomStats.xml.
Надо определиться с описанием хороших-охренительных комнат (всех, не только отдыха) и сделать их короче примерно 30 символов.

**Comment by Elevator89** [comment]
Думаю, лучше использовать следующие степени охренительности комнат в следующем порядке:
6. Хорошая
7. Очень хорошая
8. Прекрасная
9. Превосходная
10. Восхитительная
11. Чудо света

**Comment by Dimonasdf** [comment]
Восхитительно.
