### ISSUE TITLE
"Разделал человека"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#264]
Нужно сделать фразу пригодной для женских персонажей.

**Comment by Dimonasdf** [comment]
Сначала хотел спросить, "А женщина не человек?" потом понял)


![13683509043939](https://cloud.githubusercontent.com/assets/14166427/20116913/4a15441e-a60f-11e6-94eb-6cc77a0d9897.jpg)

**Comment by Elevator89** [comment]
Поднять женщину, использовать и поговорить )
