### ISSUE TITLE
"мнение моего/моей муж Василич"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#268]
И описание:
"То, что я со своей половинкой, заставляет меня чувствовать себя таким образом". 
Переведено **кошмарно!**
Во-первых, "opinion of smb" в данном случае значит, "мнение о ком-то", а не "мнение кого-то".
Во-вторых, дословный перевод сделал фразу кривой. 
Нужно исправить на один из вариантов:
"Мнение о моём/моей муж <имярек>" 
"Мнение о муж, Василич".
"Отношение к муж, Василич".
Вместо "муж" скрипт в игре может подставить: "жена", "жених", "невеста", "любовник" или "любовница>. Нужно следить за общей длиной, чтобы было не больше 30 символов.
Описание следует исправить тоже. Например, на
"Именно так я себя чувствую рядом со своей половинкой"

**Comment by EcherArt** [comment]
Отношение к: муж, Василич - сойдёт? Если да, то буду коммитить

**Comment by Dimonasdf** [comment]
Я посмотрю завтра этот момент, не совершайте пока резких движений. Или, если кто-то онлайн, киньте сюда исходную фразу, - возможно, она поменялась, и поэтому перевод стал неправильным.

**Comment by Dimonasdf** [comment]
Так-с. У нас есть:

`        <label>opinion of my {0} {1}</label>`
`        <description>Being with my lover makes me feel this way.</description>`

в Thoughts_Situation_Social.xml
Есть:

`  <OpinionOf>Opinion of {0}</OpinionOf>`
`  <SomeonesOpinionOfMe>{0}'s opinion of me</SomeonesOpinionOfMe>`

в ITabs.xml

И работает всё это вот так:

![2](https://cloud.githubusercontent.com/assets/14166427/20267499/1d2e9cf8-aa8c-11e6-9620-ffa7bb76c54e.png)

То есть, @Elevator89 оказался прав) Сорян)

> "Мнение о муж, Василич"

и

> "Именно так я себя чувствую рядом со своей половинкой"

поддерживаю.

**Comment by Elevator89** [comment]
> Отношение к: муж, Василич

Пойдет, только лучше без двоеточия.
Тут вообще, по смыслу больше подходит: "Отношения с муж, Василич". Но по переводу - именно "мнение о" или "отношение к".

**Comment by Elevator89** [comment]
Как оно по механике связано? Есть ли какая-то прямая зависимость от отношений, которые во вкладке "социум"?

**Comment by EcherArt** [comment]
Напрямую, кажется. 
![default](https://cloud.githubusercontent.com/assets/22240259/20371635/381799c4-ac77-11e6-898b-f85a706f282b.png)

**Comment by Elevator89** [comment]
Речь о том, как бонус настроения ("Opinion of my husband Vasilich") связан с отношениями с этим Василичем во вкладке "социум". К какой графе привязан этот бонус и как?
Для того, чтобы это понять и измерить, нужно попробовать изменить отношения жены с Василичем и Василича с женой и посмотреть, как это сказывается на бонусе.
Это нужно для того, чтобы уж совсем окончательно удостовериться в том, в какую именно сторону переводить "Opinion of my husband Vasilich": "моё мнение о Василиче" или "мнение Василича обо мне".

**Comment by Dimonasdf** [comment]
Да, сорри, я не пояснил. На второй половине изображения у жены появился любовник, и поэтому мнение мужа резко упало.

> Как оно по механике связано? Есть ли какая-то прямая зависимость от отношений, которые во вкладке "социум"?

Как мне кажется, зависимость relationship - mood прямая. См: +85 = +9, -45 = -5. Но это лишь додумки, причём бессмысленные.
Главное - у кого именно поменялось отношение после "аферы".

**Comment by Elevator89** [comment]
Да, теперь я уже понял. Отношение к Василичу делится на 10 с округлением в большую сторону, и получаем бонус к настроению для жены Василича.
