### ISSUE TITLE
"Проектирование" и "исследования"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#279]
Эти пункты меню занимают слишком много места. 
Надо не забывать, что мониторы бывают не только FullHD. А ещё бывают моды, которые добавляют в главное меню свои пункты.
Из-за вышеперечисленных причин пункты "проектирование" и "исследования" не влезают в отведённое им место.
![default](https://cloud.githubusercontent.com/assets/21694533/20489221/e024d180-b01a-11e6-88ca-5608104d4d51.jpg)
Предлагается заменить на "Проекты" и "Наука" соответственно. Другие варианты тоже принимаются.

**Comment by Dimonasdf** [comment]
Откровенно говоря, даже если что-то выглядит не так на моём 16:10, я считаю это своей проблемой, а не проблемой разработчика. А уж учитывать мониторы 4:3 в 2016.. Такое себе.
Впрочем, от "Проектов" и "Науки" мы ничего не потеряем, так что можно.

**Comment by Elevator89** [comment]
@Dimonasdf, @EcherArt, @MisterDvojka, Будут альтернативные "науке" и "проектам" предложения?

**Comment by Dimonasdf** [comment]
Можно вернуть вариант "Создать" на место Architect. Наука годится.

**Comment by Elevator89** [comment]
А как насчёт "технологии" вместо "науки"? Не так кратко, а к смыслу ближе

**Comment by Elevator89** [comment]
На 1024х768 смотрится нормально:
![default](https://cloud.githubusercontent.com/assets/21694533/20767310/d1946cac-b74a-11e6-8a63-5f3e7a5d72fb.jpg)
