### ISSUE TITLE
AlcoholAddiction и AlcoholTolerance

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#281]
Оказывается, мы их недоперевели.

**Comment by EcherArt** [comment]
0_0
Блин, надо было сегодня зайти. Сорри. Завтра постараюсь просмотреть.

**Comment by EcherArt** [comment]
Просмотрела, ахаха.
Знаете, что это было? Это была МОЯ первая задача, которую я начала делать до того, как меня пригласили в телеграм. Потом ещё мне сказали, что на эту задачу подписан, собсно, Лёша.
А вот к качеству перевода никаких претензий, перевели лучше, чем я.

**Comment by Elevator89** [comment]
Задача пусть повисит до следующего релиза. Вдруг разрабы исправят свой косяк.
