### ISSUE TITLE
Формы глаголов в WorkGivers

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#283]
В данный момент этот фал содержит группы строки вида:
```
  <HaulCorpses.label>переносить трупы</HaulCorpses.label>
  <HaulCorpses.gerund>Перенести</HaulCorpses.gerund>
  <HaulCorpses.verb>перенести</HaulCorpses.verb>
```
и
```
  <DoBillsHaulCampfire.label>сжигать на костре</DoBillsHaulCampfire.label>
  <DoBillsHaulCampfire.gerund>Сжигать</DoBillsHaulCampfire.gerund>
  <DoBillsHaulCampfire.verb>сжигать</DoBillsHaulCampfire.verb>
```
Требуется понять, для чего и в каких контекстах используются label, gerund и verb. После чего определиться с формами глаголов (совершенная или несовершенная) и отрефакторить этот файл.

**Comment by Dimonasdf** [comment]
**Label** 
Если во вкладке "Работа" подержать над каждым занятием мышь - появится описание. Например:

![1](https://cloud.githubusercontent.com/assets/14166427/20634691/912e6922-b364-11e6-80d3-fb09caf31a5c.png)

label в WorkGivers.xml из этого - "Тушить пожары". Это действия, за которые отвечает данная галочка/приоритет. Так что тут должно быть простое описание действия, что поселенец будет делать, если назначить его на эту работу.

![4](https://cloud.githubusercontent.com/assets/14166427/20635186/cc905a74-b36a-11e6-8582-13f0805abe7e.png)

Предположительно, в несовершенном виде.

> "Пожарный", "тушить пожар" и "Пожарные тушат огонь в поселении." тут из WorkTypes.xml Это отдельная история, но пока наблюдения такие:
> 
> "тушить пожар" - gerundLabel - это то, что употребляется в "никогда не будет".
> Так, например, в коде:
> `<Crafting.labelShort>Ремесло</Crafting.labelShort>`
> `<Crafting.pawnLabel>Ремесленник</Crafting.pawnLabel>`
> `<Crafting.gerundLabel>Ремесло</Crafting.gerundLabel>`
> если исправить gerund label на, скажем, "крафтить", и получится: "Невозможно выполнить: никогда не будет крафтить".
> Однако если перенадмозговать, то получится:
> 
> ![2](https://cloud.githubusercontent.com/assets/14166427/20634929/40f7040c-b367-11e6-88f2-3368cf11f8f4.png)
> 
> ![3](https://cloud.githubusercontent.com/assets/14166427/20635004/41bc8f0a-b368-11e6-81ba-24a69f834833.png)
> 
> Вот так.



_____

**Gerund** - всё просто, это входная фраза для приказа.
То, что в оригинале "Prioritize getting bed rest in", у нас "Отдохнуть в". Потому и заглавная буква, опять же. Ну про это вы знаете уже.

Предположительно не нуждаются в исправлении.
_____

**Verb** 
Судя по всему используется в весьма специфичном случае - `<CannotGenericWork>Невозможно {0} {1}</CannotGenericWork>`.


В тексте есть опечатка: "закалоть", которая и помогла найти это. См.:
У прирученного животного есть иконка. Она "Заколоть".
Если её нажать, а потом дать приказ поселенцу, там будет "Заколоть Рози".
Действие будет "Закалывает Рози".
Но если выбрать 'ненасильника', будет "Невозможно закалоть Рози (неспособен к насилию)"

То есть должны быть формы, подходящие под формулировку "Невозможно (с)делать". Вид зависит от действия.

**Comment by Elevator89** [comment]
Перлы "закалоть" и "искусством" исправил и залил в мастер

**Comment by Elevator89** [comment]
Для чего нужны .verb и .pawnlabel в WorkTypes.xml?
