### ISSUE TITLE
"Социальная энергия"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#286]
Встречается при описании события вечеринки.
Бывает энергия кинетическая, потенциальная, а бывает - "социальная" ). 
Нужно исправить на что-то более подходящее или переперевести всю фразу.

**Comment by fiziologus** [comment]
А бывает и социальная.
[https://vocabulary.ru/termin/socialnaja-energija.html](url)

**Comment by Elevator89** [comment]
> А бывает и социальная.

Ну и хрен с ней тогда.
