### ISSUE TITLE
Дебошир-драчун

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#295]
Нужно решить, что каким из этих слов описывать любителя рукопашной.

**Comment by EcherArt** [comment]
Я за драчуна

**Comment by Elevator89** [comment]
Тогда нужно найти все вхождения "дебошира" и исправить на "драчуна"

**Comment by Elevator89** [comment]
Ещё лучше найти все вхождения слова "brawler" в оригинале, и в соответствующих местах перевода использовать "драчуна".

**Comment by Dimonasdf** [comment]
А я не за драчуна :/

**Comment by Elevator89** [comment]
Приводи аргументы. Цель - прийти к согласию и использовать выбранный термин везде.

**Comment by Dimonasdf** [comment]
Отстой. Ничего лучше вашего "драчуна" не нашлось. Ладно, пусть так, что поделать.

**Comment by EcherArt** [comment]
@Dimonasdf , ты опять начинаешь? Не нашлось лучше НАШЕГО драчуна, если ты считаешь себя частью команды. Либо придумывай варианты конструктивные, либо успокойся.

**Comment by Dimonasdf** [comment]
Не понял наезда. Я добросовестно потратил час времени на поиск информации и пришёл к выводу, что вариант, к которому вы склонялись, действительно оптимальный, хоть мне и не нравится само слово.
Не стоит при мне говорить "ты опять начинаешь", потому что любые проблемы начинались не с меня, а с вот таких вот фразочек. Не кидай камней в других, и не получишь сам. Договорились?

**Comment by EcherArt** [comment]
Тогда не стоит добавлять оценочные комментарии вроде "отстой". ИМХО, сначала нужно находить замену, а потом уже говорить, что предложенный вариант не подходит.

**Comment by Elevator89** [comment]
Как я понимаю, к согласию все пришли.

**Comment by EcherArt** [comment]
Я ядовитый взрыв с осадками сейчас делаю
