### ISSUE TITLE
Невозможно плавить электроплавильня

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#296]
Электроплавильню нужно использовать, чтобы плавить всякий лом. Саму её не нужно плавить!

**Comment by EcherArt** [comment]
Хммм, предполагаю, что если нужно изменить "электроплавильня" -> "на электроплавильне". А глагол не трогать.

**Comment by Elevator89** [comment]
Связываю с задачей #283. Пулреквест по ней - #300. В той задаче сделано: "Плавить в электроплавильня"

**Comment by Elevator89** [comment]
Если нет возражений против такого перевода, то ишью предлагается к закрытию.

**Comment by Elevator89** [comment]
Прошу всех заинтересованных: @EcherArt, @Dimonasdf, @Bobsans - найти примеры неудачных предложений, связанных с работой за станком.

**Comment by Elevator89** [comment]
Неактуально за истечением срока давности
