### ISSUE TITLE
"личико, что притягивает"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#298]
"У NAME красивое личико, что притягивает к нHIM людей". "Что" воспринимается в значении "которое". Это неверно. Лучше: "У NAME красивое личико. Это притягивает к нHIM людей".

**Comment by Dimonasdf** [comment]
> У Jon красивое личико, что притягивает к нему людей.

Факт того, что у него красивое личико и притягивает.

Немного натянутый "баг", но как хочешь.

**Comment by Elevator89** [comment]
> Факт того, что у него красивое личико и притягивает.

Да. Но лучше, чтобы это было понятно без дополнительных разъяснений и вопросов (хотя бы самому себе).
Баг может и не такой серьёзный, но таких "вшей" в переводе много. Они в сумме наш перевод обесценивают.

**Comment by fiziologus** [comment]
_NAME has a pretty face, which predisposes people to like HIM_

У NAME привлекательная _(миловидная, прелестная)_, располагающая к себе мордашка _(личико, лицо)_.

**Comment by Elevator89** [comment]
> располагающая к себе модрашка

Круче только "внушающий уважение ковёр" (это реальная фраза, которая была раньше в переводе). 
Мордашка — это не личность, она не может располагать _к себе_.

Можно просто:
"У NAME миловидное личико, вызывающее симпатию у людей."

**Comment by fiziologus** [comment]
> Мордашка — это не личность, она не может располагать к себе

> ....Подходя к очередному дому – даже если Винсент был знаком с живущим в нём,– он выталкивал вперёд молодого друга. Приятная наружность и **располагающие к себе манеры** Раппарда помогали найти желающих попозировать практически повсюду....

 Грегори Уайт-Смит, Стивен Найфи. "Ван Гог. Жизнь."

Манеры как бы тоже не личность.
_Apropos, "располагать к себе" ближе к "притягивать"/"привязывать", чем к "вызывать симпатию" (синонимы обычно указывают в порядке соответствия, начиная с наиболее близкого по значению)._

**Comment by Elevator89** [comment]
> Грегори Уайт-Смит, Стивен Найфи. "Ван Гог. Жизнь."

Что поделать, не мы одни криво переводим.

**Comment by Elevator89** [comment]
Реквест смержен, а ишью висит. Непорядок.
