### ISSUE TITLE
Гул, умироворение и гендер

### ISSUE THREAD

**Issue by EcherArt** [Ludeon/RimWorld-ru#304]
Что видно: Гул (женского/мужского пола)
Что в коде: "{0} ({1})" ОНО НЕ ИЗМЕНЯЕТСЯ!
И ещё у гула есть свой собственный пол, да.
Что надо: гул, воздействует на лиц (женского/мужского пола) | или прямее.
Возможно, имеет смысл использовать костыль от "умиротворения".

**Comment by Bobsans** [comment]
может гул и умиротворение заменить на волны? раздражающие волны и успокаивающие волны. или излучение.

**Comment by Elevator89** [comment]
https://ludeon.com/forums/index.php?topic=30182.0

**Comment by Elevator89** [comment]
Сейчас это выглядит как "гул (♂)". Лучше и понятнее, чем было. 
Будут обновления - переоткрою ишью или создам новое
