### ISSUE TITLE
ThoughtDef: Thoughts_Exotic-Thoughts_Memory_Misc

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#317]
Просмотреть и обновить перевод в обозначенных файлах.
Отличия по сравнению с немецким переводом:

```
File: /ThoughtDef/Thoughts_Memory_Death.xml:
	4 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
		KnowGuestExecuted.stages.3.description
		KnowColonistExecuted.stages.3.description
		KnowGuestExecuted.stages.3.label
		KnowColonistExecuted.stages.3.label
File: /ThoughtDef/Thoughts_Memory_Eating.xml:
	2 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
		AteKibble.stages.0.label
		AteKibble.stages.0.description
File: /ThoughtDef/Thoughts_Memory_Misc.xml:
	12 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
		BondedAnimalAbandoned.stages.0.description
		PrisonerAbandonedToDie.stages.0.description
		DefeatedMajorEnemy.stages.0.label
		ColonistAbandonedToDie.stages.0.label
		ColonistAbandoned.stages.0.label
		DefeatedHostileFactionLeader.stages.0.description
		ColonistAbandoned.stages.0.description
		ColonistAbandonedToDie.stages.0.description
		PrisonerAbandonedToDie.stages.0.label
		DefeatedHostileFactionLeader.stages.0.label
		BondedAnimalAbandoned.stages.0.label
		DefeatedMajorEnemy.stages.0.description
	2 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/RussianTranslation/DefInjected: 
		WitnessedDeathFamily.stages.0.label
		WitnessedDeathFamily.stages.0.description
```

Вывод скрипта Квиета: [ThoughtDef.zip](https://github.com/Ludeon/RimWorld-ru/files/647495/ThoughtDef.zip)

Отличия оригинальных дефов новой версии - в гитовом ропозитории: [Defs.zip](https://github.com/Ludeon/RimWorld-ru/files/647365/Defs.zip)

Выдержка из логов игры:
[output_log defs.txt](https://github.com/Ludeon/RimWorld-ru/files/647538/output_log.defs.txt)

**Comment by Dimonasdf** [comment]
Было задание:

> Обновить файлы:
> Thoughts_Exotic
> Thoughts_Memory_Death
> Thoughts_Memory_Debug
> Thoughts_Memory_Eating
> Thoughts_Memory_Gatherings
> Thoughts_Memory_Misc

(Проигнорирован Thoughts_Memory_RoomStats)

Новое задание:

> Обновить файлы:
> Thoughts_Exotic
> Thoughts_Memory_Debug
> Thoughts_Memory_Eating
> Thoughts_Memory_Gatherings
> Thoughts_Random
> Thoughts_Situation_Social
> Thoughts_Situation_Special

Инфографика:

![default](https://cloud.githubusercontent.com/assets/14166427/21521172/89c44cc2-cd0b-11e6-9361-1bea0221589a.png)
