### ISSUE TITLE
ThoughtDef: Thoughts_Memory_Social-Thoughts_Situation_General

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#318]
Просмотреть и обновить перевод в обозначенных файлах.
Отличия по сравнению с немецким переводом:

```
9 files only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
	/ThoughtDef/Thoughts_Memory_RoomStats.xml

File: /ThoughtDef/Thoughts_Situation_Drugs.xml:
	8 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
		SmokeleafHigh.description
		SmokeleafHigh.label
		YayoHigh.label
		AlcoholWithdrawal.stages.1.label
		FlakeHigh.description
		AlcoholWithdrawal.stages.1.description
		YayoHigh.description
		FlakeHigh.label
	6 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/RussianTranslation/DefInjected: 
		FlakeHigh.stages.0.label
		SmokeleafHigh.stages.0.label
		YayoHigh.stages.0.description
		YayoHigh.stages.0.label
		FlakeHigh.stages.0.description
		SmokeleafHigh.stages.0.description
File: /ThoughtDef/Thoughts_Situation_General.xml:
	8 tags only in E:/Steam/steamapps/common/RimWorld/Mods/Core/Languages/German-git/DefInjected: 
		DeadMansApparel.stages.2.label
		DeadMansApparel.stages.3.description
		DeadMansApparel.stages.3.label
		DeadMansApparel.stages.0.label
		DeadMansApparel.stages.1.description
		DeadMansApparel.stages.0.description
		DeadMansApparel.stages.2.description
		DeadMansApparel.stages.1.label
```

Вывод скрипта Квиета: [ThoughtDef.zip](https://github.com/Ludeon/RimWorld-ru/files/647495/ThoughtDef.zip)

Отличия оригинальных дефов новой версии - в гитовом ропозитории: [Defs.zip](https://github.com/Ludeon/RimWorld-ru/files/647365/Defs.zip)

Выдержка из логов игры:
[output_log defs.txt](https://github.com/Ludeon/RimWorld-ru/files/647538/output_log.defs.txt)

**Comment by Dimonasdf** [comment]
Было задание:

(Проигнорирован Thoughts_Memory_RoomStats)

> Обновить файлы:
> Thoughts_Memory_Social
> Thoughts_Random
> Thoughts_Situation_Drugs
> Thoughts_Situation_General

Новое задание:

> Обновить файлы:
> Thoughts_Memory_Death
> Thoughts_Situation_Drugs
> Thoughts_Situation_General
> Thoughts_Situation_Traits
> Thoughts_Situation_TraitsPerm

Инфографика:

![default](https://cloud.githubusercontent.com/assets/14166427/21521172/89c44cc2-cd0b-11e6-9361-1bea0221589a.png)
