### ISSUE TITLE
Backstories

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#322]
Очень большая задача. Пока неясно, откуда брать исходный текст.

Выдержки из логов про отсутствующие бэкстори: [missing backstories.txt](https://github.com/Ludeon/RimWorld-ru/files/647609/missing.backstories.txt)

**Comment by Dimonasdf** [comment]
https://github.com/jnkyacc/Backstories/tree/development/Backstories

**Comment by Dimonasdf** [comment]
А, ну, собственно, там всё вытащено.
Кроме, разве что, MiscPirateNames.xml, где:

```
<PlayerCreatedBios>
	<PawnBio>
		<Name>
			<First>Arnold</First>
			<Last>Vimmer</Last>
			<Nick>Vim</Nick>
		</Name>
		<Gender>Male</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Alice</First>
			<Last>Lamond</Last>
			<Nick>Alli</Nick>
		</Name>
		<Gender>Female</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Mally</First>
			<Last>McJane</Last>
			<Nick>Mal</Nick>
		</Name>
		<Gender>Either</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Michael</First>
			<Last>Vomus</Last>
			<Nick>Mike</Nick>
		</Name>
		<Gender>Male</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Jennifer</First>
			<Last>Luden</Last>
			<Nick>Jen</Nick>
		</Name>
		<Gender>Female</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Jonathan</First>
			<Last>Singer</Last>
			<Nick>Jon</Nick>
		</Name>
		<Gender>Male</Gender>
	</PawnBio>
	<PawnBio>
		<Name>
			<First>Collins</First>
			<Last>Barrow</Last>
			<Nick>Barrow</Nick>
		</Name>
		<Gender>Male</Gender>
	</PawnBio>


</PlayerCreatedBios>
```

И вот этих файлов, в которых много имён.

![default](https://cloud.githubusercontent.com/assets/14166427/21138319/8c0f05ea-c13e-11e6-9fd6-aaad6b4f778d.PNG)

**Comment by EcherArt** [comment]
Никто ж не против, если я займусь?

**Comment by Elevator89** [comment]
Я бы это напоследок оставил, когда хотя бы основную часть остального переведём.

**Comment by Elevator89** [comment]
Работы тут дофига: 440 записей. Если начнёшь, то закончишь очень не скоро.

**Comment by EcherArt** [comment]
Я планирую работать параллельно над 2мя ветками, над этой и той, что надо закончить. 440 записей на самом деле не то чтобы много (для меня).

**Comment by Dimonasdf** [comment]
Пожалуйста:
https://github.com/Dimonasdf/RimWorld-ru/tree/backstories-initial/Backstories

**Comment by Elevator89** [comment]
Залил в основной репозиторий:
https://github.com/Ludeon/RimWorld-ru/tree/backstories-initial

**Comment by Dimonasdf** [comment]
@Elevator89 обнови ветку. #384.

**Comment by Elevator89** [comment]
Будет разбито на ишью
