### ISSUE TITLE
#Offtop

### ISSUE THREAD

**Issue by Tibalbo** [Ludeon/RimWorld-ru#324]
Я просто хотел узнать, вы будете делать перевод на А15 или А16?! P.s есть нестабильная версия А16

**Comment by Dimonasdf** [comment]
@Tibalbo Если обратить внимание на 19 предыдущих заданий, можно заметить, что что-то явно происходит по поводу а16.

**Comment by Elevator89** [comment]
@Tibalbo, на 0.15 перевод готов уже пару месяцев как, и лежит в этом репозитории. То, что разрабы его в игру не включали, вина исключительно разрабов.
А так, качайте, устанавливайте, наслаждайтесь.

**Comment by Tibalbo** [comment]
Спасибо за ответ и спасибо за то, что делаете качественный перевод на эту игру.

**Comment by Elevator89** [comment]
Пожалуйста ). Если есть желание помочь и нет проблем с английским - милости просим.
