### ISSUE TITLE
"Живые" переводчики

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#35]
Т.к. над переводом работает много людей и не всегда понятно кто есть "живой" в группе, предлагаю добавить текстовый файл (или может на гите есть какой-то способ получше это сделать) в который еженедельно (или хотя бы ежемесячно) будут записываться текущие переводчики.

Пример:
Translators.txt

22.08.2016-28.08.2016
1. Вася
2. Петя
3. Федор
...

Чтобы всегда было понятно кто работает над переводом в данный момент, кооперироваться и организовываться. Если предложение не встретит жесткой критики - добавлю файл в начале следующей недели.

**Comment by Ohar** [comment]
Это неплохо видно на диаграмме [Network](https://github.com/Ludeon/RimWorld-ru/network)

**Comment by Dimonasdf** [comment]
:)

Я всегда жив, но иногда молчу за ненадобностью.

**Comment by Dinoabunai** [comment]
Но не видно например, если человек переводит у себя на локальном ПК.

**Comment by Dinoabunai** [comment]
Например я работаю над папкой Drugs, кто-то тоже может над ней работать в это время. В итоге мы узнаем это только когда запулим изменения. Получается что несколько человек работают впустую.

**Comment by Ohar** [comment]
> Но не видно например, если человек переводит у себя на локальном ПК.

Если человек работает в нарушение принятых правил работы в команде — то да, не видно. 
Если же он работает в своём форке и пушит (отправляет) все коммиты на гитхаб, то всё очень даже видно.

**Comment by Dinoabunai** [comment]
> Если человек работает в нарушение принятых правил работы в команде 

Есть регламент?

> Есть желание организовать процесс?

Есть огромное желание. Я поэтому и сделал эту ветку поначалу. Т.к. прежде чем организовать работу хорошо было бы понять сколько вообще людей у нас на данный момент.
Получается что в последнее время над переводом работают Ohar, dragomano, Dimonasdf, Dinoabunai,

Есть кто еще живой? Откликнитесь пожалуйста.

**Comment by Ohar** [comment]
> Есть регламент?

Вот [неплохое описание рабочего процесса](http://ruseller.com/lessons.php?rub=28&id=2207). Всё непонятное (автор часто забирается в дебри), вполне можно пропустить.

**Comment by Dinoabunai** [comment]
Почитаю.

**Comment by Dinoabunai** [comment]
Вот dankan0880 еще в работе, а не отображается. Добавил его в пост выше.

**Comment by Dinoabunai** [comment]
> Вот неплохое описание рабочего процесса. Всё непонятное (автор часто забирается в дебри), вполне можно пропустить.

Согласно этому описанию у нас тут вообще все плохо :)

**Comment by Dinoabunai** [comment]
KviEt добавлен в пост выше.

**Comment by Dinoabunai** [comment]
@Elevator89 
Возможно данная тема потеряла свою актуальность. Лучше сделать приветственную тему для новичков и пусть они отписываются туда, если только что присоединились. И указать это на вики (или в ридми).

**Comment by Ohar** [comment]
@Dinoabunai 
А зачем вообще этот бюрократизм? 
Если человек делает правки — это и так все увидят. 
Если не делает — зачем про него знать?

**Comment by Elevator89** [comment]
Согласен с @Ohar. Тему закрываю.
