### ISSUE TITLE
Инструкция для переводчиков

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#36]
Предлагаю сделать детальную инструкцию для новых переводчиков, чтобы они могли сразу приступить к работе. Т.к. я сам пока слабо представляю себе как должен выглядеть процесс и очень много времени уходит на то чтобы понять чего-куда.

Для примера как я вижу процесс на данный момент:
1. Сравниваешь директории в **~\Mods\Core\Defs** 
c директориями в **~\Mods\Core\Languages\Russian\DefInjected**

2. Если какой-то директории нет в **~\Mods\Core\Languages\Russian\DefInjected**, то создаешь ее и переводишь все файлы в директории.

3. Для перевода открываешь оригинальный английский файл и ищешь:
```
<defName>Banana</defName>
<label>banana</label>
 <description>It's a bababa!</description>
```

в файле с переводом пишешь
```
<Banana.label>банан</Banana.label>
<Banana.description>Это банан!</Banana.description>
```

Что-то в таком духе по пунктам. Или уже есть такой ресурс?
Добавить его к вики.

**Comment by Dimonasdf** [comment]
Есть уже в вики, прямым текстом. Также, там описаны все сложности, с которыми столкнулся лично я.

> Источник (Mods\Core\Defs):
> 
```
> <defName>AridShrubland</defName>
>   <label>arid shrubland</label>
>   <description>A dry region, but not dry enough to become a true desert...</description>
```
> Результат (Mods\Core\Languages\RimWorld-ru\DefInjected):
> 
```
> <AridShrubland.label>кустарниковые степи</AridShrubland.label>
> <AridShrubland.description>Сухой регион, но не настолько...</AridShrubland.description>
```
> Содержание defName - то, что пишется перед точкой.
> 
> label и description - то, что пишется после точки, и чьё содержание переводится.

Если что-то, что ещё проще этого, придётся объяснять по пунктам, может, не нужны нам такие переводчики?

**Comment by Dinoabunai** [comment]
Нет эта инструкция как раз хорошая, я больше по тому как искать что перевести.
Особенно где искать и переводить ключи?

**Comment by Dimonasdf** [comment]
А вот как искать, что перевести, это уже немножко магия.
Но часто видно, что нуждается в переводе. Да и всегда можно заглянуть в другие языки.

Что такое ключи?

**Comment by Dinoabunai** [comment]
То что в папке "Keyed"

Как писал Тайнан на форуме Ludeon в инструкции для переводчиков:

> However, the are actually two kinds of translation in RimWorld: Keyed and DefInjected.

> Keyed translations are used by the game with their "key". e.g. the game wants to show the game-over message, so it looks up the string with the key "GameOverMessage" in the currently-selected language and displays that.

То есть слова замену которым игра ищет по ключу.

**Comment by Dimonasdf** [comment]
Так они же и идут из папки Keyed. Там вообще всё просто и по порядку. Даже форматировать не надо.

**Comment by Dinoabunai** [comment]
А для новых ключей? А дефолтной папке же вообще нет \Keyed?

**Comment by Dinoabunai** [comment]
Например до сих пор в главном меню висит Load game на английском.
Хотя в ~Mods\Core\Languages\Russian\Keyed\Menus_Main.xml и красуется строчка:
`<Load>Загрузить</Load>`

**Comment by Dinoabunai** [comment]
Кстати по совету решил заглянут в немецкую директорию - у них там:
`<LoadGame>Spiel laden</LoadGame>`

Но нельзя же просто надеяться что у кого-то другого будет. Есть же какая-то логика касательно того как игра запрашивает ключи.

**Comment by Dimonasdf** [comment]
У меня "Загрузить игру" написано. И "Загрузить" тоже есть. Это два разных места. И всё работает =/

**Comment by Dinoabunai** [comment]
Да, верно, в стим-версии старый файл.
Но например в новой 0.15 есть пункт в главном меню "Learn to play". Как понять какой это ключ и куда его надо добавить?

Вопрос того как понять в вакууме что и где должно быть остается открытым.

**Comment by Dimonasdf** [comment]
Мне бы рабочую тестовую сборочку, я бы глянул. У меня вообще ещё 1241 стоит.
Но суть в том, что в ~\RimWorld\Mods\Core\Languages\English\Keyed всё должно быть.

**Comment by Dinoabunai** [comment]
Вот!!! Отлично! Спасибо!
Просто английский DefInjected хранятся в ~\Mods\Core\Defs.
Т.е. не в ~\Mods\Core\Languages\English\DefInjected
А Keyed там и правда годная.

**Comment by Dinoabunai** [comment]
Тем не менее хотелось бы потратить меньше двух дней на выяснение этого вопроса.
Будут еще новые переводчики. Они тоже могут запутаться.
Можно это добавить в вики?
