### ISSUE TITLE
RaidStrategies

### ISSUE THREAD

**Issue by dragomano** [Ludeon/RimWorld-ru#372]
Подробности с 35 секунды в видео: https://gaming.youtube.com/watch?v=XutA8XJVDn4&feature=share&t=35

Считаю, что русский язык позволяет подобрать кучу синонимов, даже если в оригинале используется одно и то же слово. Зато нашим понятней будет :)

**Comment by Elevator89** [comment]
"Локализатор профилонил" - это конечно сильно )!
То, что переводчик что-то мог сделать намеренно, такой вариант видимо совсем не рассматривается.

> Считаю, что русский язык позволяет подобрать кучу синонимов, даже если в оригинале используется одно и то же слово.

Русский язык, конечно же, позволяет так делать. Как, впрочем, и английский, и немецкий. Но и там, и там везде поставлено одно и то же слово. Мне кажется, это было сделано умышленно.
Поэтому считаю логичным так же сделать для русского перевода.

@Dimonasdf, @EcherArt, что думаете?

**Comment by Elevator89** [comment]
Вспомнил, почему было решено сделать так, как было сделано.
Обозначать разными синонимами что-то, что имеет различный смысл - очень плохая практика. Если отбросить детали игровой механики и рассмотреть отдельно сами слова, то возникает ряд вопросов:
1. Чем именно "налёт" отличается от "атаки"? Разве налёт не подразумевает собой атаку?
2. В каком месте слова "атака" заключен смысл ожидания в сторонке перед непосредственно нападением на поселение?
3. В чём именно заключается "[диверсия](https://ru.wikipedia.org/wiki/%D0%94%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F)", если целью врагов явно не является скрытное нападение и выведение из строя каких-то критически важных моих строений. Тем более, при отсутствии стен враги прут как обычно, и вообще никакой разницы не видно!

Поскольку не вводящие игрока в заблуждение и при этом точные заголовки писем придумать не представлялось возможности, было решено объединить все эти виды нападений одним словом "налёт". Как это и было сделано в оригинале и всех переводах, которые мы успели просмотреть на этот предмет.

**Comment by Dimonasdf** [comment]
@Elevator89 отчётливо помню, что при работе над каким-то моментом ты сказал: "Ни в одной стране мира не будут знать, что это вещь А, а это вещь Б, так почему у нас они должны быть разделены?" Если это не про данное конкретное место, значит всплывёт где-то ещё потом.

     А если по сути, то этот человек, конечно же, не прав, ибо "профилонить" подразумевает упущение из внимания какой-либо части работы. А если что-то было изменено, то это априори предполагает, что кто-то всё же над предметом подумал и принял по нему определённое решение. Говоря: 
>А дальше нам следует его открыть и почитать, какого типа именно это налёт...

автор сам отвечает на свой вопрос. Каждый из этих текстов написан и переведён не просто так, а чтобы его открыли и почитали. И если это может вызывать проблемы у того, кто уже давно играет в игру и привык щёлкать по письмам не глядя, то у новичка даже вопросов никаких не возникнет, так как для него всё будет логичным и понятным, ибо он просто прочитает и узнает, что игра хочет ему сообщить.
     Я понимаю субъективный дискомфорт автора, но жизнь штука такая, всё меняется. Ты можешь бомбить от ченджлога 7.00 Доты, где на 4 часа чтива, но это не изменит того, что игра теперь работает именно таким образом и никак иначе.
