### ISSUE TITLE
Лор в директории игры

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#38]
Пробежался по директориям с локализацией. Только в русской папке лежит лор (папка "Вселенная RimWorld". Это ОК? В смысле разработчики не против что мы "светим" лор? И стоит ли включать папку в релиз? Из всех 26 языков лор лежит только у нас.

**Comment by Dinoabunai** [comment]
@TynanSylvester 
Hi, Tynan. I have a question. We have folder, containing game lore, which is actually translated version of:
https://docs.google.com/document/d/1pIZyKif0bFbBWten4drrm7kfSSfvBoJPgG9-ywfN8j8/pub
and
https://docs.google.com/document/d/1fUO3KKbAbTxMP1lqphnnodY0NPoOVblCUkDw-54MDUc/pub

And it is in Steam release. Is it OK to you, or should we remove it?

**Comment by Dimonasdf** [comment]
Ну, люди спрашивали, есть ли перевод, я добавил, кое-что перевёл, в чём проблема?

**Comment by Dinoabunai** [comment]
Некоторые разработчики скрывают лор, чтобы игроки раскрывали его сами по частям. Плюс я не против самого перевода, но он попадает в релиз. Если разработчики не планировали добавлять лор в релиз, то его там не должно быть.

**Comment by Dinoabunai** [comment]
@Elevator89 
Ты что думаешь?

**Comment by Elevator89** [comment]
Думаю, что пока стоит заняться переводом. А про лор пусть разработчики сначала ответят.

**Comment by Dinoabunai** [comment]
@Elevator89 
Я думаю что они не ответят. Только если письмо послать.
