### ISSUE TITLE
Где найти файл с описанием биографии поселенца?

### ISSUE THREAD

**Issue by Odrixen** [Ludeon/RimWorld-ru#382]
Не могу найти файл с описанием биографии поселенцев.
  При создании персонажа в биографии есть два пункта: Детство и Зрелость(Например **Детство**: Vengeful Child,  **Зрелость** : Digger с _кратким описанием_) Неоднократно делал поиск по ключевым словам, но к сожалению не смог найти. **Подскажите где искать?**

**Comment by Dimonasdf** [comment]
Тебе нужна ветка [backstories-initial](https://github.com/Ludeon/RimWorld-ru/tree/backstories-initial), там новая папка и один файл.
За это пока никто не брался почти, в скором времени дойдём, надо верить. Часть на корейском, это нормально, если понадобятся эти части тоже, я скажу, где искать.

**Comment by Bobsans** [comment]
полная версия файла на английском есть в ветке alpha-16-full-translated.

**Comment by Dimonasdf** [comment]
@Odrixen Вот этот вариант из моего форка сейчас наиболее продвинутый.
https://github.com/Dimonasdf/RimWorld-ru/tree/backstories-initial/Backstories
