### ISSUE TITLE
Предложения по организации рабочего процесса

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#41]
Как бы страшно это не звучало, думаю пора бы задуматься над этим.

Прежде всего я выделил основные рабочие процессы, которые циклично повторяются:
1. Поиск мест, требующих перевода.
2. Распределение нагрузки.
3. Непосредственный перевод.
4. Редактирование и внесение изменений в репозиторий.
5. Тестирование.
6. Релиз.
7. Обратная связь.

Теперь поподробнее по каждому пункту:

1. Поиск мест, требующих перевода.
Думаю тут все понятно. Чтобы перевести что-то нужно сначала найти это что-то.
Особенно это важно при новом релизе игры, когда разработчики добавляют новый контент, который явно должен быть переведен. Следует выработать стратегию и методику поиска таких мест, так как механика локализации не раскрыта и коварные не переведенные файлы или, хуже того, части файлов могут находиться где-угодно.

2. Распределение нагрузки.
Когда объем работ будет ясен, можно распределить нагрузку между переводчиками, чтобы не было ситуаций когда несколько человек работают над одним файлом или переводом. Чтобы всем досталось приблизительно поровну работы, следовательно перевод будет закончен раньше.

3. Непосредственный перевод.
Переводим, приводим файлы в пригодный формат и все что касается перевода напрямую.
По этому пункту можно, разве что принять единый формат комментариев в тексте.

4. Когда переводчик закончил свою работу и протестировал изменения локально, он делает пулл-реквест. После чего его материал редактируется - т.е. комментируется, люди предлагают правки, исправления, свои идеи. Исходя из обсуждения, либо все редакторы согласны с изменениями и пулл мерджится, либо пулл закрывается на доработку.
Касательно этого пункта нужно много чего решить. Формат коммитов, механизм совместных пуллов, медотику рецензирования. Так же следует решить будет ли редактор и ответственный за изменения(человек который уполномочен мерджить) одним и тем же лицом.

5. Тестирование.
Когда все необходимые изменения внесены в проект, участники тестируют его и находят ошибки, баги, недочеты и исправляют их.

6. Релиз.
Если игра стабильно работает и нет других неприятных ошибок, можно сливать ветку разработки с master веткой. Оттуда уже разработчики будут добавлять перевод в официальный релиз.

7. Обратная связь.
Получение обратной связи (часто в форме необоснованной ругани) от игроков. Ответы на их вопросы и правка ошибок, которые все-таки попали в релиз.

**Comment by Dinoabunai** [comment]
**1. Поиск мест, требующих перевода.**
По первому пункту вижу пока 2 надежных решения.
Это просмотр дебаггера в игре и поиск ручками.
Вывод дебаггера логируется в ~\RimWorld\RimWorldWin_Data\output_log.txt что удобно.

**Comment by Dinoabunai** [comment]
Пока у нас "кто во что горазд" :)
Предлагаю работать по приведенной выше схеме начиная с 0.16 релиза.
Т.е. как 0.16.xxxx попадет в unstable, тогда создадим новый бранч и отработаем по пунктам.
А пока будем "дикими" переводчиками.

**Comment by Elevator89** [comment]
Всё отражено в вики. Закрываю ишью.
