### ISSUE TITLE
Рост карциномы

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#416]
![image](https://cloud.githubusercontent.com/assets/14166427/22698575/f8924a30-ed65-11e6-9e50-1fd1a50b161a.png)

Строки 402-405 в Keyed/Misc_Gameplay.xml
```
	<!-- Hediffs growth modes -->
	<DiseaseGrowthModeChanged_Growing>{0} у {1} растёт.</DiseaseGrowthModeChanged_Growing>
	<DiseaseGrowthModeChanged_Stable>{0} у {1} в стабильном состоянии.</DiseaseGrowthModeChanged_Stable>
	<DiseaseGrowthModeChanged_Remission>{0} у {1} в стадии ремиссии.</DiseaseGrowthModeChanged_Remission>
```

Поменять местами `{0}` и `{1}` во всех трёх.

**Comment by Elevator89** [comment]
Запостил тему на форуме:
https://ludeon.com/forums/index.php?topic=30360.0
