### ISSUE TITLE
Новые названия наркотиков

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#42]
@KviEt , @Dimonasdf , @Ohar, @dragomano, @dankan0880

Предлагаю обсудить новые названия наркотиков, т.к. они теперь все выдуманные.

Английские называния:
Go-juice (боевой стимулятор, называние старое, но все же выдуманное)
Luciferium (выдуманный наркотик)
Psychite (бывший кокаин)
Smokeleaf (бывший каннабис)
Wake-up (бывший амфетамин)

Предлагаю базовые варианты:
Luciferium - Люциферий, Люцифериум
Psychite - Психит, Психин
Smokeleaf  - Дымолист, Дымнолист

Вносите предложения. самые креативные попадут в игру.

**Comment by Ohar** [comment]
Химические соединения в русском языке обычно образуются суффиксами `ин` или `ат`. Суффик `ит` принято использовать для минералов. Сравните: *"анальгин"*, *"амфетамин"*, *"героин*". Но *"кальцит"*,  *" шунгит"*. Поэтому _психит_ не очень хорошо подходит.

`Go-juice` — Озверин
`Luciferium` — Люцифин
`Psychite` — Психин
`Smokeleaf` — Курево
`Wake-up` — Шпора

**Comment by Ohar** [comment]
Химические соединения в русском языке обычно образуются суффиксами `ин` или `ат`. Суффикс `ит` принято использовать для минералов. 
Сравните: *«анальгин»*, *«амфетамин»*, *«героин»* —  препараты. Но *«кальцит»*, *«шунгит»* — минералы. 
Поэтому _психит_ не очень хорошо подходит.

# Предлагаю переводы

* `Luciferium` — Озверин ![Кот Леопольд под озвериом](https://www.ridus.ru/images/2013/9/24/121840/in_article_ea73c92a23.jpg)
* `Psychite` — Психин
* `Smokeleaf` — Курево
* `Wake-up` — Шпора

**Comment by Dinoabunai** [comment]
Для психина думаю мы ничего лучше не придумаю, буду переводить пока его.

Еще пару вариантов:
Wake-up - Бодрин
Go-juice - Нектар, еще есть вариант так и оставить его Go-juice бес перевода

**Comment by Ohar** [comment]
Без перевода не надо

**Comment by Dinoabunai** [comment]
ОК

**Comment by Dinoabunai** [comment]
Сюда же такой вопрос - как корректнее перевести следующие термины:
drug tolerance - устойчивость к наркотику или толерантность (или как-то по другому)
withdrawal - ломка или синдром отмены (или как-то по другому)

Они встречаются у каждого наркотика и перевод не совсем однозначный. Поэтому решил спросить мнение у вас.

**Comment by Ohar** [comment]
>  drug tolerance - устойчивость к наркотику или толерантность (или как-то по другому)

Толерантность — это скорость [привыкание организма к наркотику](https://goo.gl/LWKPHx). 
Перевести лучше или как устоявшийся термин — _толерантность_, или же более понятно — _привыкание_.

**Comment by Dinoabunai** [comment]
@Ohar 
Мне нравится вариант с привыканием, но я боюсь игроки могут подумать что привыкание к наркотику означает что павн пристрастился к наркотику, а не то что теперь ему надо большую дозу. 

В свою очередь толерантность к наркотику - слишком непонятный термин для игрока.

Я пока перевел как устойчивость, но этот вариант мне тоже не очень нравится, т.к. игроки могут подумать что устойчивый павн будет, например, менее подвержен побочным действиям вроде нервного срыва. Что тоже не верно.

Если ничего лучше не придумаем - поставлю "привыкание", т.к. хотя бы половине игроков (я надеюсь) знакомо понятие - привыкание к препарату.

**Comment by Dinoabunai** [comment]
@KviEt , @Dimonasdf , @Ohar , @dankan0880
Колееги - просьба проголосовать за варианты перевода, чтобы к концу воскресенья мы уже определились.

Мой голос:
Go-juice - Нектар (хотя Озверин тоже ОК)
Luciferium - Люциферий
Psychite - Психин (уже переведн)
Smokeleaf - Дымолист
Wake-up - Бодрин
drug tolerance - привыкание
withdrawal - ломка и синдром отмены (можете посмотреть https://github.com/Ludeon/RimWorld-ru/pull/47, там я использовал оба варианта)

**Comment by Dinoabunai** [comment]
Я пока буду переводить люциферий, если что переделаю. Пишите.

**Comment by KviEt** [comment]
Озверин ведь предлагался для Luciferium.
Разве Go-juice это не тоже самое, что энергетик?

**Comment by Dinoabunai** [comment]
@KviEt 

> Озверин ведь предлагался для Luciferium.

Блин, не заметил. Спасибо за уточнение. Просто Luciferium, не приводит в ярость. Это таблетка с нано-роботами, которые улучшают общее функционирование организма. При этом человек больше не может жить без них (в прямом смысле). Так что озверин в данном контексте не очень подойдет по моему мнению.

> Разве Go-juice это не тоже самое, что энергетик?

В современном значении да (это алкоголь с газировкой), но в игре это конкретно синтетический боевой стимулятор, употребляющийся внутривенно перед боем. Он улучшает силу и меткость и притупляет страх. Поэтому я и подумал что озверин сюда предлагают.

**Comment by Dinoabunai** [comment]
@KviEt 
Проголосуй как-нить на досуге, если сможешь.

**Comment by Dinoabunai** [comment]
Так же хочу обратить внимание что вариант "Курево" для "Smokeleaf" не подойдет, т.к. "Smokeleaf" это еще и название для растения. Так что растить "Курево" это немного жестковато :)

**Comment by KviEt** [comment]
Исходя из значения, по-моему Go-juice как нектар не звучит, да и самое название Go-juice может поменяться раз это боевой симулятор, озверин вполне звучит забавно и понятно)(но раз повышается меткость то так же не подходит) , боевой симулятор или нечто схожее с названием "боевой симулятор"...

**Comment by Dinoabunai** [comment]
@KviEt 

> Исходя из значения, по-моему Go-juice как нектар не звучит

Обычно в играх военные используют кодовые названия, чтобы не было понятно предназначение препарата. Например Bane из вселенной DC был накачан "Титаном". Хотя мне самому кажется что нектар как-то не очень подходит.

> да и самое название Go-juice может поменяться раз это боевой симулятор

По-английски годно звучит, не думаю что они его будут менять.

> боевой симулятор или нечто схожее с названием "боевой симулятор"...

В будущих релизах могут быть добавлены другие боевые стимуляторы, так что название должно быть уникальным.

**Comment by Ohar** [comment]
@Dinoabunai 
>Мне нравится вариант с привыканием, но я боюсь игроки могут подумать что привыкание к наркотику означает что павн пристрастился к наркотику, а не то что теперь ему надо большую дозу.
>В свою очередь толерантность к наркотику - слишком непонятный термин для игрока.
>Я пока перевел как устойчивость, но этот вариант мне тоже не очень нравится, т.к. игроки могут подумать что устойчивый павн будет, например, менее подвержен побочным действиям вроде нервного срыва. Что тоже не верно.
>Если ничего лучше не придумаем - поставлю "привыкание", т.к. хотя бы половине игроков (я надеюсь) знакомо понятие - привыкание к препарату.

Тогда предлагаю оставить _толерантность_ как самый точный термин. Да, он медицинский и его надо погуглить, но ничего страшного от этого не произойдёт.

**Comment by Dinoabunai** [comment]
@Ohar 
Ты ведь прочитал этот пост? (не знаю как давать ссылку на конкретный пост в гитхабе)

> Озверин ведь предлагался для Luciferium.

Блин, не заметил. Спасибо за уточнение. Просто Luciferium, не приводит в ярость. Это таблетка с нано-роботами, которые улучшают общее функционирование организма. При этом человек больше не может жить без них (в прямом смысле). Так что озверин в данном контексте не очень подойдет по моему мнению.

> Разве Go-juice это не тоже самое, что энергетик?

В современном значении да (это алкоголь с газировкой), но в игре это конкретно синтетический боевой стимулятор, употребляющийся внутривенно перед боем. Он улучшает силу и меткость и притупляет страх. Поэтому я и подумал что озверин сюда предлагают.

**Comment by Dinoabunai** [comment]
@KviEt @dankan0880 @Dimonasdf 
Молодые люди, голосуем.
2 голоса это ни туда, ни сюда.

**Comment by Dinoabunai** [comment]
@Ohar 

> Тогда предлагаю оставить толерантность как самый точный термин. Да, он медицинский и его надо погуглить, но ничего страшного от этого не произойдёт.

Привыкание тоже медецинский термин, причем более распространенный в России. На лекарствах именно так и указывают - пре

**Comment by Dinoabunai** [comment]
Сори - я хотел только пост свой 1 удалить, а случайно закрыл обсуждение. Поэтому не обращайте внимания. Гитхаб меня не любит и наши чувства взаимны :)

**Comment by gans13** [comment]
Luciferium как боевой стимулятор, плюсую

**Comment by Dinoabunai** [comment]
@gans13 
Напоминаю, что в будущем боевых стимуляторов может быть 5 разных штук.
И нельзя чтобы они все назывались "Боевой стимулятор №1"

**Comment by KviEt** [comment]
Go-juice пусть тогда с кодовым названием Нектар \ Энергетик
Luciferium как Люциферий \ Люцифериум меня устраивает...

**Comment by Dinoabunai** [comment]
Может "Боевой Нектар"?

Так же напоминаю что у нас 3 спорных названия:
Go-juice
Smokeleaf 
Wake-up

Luciferium он как Celsium, без проблем переводится.

**Comment by Dinoabunai** [comment]
Боевой Нектар - теперь с мякотью!

**Comment by Ohar** [comment]
> Может "Боевой Нектар"?

Почему _«Нектар»_? :-)

Я разрывался, куда поставить Озверин — как _Go-juice_ или как _Luciferium_, потому что они оба вроде как увеличивают боевые способности. Выбрал Luciferium только потому, что после его приёма поселенец скорее всего помрёт. Как выяснилось, не помрёт, а просто получит жизненно необходимую зависимость. 
Поэтому логичнее _Go-juice_ назвать _Озверином_, а не _Luciferium_.

**Comment by Dinoabunai** [comment]
> Почему «Нектар»? :-)

Близко по смыслу к соку, но более отстраненно от повседневной столовой продукции :)

> Как выяснилось, не помрёт, а просто получит жизненно необходимую зависимость. 

Вообще должен помереть, ты в игре тестировал? Если не помирает - это баг, надо сообщить разработчикам. У него в описании конкретно указано что он приводит к смерти.

> Поэтому логичнее Go-juice назвать Озверином, а не Luciferium.

Ребят, чего вы привязались к Luciferium? Он отлично переводится. Более того я уже сделал перевод для него (я поменяю конечно если будут проблемы с переводом). Я уже 10 раз писал что Luciferium не проблема, он как Celsium.

**Comment by Ohar** [comment]
>Вообще должен помереть, ты в игре тестировал? Если не помирает - это баг, надо сообщить разработчикам. У него в описании конкретно указано что он приводит к смерти.

Нет, не тестировал, по описанию понял что он приведёт к смерти, если новую дозу не принимать постоянно. то есть это зависимость.

**Comment by Dinoabunai** [comment]
@Ohar 
То что павн умрет без постоянных повторений дозы, это и значит что павн не сможет жить и без 2-ой дозы.

**Comment by KviEt** [comment]
Боевой нектар это как-то палевно, мы ведь шифруемся, пусть тогда Заряжающий нектар.
Остальное меня не интересует, по-моему, нормально звучит.
И от Go-juice помирают? Если помирают, тогда надо название говорящее о том, что это "билет в один конец".

**Comment by Dinoabunai** [comment]
@KviEt 
> Боевой нектар это как-то палевно, мы ведь шифруемся, пусть тогда Заряжающий нектар.

Мы шифруемся чтобы эту байду "Вперед-Соком" не называть.

> И от Go-juice помирают?

Нет, ну с чего вы это взяли, я все уже описал выше многократно. Никто не помирает от Go-Juice.
`===============================================================================`
Ребят, ну почему вы Luciferium с Go-Juice путаете постоянно?
У всех же есть папка Drugs, посмотрите там описание если запутались.
Повторюсь - я не знаю как дать ссылку на конкретный комментарий в гитхабе (может кто подскажет?)
Но я писал уже дважды:

> Озверин ведь предлагался для Luciferium.

Блин, не заметил. Спасибо за уточнение. Просто Luciferium, не приводит в ярость. Это таблетка с нано-роботами, которые улучшают общее функционирование организма. При этом человек больше не может жить без них (в прямом смысле). Так что озверин в данном контексте не очень подойдет по моему мнению.

> Разве Go-juice это не тоже самое, что энергетик?

В современном значении да (это алкоголь с газировкой), но в игре это конкретно синтетический боевой стимулятор, употребляющийся внутривенно перед боем. Он улучшает силу и меткость и притупляет страх. Поэтому я и подумал что озверин сюда предлагают.

**Comment by Dinoabunai** [comment]
@Ohar 
Потестировал - с павнами действительно ничего не произойдет, но это видимо, потому что механика с зависимостью/ломкой еще не реализована. Тестеры на оф.форуме тоже жаловались что у них то ломка не наступает никогда, то мужик с ужасным похмельем неделю бегает без негативных эффектов.

**Comment by Ohar** [comment]
@Dinoabunai 
> В современном значении да (это алкоголь с газировкой), но в игре это конкретно синтетический боевой стимулятор, употребляющийся внутривенно перед боем. Он улучшает силу и меткость и притупляет страх. Поэтому я и подумал что озверин сюда предлагают.

Да, сюда и предлагаю. 
У меня _«нектар»_ чётко ассоциируется с нектаром с тетра-паке и ничуть не ассоциируется с боевым стимулятором..
![Пример апельсинового нектара.](https://camo.githubusercontent.com/1ef3e7e11fc4d86e3e7703e9e60654de83db2d94/687474703a2f2f6d65676136342e72752f666f746f5f6e65772f3336373834342e6a7067)

**Comment by Dinoabunai** [comment]
@Ohar 
Мда... похоже вариант отпадает.
По поводу "Озверина" - вариант хороший. Единственное что он оставляет ощущение, что приводит в ярость, хотя на самом деле он, наоборот, успокаивает:
**Feeling pumped but calm.** - из файлов игры.

**Comment by KviEt** [comment]
Нам ведь и не надо чтобы имя ассоциировалось с боевым симулятором?
А надо просто перевести нечто напоминающее Go-juice, типа Заряжающий-Сок, Энерго-сок(столько энергии, что сидеть на месте невозможно)

**Comment by Dimonasdf** [comment]
Neutroamine - Нейтроамин
Psychite - Психин
Flake - Психин (хлопья)
Yayo - Психин (порошок)
[Они точно из психина делаются? Я не проверял.]
Smokeleaf - Дымолист [Думал что-то другое предложить, но самому это название прицепилось, так что, думаю, и игрокам норм будет]
Smokeleaf joint - сигарета/самокрутка с дымолистом / косяк из дымолиста [Но последнее, это уже немного слишком. Самокрутка самое то.]
Go-juice - Энерго-сок понравился, остальное не очень
Luciferium - Люциферий [Точно так надо, потому что в описании On the urbworlds, they call L. the "Devil's Bargain". Ну и когда что-то можно очевидно перевести буквально, не стоит изобретать велосипед.]
Wake-up - Бодрин [Просто, но понятно.]
Malari-block - Антималярин [Тоже просто, и тоже понятно.]

**Comment by Dinoabunai** [comment]
@KviEt 

> Нам ведь и не надо чтобы имя ассоциировалось с боевым симулятором?

Не принципиально.

> А надо просто перевести нечто напоминающее Go-juice, типа Заряжающий-Сок, Энерго-сок(столько энергии, что сидеть на месте невозможно)

Сок это как-то простовато, плюс напоминаю что вводят его внутривенно.

@Dimonasdf 

> [Они точно из психина делаются? Я не проверял.]
> [upd. В игре вообще психина нет. Есть растение Psychoid, из него всё это делается.]

Точно. Психин это химикат, производимый из Psychoid. Думаю что его переведем как "психоид".

> Smokeleaf joint - сигарета/самокрутка с дымолистом / косяк из дымолиста [Но последнее, это уже немного слишком. Самокрутка самое то.]

В принципе Smokeleaf это марихуана. Поэтому лично мне больше "косяк" нравится. Тоже можно обсудить.

**Comment by Dimonasdf** [comment]
Немного позлоупотреблял редактированием комментария.
По "Снежку" готов принять критику, по всему остальному - в минимальных количествах :D

**Comment by Ohar** [comment]
> В принципе Smokeleaf это марихуана. Поэтому лично мне больше "косяк" нравится. Тоже можно обсудить.

_Самокрутка_ — нейтральнее, раз уже разработчики хотят уйти от реальных наркотиков.

**Comment by Dinoabunai** [comment]
@Dimonasdf 
Flake - это крэк. Flake именно курят и никак иначе. А "снежок" намекает на порошок для вдыхания.
Yayo - это порошок из кокаина, который нюхают.

> Psychite - Психин [Где это в игре, не нашёл. Всё, что ниже, делается из нейтроамина и/или Psychoid leaves напрямую.]

Это в **~\RimWorld\Mods\Core\Defs\Drugs\Psychite_Yayo.xml**

```
  <ChemicalDef>
    <defName>Psychite</defName>
    <label>psychite</label>
    <addictionHediff>PsychiteAddiction</addictionHediff>
    <toleranceHediff>PsychiteTolerance</toleranceHediff>
  </ChemicalDef>
```
Делается то он из Psychoid, но сам химикат назыывается психин. Так же как растение называется "кока", а наркотик "кокаином".

> Psychoid - Психит

Может тогда уж "Психи**Д**"?

@Ohar 

> Самокрутка — нейтральнее, раз уже разработчики хотят уйти от реальных наркотиков.

Им принципиально уйти только от названий реальных наркотиков, касательно способов применения и терминологии это неважно.

**Comment by Dinoabunai** [comment]
В игре это кстати нормальный такой косяк:
![hoffman](https://cloud.githubusercontent.com/assets/21159467/18055031/02be9e86-6e0f-11e6-8330-c81dc4608332.jpg)
Господин Хоффман любезно вызвался продемонстрировать нам передовые технологии в области народной медицины.

**Comment by Dimonasdf** [comment]
@Dinoabunai ну, я в этом не спец.

"Д" будет оглушаться, и всё равно все будут называть его психитом. Да и резковато как-то.

Что по хлóпушкам, тогда?

**Comment by Ohar** [comment]
@Dinoabunai @Dimonasdf 
Господа, химикаты в русском принято снабжать суффиксом _-ин_, а не _-ит_. Не называйте *психин* *психитом*, пожалуйста. Я [об этом уже писал](https://github.com/Ludeon/RimWorld-ru/issues/42#issuecomment-242713446).

**Comment by Dimonasdf** [comment]
@Ohar а где конкретно мы его так называем?

**Comment by Ohar** [comment]
@Dimonasdf 
Каюсь, бес попутал.

**Comment by Dinoabunai** [comment]
@Dimonasdf 

> "Д" будет оглушаться, и всё равно все будут называть его психитом. Да и резковато как-то.

Нашел кстати растение - Аконит (лат. Aconitum). Так что можно на "Т".

> Что по хлóпушкам, тогда?

Пока "хлопушки" :)

**Comment by Dinoabunai** [comment]
К тому же осколки крэка называют хлопьями.

**Comment by Dinoabunai** [comment]
К [предыдущему посту](https://github.com/Ludeon/RimWorld-ru/issues/42#issuecomment-243143439)
Обратите внимание на пропорции г-на Хоффмана и длину непосредственно косяка.
Скорее всего поселенцы используют лист формата А-4, причем закручивают косяк они по диагонали.

**Comment by Dinoabunai** [comment]
Как вот эту фигню самокруткой после этого называть? :)

**Comment by Dinoabunai** [comment]
Согласно классификации [употребляемой в народе](https://ru.wiktionary.org/wiki/%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5:%D0%A1%D0%BB%D0%B5%D0%BD%D0%B3_%D0%BD%D0%B0%D1%80%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%BE%D0%B2) это "Гангста плюха"

**Comment by KviEt** [comment]
Я пожалуй все же не сдержусь и скажу.

Сейчас бы в наркоте разбираться, а то не знаем как назвать :D"

**Comment by Dinoabunai** [comment]
Ага, так же это может быть "Ракета"

**Comment by Dinoabunai** [comment]
Пока рабочий вариант "Гангста плюха"

**Comment by Dinoabunai** [comment]
Дима о**еет это все завтра читать :)

**Comment by KviEt** [comment]
Мне кажется господин Хоффман курит либо ракету либо космос ибо скурив такое количество - улетишь в космос...

**Comment by Dinoabunai** [comment]
Кстати, так получилось что собаку этих поселенцев зовут "Чувак"

**Comment by Dinoabunai** [comment]
Сейчас будет пул-реквест, просьба не занимать.

**Comment by Dinoabunai** [comment]
Запулил перевод, посмотрите.

Потестировал люциферий - теперь работет как надо. Но убивает очень не сразу.
Надо подождать где-то пару недель, а то и больше, прежде чем человек умрет.
При этом НАМНООООООГО более вероятно что он умрет, нападая в ярости на опасных диких животных.

**Comment by Dinoabunai** [comment]
@KviEt не подскажешь, есть проблема с переводом:
![1](https://cloud.githubusercontent.com/assets/21159467/18245256/e0a572f8-736c-11e6-99b6-1f8e2d2ed252.jpg)
Не знаешь где это должно быть?
В HediffDef/Hediffs_Global_Drugs.xml все переведено...

**Comment by KviEt** [comment]
В общем я не стал проверять перевод, есть ли у него... так как я пока занят...
Вот вся папка
https://github.com/KviEt/RimWorldHelpInTranslation/tree/master/%D0%A2%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8%20Ru/HediffDef

High находится тут
https://github.com/KviEt/RimWorldHelpInTranslation/blob/master/%D0%A2%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8%20Ru/HediffDef/WakeUp.xml

Need 
https://github.com/KviEt/RimWorldHelpInTranslation/blob/master/%D0%A2%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8%20Ru/HediffDef/Luciferium.xml

На счет алкоголя видимо это стадии
https://github.com/KviEt/RimWorldHelpInTranslation/blob/master/%D0%A2%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8%20Ru/HediffDef/Alcohol_Beer.xml

**Comment by Dinoabunai** [comment]
@KviEt 
Да не, в том то и проблема.
Это все переведено в **\HediffDef\Hediffs_Global_Drugs.xml**
А в игре все равно английские слова отображаются.

**Comment by Dinoabunai** [comment]
@KviEt 
Все нормально. Я случайно вместо "/" поставил точку в одном теге.

**Comment by Dinoabunai** [comment]
@Elevator89 
Думаю можно закрывать обсуждение - мы только по поводу GoJuice не определидись, а его осуждение вынесено в отдельное задание.
