### ISSUE TITLE
Гит для чайников

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#45]
@KviEt , @Dimonasdf , @Ohar, @dragomano, @dankan0880
Я считаю что возникла необходимость написать/дать ссылку на руководство по гиту.
Но не как официальное:
https://git-scm.com/book/ru/v1

А так чтобы можно было сразу почитать 15 минут и работать без проблем.
Чтобы любой новичок мог пользоваться.
У меня самого много времени отнимает возня с гитом.

Просьба, если тут есть боги гита - просветите пожалуйста.

В частности следует в руководстве отметить следующие моменты:
1. Как начать работу. Как клонировать репозиторий.
2. Я сделал изменения - как добавить их в проект.
3. Как получить последние изменения из общего репозитория.
4. Работа с ветками и форками.

Что еще вспомню допишу. Коллеги, подключайтесь к обсуждению - напишите кто как с гитом, кому хотелось бы почитать, а кому - написать руководство. Добавьте свои пункты.

**Comment by Dinoabunai** [comment]
@Elevator89 
Думаю можно закрыть Issue. Теперь у нас хороший гайд на вики.

**Comment by Elevator89** [comment]
3 и 4 пункт не до конца раскрыл. Плюс, надо бы ссылок хороших добавить

**Comment by Dinoabunai** [comment]
Ок, ну как доделаешь, закрывай ишшу.
