### ISSUE TITLE
Текст "Отметить как пройденное" не влезает в кнопку

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#496]
![1](https://cloud.githubusercontent.com/assets/24602486/26765386/dc76957a-4983-11e7-8e5d-97d3dad23531.jpg)

**Comment by Elevator89** [comment]
Как насчёт "закрыть"?

**Comment by Orontion** [comment]
Мне больше нравится вариант "Понятно". Это всё-таки обучение, и игрок после прочтения топика как бы подтвердит, что всё понял.

**Comment by Elevator89** [comment]
Сменить текст на "Понятно" имеет смысл. Но обычно на кнопках пишут глагол, отвечающий на вопрос "Что сделать?".

**Comment by Orontion** [comment]
Тогда надо придумать влезающий в кнопку вариант "Что сделать?".

**Comment by Elevator89** [comment]
Ну, вот, "Закрыть", "Принять", "Продолжить".
В качестве хапасного варианта годится "Понятно"
