### ISSUE TITLE
Cooking

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#497]
Почему бы не просто "готовка", повара всё-таки и мясниками на пол ставки работают (разделка туш). Кулинария это больше из уже готового, а не " что бог послал, а то самого приготовят".

**Comment by Orontion** [comment]
"Готовка" очень плохо звучит. Кроме того, "кулинария" - это совокупность всех действий по приготовлению пищи. Условно говоря, перед тем, как жарить морковь, её нужно почистить и порезать, перед тем, как жарить мясо - нужно снять шкуру с туши и нарезать мясо на куски. Особого смысла в смене названия не вижу.

**Comment by fiziologus** [comment]
нормально звучит (хоть и просторечие). Тем более там навык в одной точке и действие в другой (в походе у костра не кулинарией занимаются).
И к слову обвалка, разделка и снятие шкур в " совокупность всех действий по приготовлению пищи" не входит. Этим далёкие от кухни "специально обученные люди" занимаются.

**Comment by Orontion** [comment]
Ну я выразил своё мнение. Ещё раз говорить то же самое не стану. Как решит большинство переводчиков - так и сделаем.

**Comment by Elevator89** [comment]
[Предварительная обработка](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D1%91%D0%BC%D1%8B_%D0%BF%D1%80%D0%B8%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BF%D0%B8%D1%89%D0%B8#.D0.9F.D1.80.D0.B5.D0.B4.D0.B2.D0.B0.D1.80.D0.B8.D1.82.D0.B5.D0.BB.D1.8C.D0.BD.D0.B0.D1.8F_.D0.BE.D0.B1.D1.80.D0.B0.D0.B1.D0.BE.D1.82.D0.BA.D0.B0) (потрошение, освежевание, отделение мяса от костей) — этап приготовления пищи. "Притовление пищи" == ["кулинария"](https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%BB%D0%B8%D0%BD%D0%B0%D1%80%D0%B8%D1%8F)
Готовка — по смыслу то же самое, но звучит несколько хуже и... просторечнее, что ли. Не вижу большого смысла в изменении текущего варианта.
