### ISSUE TITLE
Правка для биомов

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#498]
[biome.txt](https://github.com/Ludeon/RimWorld-ru/files/1081586/biome.txt)

Мини помощь.

**Comment by Elevator89** [comment]
1. Такие вещи нужно оформлять в виде пулреквеста.
2. По многим местам есть вопросы относительно того, чем оригинал был хуже.

**Comment by Elevator89** [comment]
Пулреквеста так и нет.
А в целом, не вижу смысла менять то, что и так нормально переведено.
