### ISSUE TITLE
GlitterWorld

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#503]
В текущем переводе утопический мир, но glitter это "an attractive and exciting but superficial quality", привлекательное только внешне, что с понятием "утопия" не вяжется.

Здесь ближе "мир блеска", мир-"утопия" (утопия в кавычках).

**Comment by Elevator89** [comment]
_мир-«утопия»_

По смыслу подходит, и в целом короче, чем "утопический мир", но многовато дефисов и кавычек. 
@Dimonasdf, @EcherArt, @Orontion, что думаете?

**Comment by Dimonasdf** [comment]
По не зависящим от меня причинам решил разобрать завал из писем с гитхаба, случайно наткнулся на эту тему. Если что - кидай мне меншны в телеграме - его я проверяю не раз в месяц)

Помню, что я не сильно заморочился с тонким и потекстовым переводом Glitterworld, и остановился на первом более-менее удачном варианте. В связи с чем, сейчас заинтересовался вопросом.

И, хорошенько подумав, вот, что могу сказать, - "утопический мир"/"мир-утопия" изначально несёт в себе какой-то подвох, и дополнительно об этом говорить не обязательно. Тем более, тут. Судя по описанию в лоре,

> Glitterworlds: The most technologically advanced societies that can be led by humans. Swaddled in comforts by the strong arms of technology, glitterworlds are the peak of recognizable human society in terms of art, health, and generous human rights. Common people from these planets often lack grit and are very trusting in people and technology.
> Утопические миры: Самые технологически развитые общества, которые могут быть управляемы людьми. Обёрнутые сильными руками технологий в пелена комфорта, эти миры — высшая точка развития общества, признаваемого человеческим, с точки зрения искусства, здравоохранения, а также прав и свобод. Людям с этих планет часто не хватает твёрдости характера, они очень доверчивы к технологиям и к другим людям.

всё, как "испортились" люди в этих мирах - это стали чуть добрее и отзывчивее. Что, вообще-то, не плохое качество, когда ты живёшь в нормальном мире. Они не стали тупее, не сидят на наркотике, не программируются, ничего такого. Поэтому неотъемлемый, но единственный подвох этой утопии заключается в том, что она плохо контактирует с другими мирами. Если в открывающем посте "an attractive and exciting but superficial quality" взято просто из какого-то толкового словаря, то могу поздравить, никто не сказал, что это описание имеет хоть какое-то отношение к мирам, созданным авторами этой игры. Если этот мир хорош, и его назвали "Блистающим", это не значит, что мы должны переводить его как "Мир-блестяшка" просто от того, что это слово имеет и такой смысл тоже. Если же это где-то из текста, то хотел бы увидеть это место поподробнее (самому искать лень)).

В общем, пока, по совокупности причин, я, внезапно, за старый "мир-утопию". Но жду комментариев.

**Comment by fiziologus** [comment]
> И, хорошенько подумав, вот, что могу сказать, - "утопический мир"/"мир-утопия" изначально несёт в себе какой-то подвох

Утопия и в Африке утопия, нет там никакого подвоха и подводных камней.
> Людям с этих планет часто не хватает твёрдости характера, они очень доверчивы к технологиям и к другим людям.

Вот это и пришлось положить на алтарь спокойствия. Как в "Фаренгейте" Бредбери и вылезшей из него "Эквилибриум" (хотя "Фаренгейт" много чего родил и кроме этого).
> Мир-блестяшка

"Блестяшка" это как раз отрицательный смысл, а "glitter" -- как отрицательный, так и положительный, смотря с какой стороны посмотреть (в русском таких слов-перевёртышей (первое, что пришло в голову, -- магическое русское "ничего" (https://rg.ru/2017/06/08/marina-koroleva-o-neobychnosti-slova-nichego.html)) почти нет: всё задаётся через контекст и интонацию.

Кстати, смотрел Фаренгей -- наткнулся на https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%BE%D0%BF%D0%B8%D1%8F. По смыслу очень даже подходит, и править особо не придётся
(`s|утопи|практопи|g`).

**Comment by Elevator89** [comment]
Не, ребят, давайте обойдёмся без блестяшек и пр~~о~~актопий.
Вот варианты:
1. утопический мир
2. мир-утопия
3. мир-«утопия»

Первй длинноват. Третий — нагромождение символов. Плюс, надо будет где-то объяснять, почему там квычки. 
Поэтому давайте остановимся на втором.
Кто возьмётся переделать?

**Comment by Dimonasdf** [comment]
Тебе не надо будет ничего переделывать, если ты поймёшь, что первый и второй, по сути, - одно и то же.


![reece](https://user-images.githubusercontent.com/14166427/28813916-ff53f414-76a3-11e7-9aeb-1568b343be8c.JPG)

**Comment by Elevator89** [comment]
Да, по сути одно и то же, а выглядит по-разному.
Я правильно понимаю, что ты, @Dimonasdf, предлагаешь использовать **оба** термина равноправно?
Допустимо ли такое в переводе? И где границы такой допустимости?
"Мир пара" и "индустриальный мир", например, тоже по сути одно и то же. Но использовать оба этих термина в одном переводе я категорически отказываюсь.

**Comment by Dimonasdf** [comment]
По сути, надо пошерстить и понять, в каком количестве используется тот или другой варианты, а также, где какой из них более оправдан. Возможно, будет удобнее заменить где-то на один вариант, а где-то на другой. Или ничего не трогать. Просто любопытствующий Ctrl+F _"утопи"_ по всему проекту.

Не вижу между индустриальным миром и миром пара той же безграничной взаимосвязи, как 
 между утопическим миром и миром-утопией. Тут-то явные синонимы.

**Comment by fiziologus** [comment]
> Возможно, будет удобнее заменить где-то на один вариант, а где-то на другой. Или ничего не трогать.

Это (легкий люфт) в терминологии предлагалось ещё в пуле с лором, и встретило невероятно яростное сопротивление. Может Вам поспособствует удача.

> между индустриальным миром и миром пара той же безграничной взаимосвязи

Её и нет. Просто в первых версиях лора мир с таким (почти) описанием назывался Industrial world (в паре бакстори следы этого типа мира до сих пор остались), а сейчас это steamworld (более обособленный с исторической точки зрения период, т.н. "эпоха пара"). И заменить одно другим в большинстве случаев не получится: "эпоха пара" и "индустриализация" не всегда идут рука об руку.

**Comment by Elevator89** [comment]
> Это (легкий люфт) в терминологии предлагалось ещё в пуле с лором, и встретило невероятно яростное сопротивление. 

Это был не "лёгкий люфт", а попытка переписать терминологию. А "невероятно яростное сопротивление" — это замечания о том, что реквест посвящённый лору — не лучшее место для переписывания общеигровых терминов.

> По сути, надо пошерстить и понять, в каком количестве используется тот или другой варианты, а также, где какой из них более оправдан

"Мир-утопия" используется в тайтлах бэкстори, например "Эмпат с мира-утопии". В описаниях стори встречаются оба варианта.
