### ISSUE TITLE
Muffalo

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#504]
B-uffalo – б-уйвол
M-uffalo – м-уйвол, муйвол (уход от кальки в текущем состоянии).

**Comment by Elevator89** [comment]
Интересная мысль. Единственное, что останавливает — это то, что "муйвол" звучит довольно комично. Представляю реакцию игроков и стримеров.
Но в целом мысль здравая. Буду рад услышать мнение других переводчиков.

**Comment by Dimonasdf** [comment]
Huffalo.

**Comment by Elevator89** [comment]
> H-uffalo. Моё мнение.

Каламбур ясен. Но можно ли конструктивную часть твоего мнения сделать чуть поразвёрнетей?

**Comment by fiziologus** [comment]
> "муйвол" звучит довольно комично

Есть устойчивое выражение "из песни слов не выкинешь". Особо комичного в этой версии нет (ударение на первый слог, как и у слова-родителя), в отличии от версии другого оратора (но там можно оттолкнуться от "бык" или "бизон" (тоже buffalo)). На видящих везде "правило 34" нормальные люди вряд ли будут серьёзно обращать внимание.

**Comment by Orontion** [comment]
Я голосую за "муффало". Звучит круто, игрокам уже известен под этим названием. Муйвол и правда какой-то "хуйвол" получается, уходить от кальки смысла не вижу, раз это крутая калька.

**Comment by Elevator89** [comment]
Послушав комментарии остальных, пожалуй, соглашусь с общим мнением.
(Со слов домашних, «муйвол» похож на «мудилу»)
