### ISSUE TITLE
Devilstrand

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#505]
Devil-strand = пряди дьявола (почти буквальный перевод)

Как предложение (может не влезть в текстовое поле). И красиво (кстати, что-то подобное есть и вне игры), и сразу понятно что и для чего (один из лучших (по защитным свойствам) натуральных материалов).

**Comment by Elevator89** [comment]
А ткань соответствующую как предлагается переименовать?

**Comment by Elevator89** [comment]
Сейчас название гриба переведено как "дьявлонитник", из которого получают "дьявлоткань". Мужской род здесь хотя бы даёт понять, что это гриб. А что за "пряди"? И откуда они вырваны у дьявола?

**Comment by fiziologus** [comment]
> А ткань соответствующую как предлагается переименовать?

Можно также. Как в случае с хлопком/льном в реальной жизни (и растение, и получаемая из него ткань). По контексту и так понятно (для особо развитых можно пометки оставить, ткань-не_ткань)

> название гриба ... "дьявлонитник", из которого получают "дьявлоткань"

Недавно был мини-дискус про "тысячелетия". Я лично от гриб сломал язык, об ткань споткнулся (об "ло" или рядом).

> А что за "пряди"? И откуда они вырваны у дьявола?

Уснея Бородатая или ведьмины волосы. Что за волосы и откуда они выдраны. Примеров подобных ненаучных названий множество (из найденого за 5 секунд: борода старика, щучий/рыбий хвост, заячьи лапки, живые камни).
И поганка/сыроежка (из самого известного) тоже грибы, хоть и женского рода.
А если кто-то не знает (хотя бы отдалённо) значение слова "пряди".....

**Comment by Elevator89** [comment]
> Примеров подобных ненаучных названий множество

В реальном нам мире, да, множество. Кому интересно, тот сам найдёт, что такое "ведьмины волосы". 
Но мы переводим игру, и игроку должно быть немного более понятно, что к чему. "Дьявлонитник" более научно звучит, чем "пряди дьявола", и лучше отражает суть. Как я уже говорил, понятно, что это гриб. А прочесть по буквам достаточно один раз, чтобы больше не тупить на этом слове.
В общем, нужны альтернативные варианты, в противном случае тему закрываю
@Dimonasdf, @EcherArt, @Orontion, не хотите предложить ничего?

**Comment by Elevator89** [comment]
@fiziologus, если хочешь переводить, то советую заняться хоть насколько-то актуальными задачами: #442, #443
Это будет точно полезнее, чем пытаться менять термины направо-налево.

**Comment by fiziologus** [comment]
>@fiziologus, если хочешь переводить, то советую заняться хоть насколько-то актуальными задачами: #442, #443

> скорее всего посчитает переводчика наполовину безграмотным, неспособным точно применять родной язык в письменной речи. Или же подумает, что у авторов просто не хватило времени привести свой труд в порядок. Но как вы думаете, про что подумает этот самый человек, почитав все 147 комментариев. Полагаю, что не про нехватку времени.
На каждый критический комментарий в этом реквесте начитается целая дискуссия. Такие дискуссии, как я уже говорил, отнимают и время, и силы. Если бы автор чуть более критически относился к своей работе и чуть лучше прислушивался к комментариям других участников, то этот реквест был бы уже исправлен и залит. А сейчас работа стоит (не исправлено даже четверти перевода!), а время тратится впустую.

Уже пробовал -- больше работать в команде Донцовой не хочется.

>  игроку должно быть немного более понятно, что к чему. "Дьявлонитник" более научно звучит, чем "пряди дьявола", и лучше отражает суть.
?????

**Comment by Elevator89** [comment]
К чему тут две моих цитаты? Где конкретно ты видишь противоречие?

> ?????

Я ответил на этот красноречивый вопрос. Но процитирую:

> Сейчас название гриба переведено как "дьявлонитник", из которого получают "дьявлоткань". Мужской род здесь хотя бы даёт понять, что это гриб

Далее:

> Уже пробовал -- больше работать в команде Донцовой не хочется.

Это вообще о чём было? Здесь кто-то присваивал себе авторство чужих коммитов? 
Может, ты говоришь про какой-то другой проект, который, может, действительно имеет отношение в Дарье Донцовой )? Но тогда причём тут **этот** проект?
