### ISSUE TITLE
"Скорость загрязнения животными"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#510]
Этот текст отображается как название одного из свойств животного. Моно понять, будто это животное пачкают другие животные.

**Comment by fiziologus** [comment]
оригинал (Keyed/Dialogs_Various.xml):

**`<AnimalFilthRate>`Animal filth rate`</AnimalFilthRate>`**

`<AnimalFilthRateExplanation>`Animals produce filth when moving around on constructed floors. This is the average amount of such filth produced per {0} cells walked by this creature.\n\nLarger or less pet-like animals produce more filth.`</AnimalFilthRateExplanation>`

_Скорость загрязнения <поверхности>_

**Comment by Elevator89** [comment]
> Скорость загрязнения поверхности

Да, как-то так. Или "поверхностей"

**Comment by Elevator89** [comment]
Альтернативные варианты:
_уровень загрязнения
показатель загрязнения
производимое загрязнение_
