### ISSUE TITLE
[definjected/hediffs_global_drugs.xml] копипаста

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#511]
<WakeUpHigh.label>под действием бодрина</WakeUpHigh.label>

<WakeUpTolerance.label>толерантность к бодрину</WakeUpTolerance.label>
**<WakeUpTolerance.stages.1.label>небольшая</WakeUpTolerance.stages.1.label>
<WakeUpTolerance.stages.2.label>средняя</WakeUpTolerance.stages.2.label>
<WakeUpTolerance.stages.3.label>сильная</WakeUpTolerance.stages.3.label>**

<WakeUpAddiction.label>бодриновая зависимость</WakeUpAddiction.label>
<WakeUpAddiction.stages.1.label>ломка</WakeUpAddiction.stages.1.label>

<AmbrosiaHigh.label>тепло амброзии</AmbrosiaHigh.label>

<AmbrosiaTolerance.label>толерантность к амброзии</AmbrosiaTolerance.label>
**<WakeUpTolerance.stages.1.label>небольшая</WakeUpTolerance.stages.1.label>
<WakeUpTolerance.stages.2.label>средняя</WakeUpTolerance.stages.2.label>
<WakeUpTolerance.stages.3.label>сильная</WakeUpTolerance.stages.3.label>**

> Ночь, улица, фонарь, аптека,
Бессмысленный и тусклый свет.
Живи ещё хоть четверть века —
Всё будет так. Исхода нет.

> Умрёшь — начнёшь опять сначала
И повторится всё, как встарь:
Ночь, ледяная рябь канала,
Аптека, улица, фонарь.

**Comment by Elevator89** [comment]
Да. Нехорошо получилось.
