### ISSUE TITLE
[minor] Лор

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#515]
В "голову" добавить ВОМ (у меня нет).
В "хвосте": убрать encode (это подсказка для решивших посмотреть файл чем-то вроде старого "блокнота") и добавить, кто переводил, кто редактировал и выполнял корректуру (перевод вы получили со стороны: имею право потребовать).

**Comment by Elevator89** [comment]
С BOM есть проблемы. Не все редакторы его адекватно читают и сохраняют. Например, Atom не сохраняет BOM. Кроме того, он крашится при запуске, если до этого в нём был открыт файл с BOM.
Я сам в своё время стоял за инициативой везде добавлять BOM, но теперь вижу, что c этим многовато гемора.

**Comment by Elevator89** [comment]
По поводу "кто переводил".
В качестве переводчиков в титры мы добавляем тех, кто более-менее успешно участвовал в переводе хотя бы двух версий игры.
Одного перевода файла с лором (которому ещё потребовалось приличное количество исправлений) для вхождения в эту секцию явно недостаточно.
Есть ещё секция "отдельное спасибо". Для неё нужно поучаствовать в переводе хотя бы одной версии. Ну, или сделать что-то значительное и важное для проекта. Например, KviEt написал скрипт, добавляющий в файлы перевода ещё не переведённые строки.

**Comment by fiziologus** [comment]
ВОМ по стандарту нужен для установки порядка байт (endian), но для utf-8 это не критично, и если понять кодировку другим способом невозможно. Здесь как раз второй случай (понять кодировку по выводимым крякозябрам могут далеко не все): или втыкать ВОМ (хоть и не все смотрелки и редакторы его понимают; Atom, кстати, с ним вообще работать не умеет: выводит "как есть" в поток), или втыкать encoding-"костыль", как у меня.

> В качестве переводчиков в титры мы добавляем тех, кто более-менее успешно участвовал в переводе хотя бы двух версий игры

Я сказал, что-то про титры.
> В "хвосте": ... добавить, кто переводил, кто редактировал и выполнял корректуру

Над переводом работали двое (один , и понять это на данный момент невозможно. Или же удаляйте **весь** мой текст, если считаете, что всё сделали в одиночку.

**Comment by Elevator89** [comment]
Никто не говорит, что лор переведён в одиночку.
Все, кто работал над переводом, увековечены в истории коммитов.
В каждый отдельный файл мы авторов его перевода не пишем.

**Comment by fiziologus** [comment]
> Все, кто работал над переводом, увековечены в истории коммитов.

Только вот нет в ней событий до смерживания lore с master. В истории самого файла есть, а в истории коммитов нет.
И указывать _"кому по макушке стучать"_ в случае с литературными текстами (и не только) вполне обычная практика (как и указание на оригинал в случае перевода).
https://github.com/fiziologus/RimWorld-ru/commit/22744959c4e3d8d822b429bc4ab8a5ae12025435
(со своей стороны ещё можете добавить "синхронизация с терминологией"; и не забудьте, кто предложил "Развитие и упадок планет" (тут лучше "миров", благо в пределах текста это синонимы)).

**Comment by Dimonasdf** [comment]
.

**Comment by Elevator89** [comment]
> Только вот нет в ней событий до смерживания lore с master. В истории самого файла есть, а в истории коммитов нет.

Да [неужели ](https://github.com/Ludeon/RimWorld-ru/commits/master))?

**Comment by Elevator89** [comment]
На все вопросы даны ответы. Тему считаю закрытой.
