### ISSUE TITLE
Go-сок

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#516]
Посмотрел старый ишью. Поднимем тему.

В русском разговорном крепкий (часто самопальный) алкоголь (одна из интерпретаций, и, кстати, хороший стимулятор, если не перебрать) называют простым словом: "горючее" или просто "горючка" (ещё одна интерпретация).

**Comment by Elevator89** [comment]
"Горючка" — вариант любопытный, точно получше некоторых предложенных ранее, но, если честно, не вижу смысла переименовывать то, что:
1) переведено без значительных искажений оригинала и не противоречит ему по смыслу;
2) уже устоялось и привычно пользователям;
3) аналогично переведено для других языков.
