### ISSUE TITLE
"Социальные наркотики" 

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#517]
"Социальные наркотики" - [полная херня](https://github.com/Ludeon/RimWorld-ru/issues/206#issuecomment-254352995) или нет?

**Comment by fiziologus** [comment]
[Social drugs](http://www.bbc.co.uk/schools/gcsebitesize/pe/performance/1_performance_drugsinsport_rev2.shtml) нет. А вот перевод... В русском такие вещи (по сути легальные психотропные вещества) и к наркотикам то не причисляют (а если и причисляют, то только номенклатурно).

Применяется оно, вроде, в политике (схеме) приёма наркотиков. Можно заменить на _"для расслабления"_ (_"рекреации",_ хотя 99% людей значение этого мудрёного слова не знают). Или чем-то из этого же ряда.

**Comment by Elevator89** [comment]
> для расслабления

@Dimonasdf, что думаешь?

**Comment by Dimonasdf** [comment]
_Рас_-слабительные вещества)

По сути, - да, - у нас тут немножко конфликт культур. Потому что у нас это максимум - "вредные привычки". И другого общего названия для питья и курения у нас, вроде, нет.

Если будет понятно из контекста, что "для расслабления" это то, что мы хотим, то ок. Либо правда как-то уместить в текст формулировку "Разрешить вредные привычки".

**Comment by fiziologus** [comment]
> Потому что у нас это максимум - "вредные привычки". И другого общего названия для питья и курения у нас, вроде, нет.

"Вредные привычки" это когда неумеренно, а разик-два на "снять стресс", либо как аперитив вообще никак не называют. Никакого "конфликта культур" (за исключением разрешённой в некоторых странах конопли, которая сейчас наркотик, а была (до 90-х годов) технической культурой): люди везде одинаковые по физиологии, хоть и говорят на разных языках.

**Comment by Elevator89** [comment]
В принципе, ничего против "Для расслабления" не имею.
Другие варианты будут?
