### ISSUE TITLE
"Пауза по удовлетворении"

### ISSUE THREAD

**Issue by zumm** [Ludeon/RimWorld-ru#522]
Русская локализация для PauseWhenSatisfied и UnpauseWhenYouHave в файле Keyed\Dialog_Various.xml слишком длинная. Из-за этого чекбокс налазит на надпись, а слайдер и вовсе уходит за пределы видимой области.
https://habrastorage.org/web/dea/948/ebf/dea948ebf3a0490ab2f89b385db41e6e.png

Если не играть ни разу в оригинал и не знать, что слайдер там есть, то можно очень долго думать, что так и должно быть. Если бы не это https://ludeon.com/forums/index.php?topic=33480.0 до сих пор бы так и думал.

Перевод явно нужно делать короче, но как при этом сохранить понятность описания - вопрос отдельный. Для себя остановился на "Пауза по окончанию" и "Продолжить от".
https://habrastorage.org/web/634/c37/0fa/634c370fa830492d8a806ffaa536f935.png

P.S.: Кстати, сама фраза "Пауза по удовлетворении" некорректна. Должно быть или "Пауза при удовлетворении" или "Пауза по удовлетворению".

**Comment by Elevator89** [comment]
> фраза "Пауза по удовлетворении" некорректна

[Фраза](http://russkiiyazyk.ru/orfografiya/pravopisanie/kak-pravilno-po-pribyitii-ili-po-pribyitiyu-na-mesto.html) [корректна](http://new.gramota.ru/spravka/buro/search-answer?s=%D0%BF%D1%80%D0%B8%D0%B1%D1%8B%D1%82%D0%B8%D0%B8)

**Comment by Elevator89** [comment]
Первая фраза имеет значение: "Когда будет сделано N экземпляров, поставить задание на паузу". "Пауза по окончании" тут не очень подходит. Тут речь именно про _удовлетворение потребностей_ поселения в ресурсе.
Вторая — "возобновить работу, если на складе M или меньше экземпляров продукции". Фраза "продолжить от" вообще непонятно что значит.

**Comment by zumm** [comment]
> Фраза корректна
Ну что ж, очевидно, это мой колхозный фейл. Но все таки звучит это как-то... странно?

Не уверен, что сокращения это лучший вариант.
Например, в оригинале для UnpauseWhenYouHave используется "Unpause at", что мало чем отличается от "Продолжить от". И ничего, люди понимают. 
А с PauseWhenSatisfied дело, конечно, обстоит сложнее. Понятно, что речь идет именно про удовлетворение потребностей, но для красоты перевода можно воспользоваться переносом логики. То есть, задание завершится, когда потребности будут удовлетворены (колонист не станет продолжать работу, если на складе уже есть N единиц). Таким образом завершение задания можно считать удовлетворением потребностей и использовать его в описании функции. При этом логика работы функции полностью сохраняется.

**Comment by Dimonasdf** [comment]
На самом деле, "Продолжить от" меня полностью удовлетворяет.
"Пауза по окончани(ю/и)" звучит немного странно, но с лёгкостью годится как временное/не имеющее пока что лучшего решение.

**Comment by Elevator89** [comment]
Решение одно — наиболее точно передать смысл этих элементов. Не просто перевести оригинал, а именно передать смысл. 
"Продолжить от" справляется с этой задачей так себе. "Продолжить при наличии" — идеальный вариант, если бы не его длина.
"Пауза по удовлетворении" вообще не справляется.

В любом случае, коммит сделан. Текст выглядит вполне неплохо, задачу выполняет. 
Если кто-то считает иначе, и есть вариант лучше, переоткрою ишью.
