### ISSUE TITLE
MovementTime

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#525]
```
	<CaravanBaseMovementTime>Базовое время пути</CaravanBaseMovementTime>
	<CurrentTileMovementTime>Времени в текущей клетке</CurrentTileMovementTime>
```
Имеется в виду:
CaravanBaseMovementTime: базовое время на прохождение одной "обычной" клетки этим караваном
CurrentTileMovementTime: рассчитанное время для прохождения конкретной клетки этим же караваном.
Это можно было бы назвать словом "скорость", но под скоростью обычно понимают количество расстояния, пройденного в единицу времени, а не время, потраченное на единицу расстояния.

**Comment by fiziologus** [comment]
> CaravanBaseMovementTime

Обычное время прохождения (не помню какая размерность: время или время на клетку).

> CurrentTileMovementTime

Время прохождения (преодоления) текущей клетки.

Места там достаточно, особо ужимать ничего не надо.
