### ISSUE TITLE
Traits. Мелкие огрехи.

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#534]
Вначале без градации (Singular).

- **Bloodlust** и Ascetic
_NAME gets a rush from hurting people, and never minds the sight of blood or death. HECAP is twice as likely to start a social fight._ : **NAME входит в раж, причиняя людям боль. HIMCAP безразличен вид крови или смерти.**
_NAME prefers to live in asceticism. HECAP will be put in a poor mood if HE has a bedroom that's too impressive. HECAP also dislikes fancy food and prefers to eat raw - and raw food won't bother HIM a bit._ : **NAME предпочитает жить скромно. У нHIS портится настроение, если HIS спальня слишком впечетляющая.**
Мне кажется, что в переводе чего-то не хватает...

- **Kind**
"Скрашивать" – убирать недостатки, а день у нас может быть как плохим, так и хорошим, и добряк **делает его светлее**.

- **Cannibal**
Лучше **людоед**, уже есть моды на ксенолюдей.

- **Abrasive**
**Резкость** (говорю, что думаю), а не грубость (посылаю всех лесом).

- **Brawler**
_NAME likes to fight up close and personal_ **Лицом к лицу**, а не "в полный контакт". (up close and personal – фразеологизм, родившийся из названия телепередачи).

- **GreenThumb**
**«Зелёная рука»** (можно и без кавычек). Ни разу не слышали?

- **NightOwl**
Первую пару **просыпатся-бодрствовать** надо **поменять местами** (забыл, и, вообще, редактор мог бы сам догадаться).

- **Ascetic**
Аскетизм – образ жизни, а черта – **аскет**.

- **DislikesMen**, **DislikesWomen**
**мизандрия**, **мизогиния** на усмотрение редакции: разница там не сильная.

- **Wimp**
**<Wimp.degreeDatas.0.label>wimp</Wimp.degreeDatas.0.label>
<Wimp.degreeDatas.0.description>NAME is weak and cowardly. Even a little pain will immobilize HIM.</Wimp.degreeDatas.0.description>**
Кто-то говорил про скрипт, отслеживающий добавившееся строки... _Хотя принять жеребца в подарок и ездить на этом жеребце – вещи разные._

Теперь с градацией (Spectrum)
- **SpeedOffset**
"Ходок" – кто много, а не быстро ходит. Лучше перевести "почти" дословно – **скороход**

- **DrugDesire**
Аддикция – это когда уже надо, а "пешка" с этой чертой либо не откажется, **если есть возможность**, либо очень редко, когда откажется. Ну и далее вместо интереса вылезают зависимости.
_<DrugDesire.degreeDatas.0.label>увлечение «химией»</DrugDesire.degreeDatas.0.label>
<DrugDesire.degreeDatas.0.description>NAME имеет сильную увлечённость химическими источниками удовольствия. Потреблять HE их будет значительно больше и чаще, а временами и устраивать долгие алкогольные, либо наркотические марафоны. HECAP не обращает внимания на указания не использовать доставляющие удовольствия препараты.</DrugDesire.degreeDatas.0.description>
<DrugDesire.degreeDatas.1.label>интерес к «химии»</DrugDesire.degreeDatas.1.label>
<DrugDesire.degreeDatas.1.description>У NAME необычный интерес к химическим источникам удовольствия.  Потреблять HE их будет побольше и почаще, а временами расслабляться с их помощью дольше, чем надо. HECAP не обращает внимания на указания не использовать доставляющие удовольствия препараты.</DrugDesire.degreeDatas.1.description>_

- **Nerves**
**Железная воля**, а не железные (правильно "стальные") нервы. Пешка не сломается под гнётом обстоятельств, а не не вздрагивает от неожиданного "бу".

- **Industriousness**
Трудоголик не трудолюбивый, а зацикленный на работе человек (да это один из возможных переводов, но на результат смотреть тоже надо). Здесь ближе (при "гендерном равенстве") **работяга**.

- **PsychicSensitivity**
Разум гиперчувствительного **подобен камертону** (tuning fork), а разум психически глухого работает не "на отличной от других волне", а на **на волне, отличной от волны кого-либо ещё**.

- **Beauty**
Оригинал "красоты": NAME is exceptionally beautiful, with an exotic-yet-familiar facial structure and an arresting gaze. People are attracted to HIM before HE even opens HIS mouth.
_NAME обладает исключительной красотой, с необычным, но в тоже время знакомым лицом и приковывающим взглядом. HECAP привлекает людей ещё до того, как откроет рот._
И не нужно мучить никакую экзотику.

**Comment by Elevator89** [comment]
> Мне кажется, что в переводе чего-то не хватает...

Это в игре раньше чего-то не хватало, а появилось недавно. За всем сразу не уследишь.

> Cannibal
Лучше людоед, уже есть моды на ксенолюдей

С какого перепугу "каннибализм" не сочетается с ксенолюдьми?

> Резкость (говорю, что думаю), а не грубость (посылаю всех лесом).

Посылать всех лесом - это хамство. А говорить что думаешь - это как раз [грубость](https://ru.wikipedia.org/wiki/%D0%93%D1%80%D1%83%D0%B1%D0%BE%D1%81%D1%82%D1%8C).

> GreenThumb
«Зелёная рука» (можно и без кавычек). Ни разу не слышали?

Не-а. Переводить идиомы дословно - плохая идея.

> NightOwl
Первую пару просыпатся-бодрствовать надо поменять местами (забыл, и, вообще, редактор мог бы сам догадаться).

Редактор проверил и догадался, что "просыпаться" там вообще не к месту. В обоих случаях нужно "бодрствовать".

> Wimp
Кто-то говорил про скрипт, отслеживающий добавившееся строки... Хотя принять жеребца в подарок и ездить на этом жеребце – вещи разные.

Жеребец не отслеживает строки. Он генерит заготовку файла для перевода. При этом новые строки всегда идут в самом конце. Для отслеживания добавленных строк он не очень удобен. Гораздо лучше в этом плане translation report, генеримый самой игрой, но и он имеет свои минусы. Например, Wimp и все остальные вложенные поля он как раз он не увидит. Пока что я не встретил универсальных жеребцов, к сожалению.

> Nerves
Железная воля, а не железные (правильно "стальные") нервы.

Стальные/железные нервы как раз у человека, который устойчив к психологическим стрессам. В контексте "бу" применения этой фразы не встречал. А железная воля - это когда человек умеет управлять собой и окружающими. Не то.

> Industriousness - работяга.

Лучше "трудолибие", для единообразия. См. на другие  степени - "усердие", "леность", "праздность".

> PsychicSensitivity
Разум гиперчувствительного подобен камертону 

Мы намеренно ушли от дословного перевода как от неподходящего по смыслу. [Tuning fork](https://images-na.ssl-images-amazon.com/images/I/41zhc3qJysL._SX355_.jpg) надо нехило ёбнуть обо что-то, чтобы его можно было хотя бы просто услышать. Да и сам смысл камертона в том, чтобы всегда, в любых условиях выдавать звук одной и той же частоты. Ни о какой чувствительности речи не идёт, скорее наоборот.

> с необычным, но в тоже время знакомым лицом 
Что? Кому знакомым?

**Comment by Elevator89** [comment]
> Ascetic
Аскетизм – образ жизни, а черта – аскет.

Не вижу противоречий, как и смысла менять текущй вариант.

**Comment by fiziologus** [comment]
> С какого перепугу "каннибализм" не сочетается с ксенолюдьми?

Канибаллизм -- поедание особей **своего** вида (тигр-канибал не есть тигр-людоед), а ксенолюди хоть и близкородственный, но всё же другой вид.
> А говорить что думаешь - это как раз грубость

 С каких это пор прямота (резкость в общении) стала грубостью.
> социально-психологическая черта человека, различные проявления жесткости в отношениях, неучтивости, черствости, невежливости, своего рода душевной близорукости, неуважения, несоблюдения социальных норм или этикета групп, культуры.
> Она выражается в откровенной недоброжелательности к окружающим, в не внимании к чужим интересам и запросам, в беззастенчивом навязывании другим людям своей воли и желаний, в неумении сдерживать свое раздражение (Выдержка), в непредумышленном или намеренном оскорблении достоинства окружающих людей, в развязности, сквернословии, употреблении унизительных кличек и прозвищ, в хулиганских действиях.

Грубость есть, прямоты не наблюдается.

>  Переводить идиомы дословно - плохая идея

А кто сказал, что это дословный перевод (дословный: "зелёный большой палец"). "Зеленорукий" ("у него зелёная рука") очень распространённое у работающих с растениями (и не только) людей слово: _язык надо знать не только по словарю_.

> Жеребец не отслеживает строки. Он генерит заготовку файла для перевода. При этом новые строки всегда идут в самом конце.

А сдиффать (diff) заготовку и текущий вариант (половина хороших редакторов это уже умеет, а про IDE и говорить не стоит) и проштудировать выхлоп ну никак нельзя.
Или попользовать [это](https://github.com/KviEt/RimWorldHelpInTranslation/blob/master/P2.7%20Compare.py) (работоспособность не проверял)

> Стальные/железные нервы как раз у человека, который устойчив к психологическим стрессам. В контексте "бу" применения этой фразы не встречал. А железная воля - это когда человек умеет управлять собой и окружающими.

??? Как знаете.

> Мы намеренно ушли от дословного перевода как от неподходящего по смыслу. Tuning fork надо нехило ёбнуть обо что-то, чтобы его можно было хотя бы просто услышать. Да и сам смысл камертона в том, чтобы всегда, в любых условиях выдавать звук одной и той же частоты. Ни о какой чувствительности речи не идёт, скорее наоборот.

Про резонанс не слышали (как раз на камертоне и показывают). Смысл как раз в этом (и не только здесь, но и во всей ветке: "NAME's mind is like a psychic tuning fork" (полный, либо (ниже) почти полный резонанс), "NAME's mind is psychically out of tune with others" (скажет так, резонанс через октаву, либо настройка камертона сбилась), "NAME's mind works on a psychic frequency different from everyone else" (камертон гитарный, а не обычный) ). 
А "тонко настроенный инструмент" -- это про душевную организацию, а не чувствительность.
(_и чтобы услышать **хороший** камертон, достаточна щелчка по вилке; удар в основание используют для больших вариантов (первый закон Ньютона и никуда не денешься), либо когда вилка держится в руке (поглощение колебаний),  и чтобы не сбивать настройку у перенастраиваемых камертонов_)

**Comment by Elevator89** [comment]
> ксенолюди хоть и близкородственный, но всё же другой вид

Извини, я не вижу связи между фактом наличия мода на ксенолюдей (или на что либо ещё) и необходимостью переделывать очевидно верный перевод слова "Cannibal".

> С каких это пор прямота (резкость в общении) стала грубостью.

Читай внимательно:

> Грубиян стесняет окружающих. Он не стремится умышленно причинить вред людям, не желает унизить или оскорбить. Грубость не тождественна наглости или жестокости, хотя нередко приводит к бесцеремонным и уязвляющим поступкам. Грубиян не стремится к злу, хотя часто его причиняет. Грубый человек просто остается самим собой, он поступает в соответствии со свойствами своей личности, он не умеет учитывать ни особенностей людей, ни реальных обстоятельств. Недостаток грубияна состоит в его простоте: в неотёсанной уверенности, что кроме него в мире никого нет; или, по крайней мере, никого и ничего, с чем стоило бы сообразоваться.

Есть ещё вопросы?

> язык надо знать не только по словарю.

Ты удивишься, но словари разговорной речи тоже существуют. Найдёшь там своих "зеленоруких" — тогда и поговорим.

> Или попользовать это (работоспособность не проверял)

А я проверял. Это и есть тот самый "жеребец".

> А сдиффать (diff) заготовку и текущий вариант

Нет необходимости. В заготовке новые части всегда идут в конце. Пропустить сложно.
Скорее всего, Wimp'а просто ещё не было, когда создавались ишью для перевода 0.17.

> А "тонко настроенный инструмент" -- это про душевную организацию, а не чувствительность.

Не вижу принципиальной разницы. В любом случае, метафора, проходящая сквозь градации, если она и имела место в оригинале, слишком неясна и размыта, чтобы её повторять слово в слово в переводе. 
Этот вопрос уже обсуждался, и коллективно было принято решение не использовать неочевидную метафору с камертоном, а вместо неё применить более подходящую по месту.

**Comment by Elevator89** [comment]
Тему закрываю. По огрехам, наличие которых на вызывает больших сомнений, создам отдельные ишью.
