### ISSUE TITLE
GreenThumb

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#540]
Если уж в очередной раз воспользовались (по "тыканью" ясно, что на брудершафт мы уже выпили).

http://otkrytka.mybb.ru/viewtopic.php?id=7375
> С осени на даче посажены тюльпаны и прочие луковичные. А вечной будем садить все, что увидим. У нас посадками заведует племянник - **у него зелёная рука**, а я занимаюсь общим руководством и субсидированием.

http://tonkiimir.ru/viewtopic.php?t=10301
> Хорошая освешенность, высокая влажность, вовремя пдкармливать,ну ещё желательно что бы сажал их человек **про которого говорят что у него зеленая рука**.

www.lib.tpu.ru/fulltext/c/2011/C77/V2/056.pdf   стр 172, второй абзац. Собственно откуда вероятней всего пошло.

Нужно больше -- скармливаем поисковику "у него зелёная рука", фраза эта достаточно устойчивая.

> язык надо знать не только по словарю.

**Comment by Elevator89** [comment]
Две ссылки на древние форумы, один из которых посвящён оккультизму? Ты серьёзно считаешь **это** достаточным основанием для того, чтобы считать фразу устойчивой?
Ни Гугл, ни Яндекс по запросу "у него зелёная рука" выдают [что угодно](https://yandex.ru/images/search?text=%D1%83%20%D0%BD%D0%B5%D0%B3%D0%BE%20%D0%B7%D0%B5%D0%BB%D1%91%D0%BD%D0%B0%D1%8F%20%D1%80%D1%83%D0%BA%D0%B0&noreask=1&img_url=http%3A%2F%2Fcs8.pikabu.ru%2Fpost_img%2F2017%2F03%2F20%2F8%2F1490012336143212335.jpg&pos=12&rpt=simage&lr=193), но не употребление якобы устойчивого выражения.
Если бы ты читал чуть внимательнее, то заметил бы, что источник по третьей ссылке говорит открытым текстом, что "у него зелёная рука" - это не что иное, как буквальный дословный перевод французского выражения, сделанный в академических целях. Из него не могло ничего "пойти":

> Французские фразеологизмы с vert могут характеризовать человека с положительной стороны...
> А тот, кто обладает способностью к уходу за растениями  –  "il a la main verte" (букв. "у него зелёная рука"). **В русском языке подобные понятия со словом зелёный отсутствуют.**

Если обсуждать смысл, то "зелёная рука" - это про способность к уходу за растениями. А в игре никакой корреляции с именно способностью нет. У павна просто настроение повышается, а навык может быть хоть нулевой.

> по "тыканью" ясно, что на брудершафт мы уже выпили

В этом проекте принято обращаться на "ты". Странно, что ты ещё этого не заметил.

**Comment by fiziologus** [comment]
> Две ссылки на древние форумы, один из которых посвящён оккультизму? Ты серьёзно считаешь это достаточным основанием для того, чтобы считать фразу устойчивой?

Фраза есть? Смысл в обоих случаях один и тот же?

> Ни Гугл, ни Яндекс по запросу "у него зелёная рука" выдают что угодно, но не употребление якобы устойчивого выражения.

А каким место https://yandex.ru/images относится к поиску **текстовой фразы**? Или у вас какое-то извращенное восприятие.

> это не что иное, как буквальный дословный перевод французского выражения, сделанный в академических целях. Из него не могло ничего "пойти"

А когда французский и русские языки были тесно связаны?

>  русском языке подобные понятия со словом зелёный отсутствуют.

Отсутствуют не значит не употребляются. Многие фразы пришли в русский из других языков. И если бы ты читал внимательно этот источник, то понял бы, что понятие "входит в язык" там обозначает "исконные для языка фразы", не фразы-заимствования.

> зелёная рука" - это про способность к уходу за растениями. А в игре никакой корреляции с именно способностью нет. 

<label>green thumb</label>
        <description>NAME has a passion for gardening. HECAP gets a mood bonus for every plant HE sows.</description>
        <skillGains>
          <li>
            <key>Growing</key>
            <value>2</value>
          </li>
        </skillGains>
Совсем нет. Ни капельки. Ну не граммулечки.

> В этом проекте принято обращаться на "ты".

Я **не отношусь к команде проекта**. Между собой можете как угодно.

> ещё более странно прийти на проект и вести себя так, словно все тебе здесь чем-то обязаны

В русском языке, если бы вы его хорошо знали, к незнакомому человеку (независимо от возраста) принято обращаться **на вы** (при этом на письме само местоимение в некоторых случаях пишется с заглавной).
> Я **не отношусь к команде проекта**.

И изначально ко всем обращался на вы. И это не мои личные хотелки, это элементарные правила вежливости, вошедшие в язык, и мне неприятно, что незнакомые мне люди то ли панибратствуют со мной, то ли неявно оскорбляют.

**Comment by Elevator89** [comment]
> Совсем нет. Ни капельки. Ну не граммулечки.

Ок, не посмотрел. Есть корреляция.

> Фраза есть? Смысл в обоих случаях один и тот же?

Фразу употребили две тётки на каких-то форумах, по одному разу. Являются ли два этих употребления выражения признаком его **устойчивости**? Думаю, что нет.

> А каким место https://yandex.ru/images относится к поиску текстовой фразы?

Таким, что на входе поисковику всё равно даётся текстовая фраза, а не изображение. Этой картинкой я проиллюстрировал пример того, что находит поисковик. И текстовый поиск также не выдаёт [практически](https://yandex.ru/yandsearch?&clid=2186620&text=%D1%83%20%D0%BD%D0%B5%D0%B3%D0%BE%20%D0%B7%D0%B5%D0%BB%D1%91%D0%BD%D0%B0%D1%8F%20%D1%80%D1%83%D0%BA%D0%B0&lr=193) [ничего](https://www.google.ru/search?q=%D1%83+%D0%BD%D0%B5%D0%B3%D0%BE+%D0%B7%D0%B5%D0%BB%D1%91%D0%BD%D0%B0%D1%8F+%D1%80%D1%83%D0%BA%D0%B0&ie=utf-8&oe=utf-8&gws_rd=cr&ei=AJaZWYm5A8PP6ATZ0K6wDw) релевантного заявленному тобой смыслу. 

Мне кажется, я достаточно ясно сказал искать "зеленоруких" в словарях устойчивых выражений (фразеологических). Найдёшь — тогда будем говорить.

Теперь о другом.

> Я не отношусь к команде проекта. Между собой можете как угодно.

Про **команду** речи не было. Есть **участники** прокета. Ты или участвуешь в проекте, или не участвуешь. Если участвуешь, то изволь быть готовым к общению на равных.

> мне неприятно, что незнакомые мне люди то ли панибратствуют со мной, то ли неявно оскорбляют.

Вот уж кто бы говорил про извращенное восприятие. Хотя, с другой стороны, не нравится — не ешь.

**Comment by fiziologus** [comment]
> Фразу употребили две тётки на каких-то форумах, по одному разу. Являются ли два этих употребления выражения признаком его устойчивости? Думаю, что нет.

Причём в **обоих** случаях фраза была **идентичной** как **по структуре**, так и **по смыслу**. Хотя да, _этого же нет в словаре, значит и нет в языке. В словарях же собраны ну абсолютно все слова в языке, во всех смыслах и контекстах._

Apropos, [этот](https://youtu.be/RwFo9tRguFw?t=1515) смысл родился уже на русском чернозёме, но с изначальным достаточно близко связан, хотя "_в словаре это нет, значит нет нигде_".
> Есть участники **прокета**. Ты или участвуешь в проекте, или не участвуешь. Если участвуешь, то изволь быть готовым к общению на равных.

Не участвую. Изначально. Хочу помогаю, хочу -- нет. Разговор (хоть и личной) про это был уже давно. [Для общего развития](http://etika-education.ru/otvety-k-ekzamenu-professionalnaya-etika-i-etiket-etiket-obshheniya-lichnye-mestoimeniya-ty-i-vy-kak-nado.html)

> Вот уж кто бы говорил про извращенное восприятие

Процитировать снобискую манеру общения одного из участников этой переписки.

> не нравится — не ешь

Что и пытаюсь делать, да только насильно пихают, уверяя, что так принято.

**Comment by Elevator89** [comment]
> этого же нет в словаре, значит и нет в языке

Я такого не говорил, не надо перевирать мои слова. Я говорил, что если фразы нет во фразеологическом словаре, то она не может называться устойчивой.

> Для общего развития

Ах да, куда же мне до Вас с Вашим высочайшим уровнем развития! Совсем забыл обратиться к знаниям этой статьи, бесценным в случае общения через Интернет и работе над опенсорсным проектом.

> Не участвую. Изначально. Хочу помогаю, хочу -- нет.

Здесь все хотят помогают, хотят - нет. Принуждать никто никого не собирается. Это и называется участием. А участники здесь общаются на "ты". Персонально для Вас, глубокоуважаемый @fiziologus, исключения не будет.
