### ISSUE TITLE
DefInjected: замеченные огрехи

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#546]
- **_DesignationCategories.xml_**
_<Temperature.description>Устройства для управления температурой.</Temperature.description>_
**Средства**. Костёр не устройство.
- **_FactionDef/Factions_Misc.xml_**
_<Outlander.label>город чужеземцев</Outlander.label>_
Они _outlander union_ (союз чужеземцев, чужеземный союз) вообще-то.
_<Outlander.leaderTitle>мэр</Outlander.leaderTitle>_
В оригинале -- _prime councilor_ (первый советник).
- **_GameConditionDef/GameConditions_Misc.xml_**
_<SolarFlare.label>вспышка звезды</SolarFlare.label>_
Солнечная вспышка. Звезда для своих планет является **солнцем**. А "вспышка звезды" -- это где-то вспыхнуло и досюда долетело.
**PsychicDrone** и **PsychicSoothe** в оригинале 
_A distant, powerful AI is emitting waves of psychic force that are driving people towards insanity._ (Где-то вдалеке могущественный ИИ излучает волны влияющей на разум силы, что ведёт людей навстречу безумию.)
_A distant, powerful AI is emitting waves of psychic force that are calming people and stabilizing their minds._ (Где-то вдалеке могущественный ИИ излучает волны влияющей на разум силы, что умиротворяет людей и укрепляет их умы)
**ToxicFallout** и **VolcanicWinter**
_Недалеко от поселения произошёл выброс химических отходов. Любое существо, не защищённое крышей, будет получать химическое отравление и ожоги._
против
_A plume of toxic dust from some distant source is slowly settling over this entire region of the planet. Anyone not under a roof will be slowly poisoned._
и
_Произошло извержение вулкана.\n\nПотоки лавы не добрались до поселения, но вулканический пепел в течение многих месяцев будет заслонять свет звезды._
против
_The atmosphere is choked with volcanic particles, significantly reducing the amount of light which reaches the surface. Temperatures will be colder and plants will grow slower._
- **_HediffDef/Hediffs_Global_Execution.xml_**
_<Euthanasia.label>_ приказал долго жить.
- **_HediffDef/Hediffs_Global_Misc.xml_**
Потеря крови --> кровопотеря (незаметная (незначительная), лёгкая, средняя, серьёзная, огромная).
Криптосонная болезнь -> Криптосонная слабость.
Химический ожог -> накопление токсинов, _toxic build up_ (химический ожог слабоумие вызовет только, если долго и без головного убора, а рак и подавно): незаметное (незначительное), начальное, лёгкое, умеренное, серьёзное, чрезмерное.
Беременна (в label) -> беременность
- **_HediffDef/Hediffs_Global_Temperature.xml_**
Гипотермия -> переохлаждение.
Озноб -> дрожь (озноб обычно не от переохлаждения).
- **_HediffDef/Hediffs_Local_AddedParts.xml_**
Силовая клешня -> когти 
- **_HediffDef/Hediffs_Local_Chronic.xml_**
Потеря слуха -> глухота.
Деменция -> слабоумие.
Атеросклероз. По дефам это _сердечная недостаточность_ (тромбоз коронарных артерий): влияет только на сердце и вызывает сердечный приступ (атеросклероз в этом отношении по разнообразней).
- **_HediffDef/Hediffs_Local_Injuries.xml_**
Ожог и обморожение оставляют _рубцы_
Размозжённая рана -> размозжение (и размозжено соответственно).
Царапина -> рваная рана
Огнестрельное ранение -> пулевое ранение и шрам от пули -> след от неё же.
**<SurgicalCut.injuryProps.destroyedLabel>
<SurgicalCut.injuryProps.destroyedOutLabel>
<Bruise.injuryProps.destroyedOutLabel>**
пошли провожать эвтаназию.
- **_HediffDef/Hediffs_Local_Misc.xml_**
ChemicalDamageBrain -> CheChemicalDamage
ChemicalDamageKidney -> ChemicalDamageSevere
Оба теперь характеризуют повреждение от приёма алкоголя и химии (drugs)

**Comment by Elevator89** [comment]
> <Temperature.description>Устройства для управления температурой.</Temperature.description>
> Средства. Костёр не устройство.

> <Outlander.label>город чужеземцев</Outlander.label>
> Они outlander union (союз чужеземцев, чужеземный союз) вообще-то.

> <Outlander.leaderTitle>мэр</Outlander.leaderTitle>
> В оригинале -- prime councilor (первый советник).

> Химический ожог -> накопление токсинов

> Ожог и обморожение оставляют рубцы

> Царапина -> рваная рана

> Euthanasia.label

Со всем этим согласен, сделаю отдельные ишью.
Остальное или переведено хуже, чем сейчас есть, или переведено неверно (не соответствует действительности), или шило на мыло.
