### ISSUE TITLE
Имя хозяина не влезает в кнопку при наличии привязанности

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#553]
![photo_2017-09-16_01-33-04](https://user-images.githubusercontent.com/24602486/30505797-957e9ada-9a7f-11e7-825e-aae90fc78295.jpg)

**Comment by Elevator89** [comment]
Если только не найти **действительно** короткий синоним этого слова.

**Comment by Arex-rus** [comment]
> Ещё сокращать — не хочется, ибо это же слово используется в том числе в местах, где использование сокращений неуместно (места и так хватает).

Не очень понял: этот перевод используется ещё в каких-то строках, не только для кнопки?

**Comment by Elevator89** [comment]
Можно символ сердечка поставить: https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB_%D1%81%D0%B5%D1%80%D0%B4%D1%86%D0%B0#%D0%9A%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D0%B4
