### ISSUE TITLE
Универсальный метал

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#557]
![default](https://user-images.githubusercontent.com/24602486/30506695-b2280dd6-9a86-11e7-816b-051a653ef275.jpg)

**Comment by Elevator89** [comment]
Проблема в том, что сталь — это не металл? Или в том, что нужна двойная "л"?

**Comment by Orontion** [comment]
Нужна двойная "л", орфографическая ошибка.
