### ISSUE TITLE
Нужна тёплая одежда

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#558]
![default](https://user-images.githubusercontent.com/24602486/30506876-18fd011e-9a88-11e7-98ae-146ddc7197b8.jpg)

Данное сообщение не совсем корректно. Оно появляется в тот момент, когда температура УЖЕ опустилась до какого-то уровня, а не сообщает о проблеме в будущем, поэтому стоит переработать описание.

Мой вариант:

"Как минимум у Х ваших поселенцев нет достаточно тёплой одежды для выхода на улицу.

Температура за окном опустилась до YY градусов.

Вы можете..."

**Comment by fiziologus** [comment]
> Данное сообщение не совсем корректно. Оно появляется в тот момент, когда температура УЖЕ опустилась до какого-то уровня, а не сообщает о проблеме в будущем

Всё корректно.
_At least {0} of your colonists will lack warm clothes when the cold season comes._
_All of your colonists will lack warm clothes when the cold season comes._

_The outdoor temperature is going to reach {0}.\n\nYou can tailor warm clothes at the tailoring bench, or buy them from traders._
Здесь 0 -- минимальная расчётная температура **за квадрум** (quadrum), игровой "месяц". Она может и сразу до этой отметки опуститься, а может и после.

А на улицу пешки могут хоть голышом выскакивать, независимо от погоды (Rim делали канадцы, не американцы): переохлаждение (гипотермия) процесс относительно медленный и достаточно безопасный (если не морозить до полусмерти).

PS. Ну вы батенька и Юлий Цезарь: три партии одновременно.

**Comment by Orontion** [comment]
В том и дело, я специально тестировал момент появления сообщения. Когда температура опустилась до -25, сообщение выпало в первый раз на температуру в -25. Затем, в том же квадруме, игровом месяце, температура упала до -27, и сообщение выпало вновь, уже с новым значением. Но когда днём температура поднималась до приемлемых значений - предупреждение пропадало. Вывод - сообщение говорит о текущей температуре на улице, и изначальный английский текст сообщения не соответствует игровой механике. Можно оставить как есть, для соответствия точности перевода, можно изменить, для лучшего игрового опыта.

Лично меня сообщение "Температура опустится до -30! Шей теплые вещи!!!" поначалу сильно смущало, я судорожно начинал готовиться к холодам. А они не наступали, т.к. эти "холода" держались ровно одну ночь, пока поселенцы спали в уютных кроватях, а у меня горело страшное предупреждение.

**Comment by Arex-rus** [comment]
Тоже обращал внимание, что там отображается **текущая** температура.
