### ISSUE TITLE
Стрельба?

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#560]
Навык "стрельба" относится не только к огнестрельному оружию и лукам, но и к гранатам с пилумами. Надо переделать во что-то вроде "дальний бой".

**Comment by fiziologus** [comment]
В оригинале _Shooting_, но с пометкой _Use of all kinds of ranged weapons._

Для броска нужны те же навыки (а у нас **навык**: _дальний бой_ – не навык в широком смысле), что и для стрельбы: особой нестыковки здесь нет.

В конечном итоге "Животноводство" (_Animals_ – _работа с животными_) с приручением тоже не сильно сочетается.

**Comment by Elevator89** [comment]
В жизни если человек хорошо умеет стрелять из винтовки, это не значит, что он может метко кинуть гранату или пилум. И наоборот. 
И тому, и другому нужно учиться, и называть **всё это** одним словом "стрельба" как-то неправильно.
Чем "дальный бой" не навык? Почему тогда навык "ближний бой" не вызывает вопросов?

**Comment by Orontion** [comment]
Мне нравится "Дальний бой", очень точное определение.
