### ISSUE TITLE
[Minor] Slaughter

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#562]
https://github.com/Ludeon/RimWorld-ru/commit/bc036ea17cc14adb0783cdf8f3b69fca1f6e2aed Вначале кололи, теперь бьют.
_Забивают_ скот (массово), а одно-два животных -- **режут**.

**Comment by Elevator89** [comment]
Оба варианта используются. Но "зарезать", очевидно можно только чем-то острым. "Забить" - чем угодно.
Приятного чтения:
https://orchardo.ru/49-kak-zabit-hryushku-samostoyatelno-bez-lishnih-problem-i-nervotrepki.html
http://fermagid.ru/svinovodstvo/84-kak-zarezat-svinyu.html
