### ISSUE TITLE
Шлемы

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#564]
Военный шлем (Military Helmet) превратился в _Simple Helmet_.
Кевларовый шлем (Kevlar helmet) заменён на _Advanced helmet_.

Может и ещё что-то дёрнули: по ходу добавлю.

**Comment by fiziologus** [comment]
- Военный шлем и кевларовый
затронуты _DefInjected/RecipeDef/Recipes_Add.xml _ (Make_\<defName\>.[ label || description ||  jobString] и _DefInjected/ThingDef/Apparel_Hats.xml_
Теперь это
_simple helmet_ (defName _Apparel_SimpleHelmet_) c описанием:
_A simple helmet which gives moderate protection against sharp attacks. Not effective against blunt weapons._
_advanced helmet_ (defName _Apparel_AdvancedHelmet_) с описанием:
_A lightweight combat helmet with a complex design, reinforced with plasteel. Not effective against blunt weapons._
Смотреть _Defs/ThingDefs_Misc/Apparel_Hats.xml_

- винтовка
затронуты _DefInjected/RecipeDef/Recipes_Add.xml _ (Make_<fName>.[ label ||description ||  jobString]  и DefInjected/ThingDef/Weapons_Guns.xml
Нужно заменить defName: было _Gun_SurvivalRifle_, стало _Gun_BoltActionRifle_ (и _Bullet_BoltActionRifle_ у пуль).
Смотреть _Defs/ThingDefs_Misc/Weapons_Guns.xml_

**Comment by Elevator89** [comment]
Будет исправлено при переводе альфы-18
