### ISSUE TITLE
Текущая работа

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#59]
Вот примерный список непереведенных вещей к 0.15 релизу.
Берите себе что хотите, только вот пара условий:
1. Берите за раз не очень много. Лучше от 1 до 3 пунктов.
Чтобы было удобно проверять. Сделаете, проверим, померджим, потом еще набирайте.
2. Отписывайтесь сюда, что себе взяли. Чтобы другие участники видели и не получилось что 2 человека переводили одно и то же.

Я периодически буду список этот подчищать.

#73 **HediffDef/Hediff_Global_Misc.xml** - @Elevator89
DrugOverdose

#72 **JobDef/Jobs_Misc.xml** - @Elevator89
FillFermentingBarrel и TakeBeerOutOfFermentingBarrel

#72 **JobDef/Jobs_Work.xml** - @Elevator89
OperateDeepDrill

#63 **KeyBindingDef/KeyBindings.xml**
TickOnce, ToggleGodMode, ToggleDebugLog,
ToggleDebugActionsMenu, ToggleDebugLogMenu,
ToggleDebugInspector, ToggleDebugSettingsMenu

#73 **MentalStateDef/MentalStates_Mood.xml**
BingingDrugExtreme

 #71 **NeedDefs/Needs_Misc.xml**
Mood, Rest, Joy, Beauty, Comfort, Space (.description)

#73 **RecipeDef/Recipes_Drugs.xml**
MakeWort, BurnDrugs

#64 **ResearchProjectDef/ResearchProjects_Tier1_Misc.xml**
PassiveCooler, DrugProduction

#64 **ResearchProjectDef/ResearchProjects_Tier2_Misc.xml**
CocaRefining, AmphetamineProduction, GoJuiceProduction, MalariBlockProduction (названия поменялись)

#64 **ResearchProjectDef/ResearchProjects_Tier3_Misc.xml**
MedicineProduction

#74 **Scenarios/ScenParts_Various.xml**
SetNeedLevel, CreateIncident

#73 **StatDef/Stats_Pawns_WorkRecipes.xml**
DrugProductionSpeed

#69 **TaleDefs/TalesDoublePawn**
TradedWith

#65 **ThingDef/Buildings_Security.xml**
Bullet_TurretImprovised, BaseArtilleryWeapon, Artillery_MortarBomb
Artillery_MortarIncendiary, Bullet_MortarIncendiary,
Artillery_MortarEMP, Artillery_MortarEMP, Bullet_MortarEMP

#66 **ThingDef/Buildings_Furniture.xml**
TableBase.description, SunLamp

#66 **ThingDef/Buildings_Misc.xml**
GroundPenetratingScanner

#66 **ThingDef/Buildings_Power_WindTurbine.xml**
WindTurbine

#66  **ThingDef/Buildings_Temperature.xml**
PassiveCooler

#67 **ThingDef/Items_Artifacts.xml**
ArtifactBase.comps.0.useLabel

#67 **ThingDef/Items_BodyParts.xml**
BodyPartBase

#67 **ThingDef/Items_Exotic.xml**
Neurotrainer.comps.0.useLabel

#67 **ThingDef/Items_Implants.xml**
ImplantBase

#67 **ThingDef/Items_Luxury.xml**
ResourceBase

#67 **ThingDef/Items_Resource_Manufactured.xml**
Neutroamine

#67 **ThingDef/Items_Resource_RawPlant.xml**
CocaLeaves, MarijuanaLeaves

#67 **ThingDef/Items_Unfinished.xml**
UnfinishedBase

#75 **ThingDef/Plants_Bases.xml**
TreeBase

#75 **ThingDef/Plants_Cultivated_Farm.xml**
PlantCoca, PlantMarijuana

#62 **ThingDef/Races_Animal_Arid.xml**
Muffalo.lifeStages.0.label

#62 **ThingDef/Races_Animal_BigCats.xml**
Lynx.lifeStages.0.label

#62 **ThingDef/Races_Animal_Farm.xml**
Chicken, Pig, Cow

#62 **ThingDef/Races_Animal_Giant.xml**
Elephant.lifeStages.0.label

#62 **ThingDef/Races_Animal_Pet.xml**
YorkshireTerrier.lifeStages.0.label

#62 **ThingDef/Races_Animal_Temperate.xml**
Deer, Ibex, Elk, Caribou

#62 **ThingDef/Races_Animal_Tropical.xml**
Boomalope.lifeStages.0.label

#62 **ThingDef/Races_Animal_WildCanines.xml**
Warg, WolfTimber, WolfArctic, FoxFennec, FoxRed, FoxArctic

#74 **ThingDef/Various_Stone.xml**
StoneBlocksBase.description

#68 **ThingDef/Weapons_Grenades.xml**
BaseEquipment

#68 **ThingDef/Weapons_Guns.xml**
BaseBullet, Bullet_MachinePistol, Gun_MachinePistol

#68 **ThingDef/Weapons_RangedNeolithic.xml**
BaseProjectileNeolithic

#69 **TraderKindDef/TraderKinds_Caravan_Neolithic.xml**
Caravan_Neolithic_Slaver

#69 **TraderKindDef/TraderKinds_Orbital_Misc.xml**
Orbital_BulkGoods, Orbital_Exotic, Orbital_PirateMerchant

#70 **WorkGiverDef/WorkGivers.xml**
Drill, DoBillsProduceDrugs, TakeBeerOutOfFermentingBarrel,
FillFermentingBarrel, DoBillsHaulCampfire

**Comment by Elevator89** [comment]
Возьму первые пять файлов

**Comment by Dinoabunai** [comment]
Да, забыл совсем. Спасибо @KviEt. Все это было добыто его скриптом.

**Comment by KviEt** [comment]
Да без проблем, я вам ещё редактор сделаю если не откажитесь, мне практика, вам помощь, к тому же это ускорит перевод, а значит после выхода новой версии игры перевод для нее будет быстрее готов и можно будет без проблемно играть для тех кто плохо знает английский(в частности мне) (:

**Comment by Dinoabunai** [comment]
Чего ж отказываться. Я думаю это неплохая идея.

**Comment by Dinoabunai** [comment]
@Elevator89 
Я немного изменил твой комментарий, чтобы было понятно что именно ты взял.
Напоминаю - я буду периодически подчищать список, так что не пишите "взял первые два" или что-то подобное. Потому что когда вы их сделаете, я подчищу список и будет казаться что вы взяли другие файлы.

**Comment by Elevator89** [comment]
Разбил скоуп на задачи. Прописал ссылки на задачи. Теперь их можно разбирать самим, не отписываясь здесь и не обновляя список.

**Comment by Elevator89** [comment]
ThingDef/Various_Stone.xml
StoneBlocksBase.description
Это точно нужно переводить? В немецкой версии такого нет. Да и в игре никакой плашки с описанием не отображается на каменных блоках.

**Comment by KviEt** [comment]
@Elevator89 Где ты такое откопал?
У немецкой версии сейчас прилично пропусков... Смысла на них ровняться сейчас нету.
И потом сколько раз кидать ссылку?
Вот [тут](https://github.com/KviEt/RimWorldHelpInTranslation/tree/master/%D0%A2%D1%80%D0%B5%D0%B1%D1%83%D0%B5%D1%82%D1%81%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%B5%D1%81%D1%82%D0%B8%20Ru) можно найти то, что надо перевести
Various_Stone.xml отсутствует по причине того, что это описание находится у абстрактного класса, а то что у абстрактного перевести на данный момент нельзя.

**Comment by Elevator89** [comment]
@KviEt 
Так тут и откопал, в текущей работе. Не сам же придумал. 
Вообще, будет лучше, если мы выделим человека, ответственного за постановку заданий.

**Comment by KviEt** [comment]
@Elevator89 
Видимо человек использовал старую версию скрипта, которая совсем не смотрела абстрактный класс или производный, а писала все тэги которые найдет...
[Здесь](https://github.com/KviEt/RimWorldHelpInTranslation/releases) последняя версия программы, распаковываешь в любую папку, в эту же папку добавить Defs и DefInjected с переводом и она тебе скажет, чего не хватает.

**Comment by Dinoabunai** [comment]
Да, я ее и использовал. Там еще и старые марихуана и кокейн и амфетамин.

**Comment by KviEt** [comment]
Не вижу случаев, чтобы программа 0.7.0 упоминала об Various_Stone.xml.

**Comment by KviEt** [comment]
Папку конечно надо обновить, просто я когда вижу. что пулы весят, мне не хочется...

**Comment by Dinoabunai** [comment]
Да не, я просто взял изменения еще с твоего пул-реквеста, когда родились ветки a15 и Alfa-15-Clean

**Comment by KviEt** [comment]
С того времени уже много чего поменялось... ^^)

**Comment by Dinoabunai** [comment]
Ага. Доделаем это, запустим новый, проверим еще раз.

**Comment by Ohar** [comment]
Этот мегасписок вроде как надо почистить, порезать на отдельные ишью и закрыть. Он большой, страшный и непонятно как к нему подступаться.

**Comment by Dinoabunai** [comment]
@Ohar @Elevator89 
Его бы закрыть уже наверное, он неактуален.

**Comment by Ohar** [comment]
Взял #75

**Comment by Elevator89** [comment]
Неактуально. Закрываю.
