### ISSUE TITLE
"Мелкий" феодал

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#596]
"Мелкий феодал" - один из заголовков бэкстори для периода детства. 
Этот феодал мелкий не потому что у него мало земель, а по возрасту.

**Comment by Dimonasdf** [comment]
Привет.
Какие унижения ты предусмотрел для несчастного мелкопоместного лорда на этот раз?

**Comment by Elevator89** [comment]
И так мелочью обозвали! Что самое обидное, это правда. Какие ещё нужны унижения?

**Comment by Orontion** [comment]
Юный феодал

**Comment by Elevator89** [comment]
Исправлено коммитом 35091778beb55b1d334fb30d0e7f31a3c29e5f32
