### ISSUE TITLE
«Строится»

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#608]
Фраза "спальный мешок (строится)" и налогичные ей выглядят и звучат нелепо. Надо придумать для каждой такой "стройки" индивидуальное описание. Перевод это сделать позволяет. 
Файл с нужными описаниями находиться здесь: "DefInjected\ThingDef\_ThingDef_BlueprintsAndFrames.xml"

**Comment by Dimonasdf** [comment]
Находится.

Каждому blueprint и frame можно присвоить свой процесс?

**Comment by Elevator89** [comment]
> Каждому blueprint и frame можно присвоить свой процесс?

Да. Только пока непонятно как это в игре отображаться должно
