### ISSUE TITLE
Древесина кровать

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#611]
![default](https://user-images.githubusercontent.com/24602486/32415672-6543ac2e-c24e-11e7-90fa-63fc1b935d62.jpg)
По-видимому, изменился способ наименования материала предмета.

**Comment by Elevator89** [comment]
Не изменился. Остался таким же кривым как был
```	
public override string Label
{
	get
	{
		string text = this.def.entityDefToBuild.label + "FrameLabelExtra".Translate();
		string result;
		if (base.Stuff != null)
		{
			result = base.Stuff.label + " " + text;
		}
		else
		{
			result = text;
		}
		return result;
	}
}
```
Строка для материала прошита в коде. На это, к сожалению, мы повлиять не можем.
