### ISSUE TITLE
Вкладка "Бой"

### ISSUE THREAD

**Issue by Orontion** [Ludeon/RimWorld-ru#615]
![default](https://user-images.githubusercontent.com/24602486/32417818-2464bc8a-c270-11e7-90d5-ac7e7d7f579b.jpg)

Действия боя не переведены совсем.

**Comment by Elevator89** [comment]
За это отвечают RulePackDef'ы. Ишью 570-580. Их я оставил на закуску, ибо там весьма непросто всё.
