### ISSUE TITLE
Animal Races

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#62]
**ThingDef/Races_Animal_Arid.xml**
Muffalo.lifeStages.0.label

**ThingDef/Races_Animal_BigCats.xml**
Lynx.lifeStages.0.label

**ThingDef/Races_Animal_Farm.xml**
Chicken, Pig, Cow

**ThingDef/Races_Animal_Giant.xml**
Elephant.lifeStages.0.label

**ThingDef/Races_Animal_Pet.xml**
YorkshireTerrier.lifeStages.0.label

**ThingDef/Races_Animal_Temperate.xml**
Deer, Ibex, Elk, Caribou

**ThingDef/Races_Animal_Tropical.xml**
Boomalope.lifeStages.0.label

**ThingDef/Races_Animal_WildCanines.xml**
Warg, WolfTimber, WolfArctic, FoxFennec, FoxRed, FoxArctic

**Comment by Dimonasdf** [comment]
Это не нужно. Стейджи расположены в DefInjected\PawnKindDef.
См. сверху:
```
  <ThingDef ParentName="AnimalThingBase">
    <defName>Muffalo</defName>
    <label>muffalo</label>
```
И:
```
  <PawnKindDef Name="Muffalo" ParentName="AnimalKindBase">
    <defName>Muffalo</defName>
    <label>muffalo</label>
```

**Comment by Dinoabunai** [comment]
Надо будет потестить. Если в теге написано ThingDef, то и лежать оно по идее должно в ThingDef.

**Comment by Dimonasdf** [comment]
А если нет, то нет. Это из одного файла строки.

**Comment by Dinoabunai** [comment]
Значит и туда и сюда надо. Надо проверить.
