### ISSUE TITLE
[idea] tribal headdress

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#620]
[Малахай](https://www.google.ru/search?q=%D0%BC%D0%B0%D0%BB%D0%B0%D1%85%D0%B0%D0%B9&newwindow=1&dcr=0&biw=1916&bih=996&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjE7fCvl7bXAhWJdpoKHTNzBrsQsAQIRA)
Что-то наподобии в фильмах с Гойко Митич проскакивало, если сколероз не изменяет.

И чтобы не плодить темы. _Psychoid Pekoe_ или Mate de Coca в реальности -- чай (настой) из листьев коки. **Настой психолиста** (по названию понятно, что в чан кидают, да и вариаций рецепта (кора, корни etc) нет), который готовят при заваривании (label -- _приготовить настой_, desc -- _заварить_).

**Comment by Elevator89** [comment]
Не надо быть знатоком, чтобы отличить малахай, который делают из шкуры животного, от бутафорского головного убора из ткани, которому лишь придали вид головы животного.
