### ISSUE TITLE
[low] ikwa

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#621]
[иклва](https://upload.wikimedia.org/wikipedia/it/9/98/Shaka_Zulu_incisione_ottocentesca.jpg), укороченный зулусский дротик (ассегай) для культурного (и не очень) обмена в рукопашной.

[Ещё фотка](http://kstk71.livejournal.com/407918.html)

[Википедия](https://ru.wikipedia.org/wiki/Ассегай)

**Comment by Elevator89** [comment]
Иква - частный случа ассегая. Не вижу причин вносить какие-либо изменения в перевод.
http://www.rulit.me/books/ona-i-allan-read-391034-2.html
http://popgun.ru/viewtopic.php?f=335&t=615304&start=6150
