### ISSUE TITLE
Research Projects

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#64]
**ResearchProjectDef/ResearchProjects_Tier1_Misc.xml**
PassiveCooler, DrugProduction

**ResearchProjectDef/ResearchProjects_Tier2_Misc.xml**
CocaRefining, AmphetamineProduction, GoJuiceProduction, MalariBlockProduction (названия поменялись)

**ResearchProjectDef/ResearchProjects_Tier3_Misc.xml**
MedicineProduction

**Comment by Dimonasdf** [comment]
Обновить всю DefInjected\ResearchProjectDef.

**Comment by Dimonasdf** [comment]
Requested pull #82.

**Comment by Dimonasdf** [comment]
Done.
