### ISSUE TITLE
Security Buildings

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#65]
**ThingDef/Buildings_Security.xml**
Bullet_TurretImprovised, BaseArtilleryWeapon, Artillery_MortarBomb
Artillery_MortarIncendiary, Bullet_MortarIncendiary,
Artillery_MortarEMP, Artillery_MortarEMP, Bullet_MortarEMP

**Comment by Dinoabunai** [comment]
Беру.

**Comment by Dinoabunai** [comment]
Это все уже переведено, только рассовано по разным файлам.
Единственное что описание ловушек сильно упрощено по сравнению с оригиналом.

@Dimonasdf @Elevator89 
Может стоит привести файлы по образу оригинальных Defs, чтобы было легче искать?

**Comment by Dimonasdf** [comment]
Подробнее идею, что значит "привести файлы по образу оригинальных Defs"?

**Comment by Dinoabunai** [comment]
Засунуть все переведенные файлы в **ThingDef/Buildings_Security.xml**

**Comment by Dimonasdf** [comment]
???
Нет.
И где тут связь с оригинальными? В оригинале всё разложено по папкам с индексами _Buildings, _Items, _Misc. Зачем сливать все файлы папки в один файл?

**Comment by Dinoabunai** [comment]
В оригинальных Defs все что касается Buildings_Security лежит в Buildings_Security.xml.
А у нас в 4 разных местах.

**Comment by Dimonasdf** [comment]
Так, идея уже начинает обретать форму и нравиться. Если бы ещё были картинки/цитаты, было бы вообще супер.

**Comment by Dinoabunai** [comment]
Например у нас:
**Sandbags** в **Buildings_Security.xml**
**Bullet_MortarBomb** в **Weapons_Artillery.xml**
**Bullet_TurretImprovised** в **Weapons_Guns.xml**

А в оригинале **Sandbags**, **Bullet_MortarBomb** и **Bullet_TurretImprovised** все находятся в **Buildings_Security.xml**

**Comment by Elevator89** [comment]
Задание перенесено в #111
