### ISSUE TITLE
TerrainDef/Terrain_Floors.xml 

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#653]
Перепутаны Limestone_* и Slate_* секции (первое известняк, второе сланец, а не наоборот).

В принципе можно использовать здесь генерацию самим движком. Лекала для _Rough_, _RoughHewn_ и _Smooth_ (и не только) берутся из _Keyed/Misc.xml_:

\<RoughStoneTerrainLabel\>грубый {0}\</RoughStoneTerrainLabel\>
\<RoughStoneTerrainDesc\>Грубая природная основа из {0}а.\</RoughStoneTerrainDesc\>
\<RoughHewnStoneTerrainLabel\>обтёсанный {0}\</RoughHewnStoneTerrainLabel\>
\<RoughHewnStoneTerrainDesc\>Естественный пол из грубо обтёсанного {0}а.\</RoughHewnStoneTerrainDesc\>
\<SmoothStoneTerrainLabel\>гладкий {0}\</SmoothStoneTerrainLabel\>
\<SmoothStoneTerrainDesc\>Гладкий природный пол из {0}а.\</SmoothStoneTerrainDesc\>

А в файле оставить только неукладывающиеся в лекала случаи.

**Comment by fiziologus** [comment]
Дополнение.
Лекала можно смело выкинуть: движок подставляет в них **нелокализованные** "камни" (баг на уровне самого движка и припарками не лечится). Зато можно не переводить _description_: их содержимое нигде не отображается.

**Comment by Elevator89** [comment]
Исправлено коммитом 601441a8fde8ecb7de7ab04c63d14db0fd6e7249
