### ISSUE TITLE
Кривой шаблон в сообщении о переговорах

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#656]
![610ba-clip-20kb](https://user-images.githubusercontent.com/21694533/33374692-36679898-d518-11e7-944b-6e2b4580d92e.jpg)

**Comment by fiziologus** [comment]
_DefInjected/IncidentDef/Incidents_Quests.xml_
**QuestPeaceTalks.letterText** ---> NAME, {0} фракции {1}

Не сильно оно и critical. Так, опечатка.

**Comment by Elevator89** [comment]
Опечатка, которая делает текст нечитаемым. Исправишь?
