### ISSUE TITLE
Various Buildings

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#66]
**ThingDef/Buildings_Furniture.xml**
TableBase.description, SunLamp

**ThingDef/Buildings_Misc.xml**
GroundPenetratingScanner

**ThingDef/Buildings_Power_WindTurbine.xml**
WindTurbine

**ThingDef/Buildings_Temperature.xml**
PassiveCooler

**Comment by Dinoabunai** [comment]
@Elevator89 
Может закрыть это задание. Оно дублируется в #131.

**Comment by Elevator89** [comment]
Определённо
