### ISSUE TITLE
Комментарии к @92c13c59d (cryptosleep_revival_briefing_trans: grammar & syntax fixes)

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#677]
- строка 34. _они необитаемы, как и все **планеты их до** первого посещения людьми._ Их -- это чьи?
- строка 40. Не в **пелену**, что взор застилает, а в **пеленА** (пелёнки).
- строка 61. Просто _инопланетяне_, не надо **эти**. Других в мире RimWorld нет: либо люди, либо ксенолюди (о чём и говорится).
- строка 65. _gene-sampled_ --  **семплировала** (здесь калька с оригинала нужна), неологизм уже устоявшийся.
- строка 77. **Наш** ИИ. Наблюдает ИИ, созданный по архитектуре субличности (смотреть ниже по тексту), а не (суб)личность в виде ИИ (в мире игры это архотек, всё остальное всего лишь программный код со своими ограничениями).
- строка 95. **Мирные по натуре**: кажется или запятая всё-таки не нужна.  _Старый трумбо -- создание, **попусту (просто) предпочевшее** не разговаривать_. А не _продпочевшее попусту (в пустую) не разговаривать_.
- строка 128. _Они **так же** совершают множество ошибок. **Так, как и люди**, или всё-таки **также, как и люди**.
- строка 141. Тройное **которую** -- усилительный оборот _(который я лично уже давно нигде не вижу, как и много другое)_, не ошибка. Не надо его убирать, смягчая фразу.

За остальное -- спасибо (либо "и так сойдёт"), выправить здесь ошибки самому возможности не дали.

И от себя довески.
- строка 124. Фон Нейман не создавал никаких классификаций. Личность достаточно известная, особенно в математических кругах. _genius-level intellects in the Von Neumann class_ -- интеллект-гений класса (в классе) Фон Нейман.
- строка 68. Если уж хочется тащить кальку, то не **признаки Менделя**, а **Менделевы признаки** (больше известные как **генетически устойчивые**, ака доминантные и рецессивные).
- строка 54. Всё больше склоняюсь, что drive -- это _привод_, а в обычных условиях летают по старинке, на реактивной тяге. Лучше в этом месте в скобках оставить оригинал из-за неоднозначности трактовки.

**Comment by Arex-rus** [comment]
> то не признаки Менделя, а Менделевы признаки

> Признаки, наследование которых подчиняется перечисленным закономерностям, принято называть менделирующими (по имени Г. Менделя).

http://studopedia.org/5-105257.html

**Comment by Arex-rus** [comment]
> gene-sampled -- семплировала (здесь калька с оригинала нужна), неологизм уже устоявшийся.
сомневаюсь, что его стоит использовать вне специализированной литературы.

**Comment by Arex-rus** [comment]
> Мирные по натуре: кажется или запятая всё-таки не нужна.

Допустимо и без неё, но с ней лучше смысл передаётся.

**Comment by Arex-rus** [comment]
> строка 128. _Они так же совершают множество ошибок. Так, как и люди, или всё-таки также, как и люди.

В оригинале "just like people"
just like - точно так же как, почти такой же (как)
