### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#68]
**ThingDef/Weapons_Grenades.xml**
BaseEquipment

**ThingDef/Weapons_Guns.xml**
BaseBullet, Bullet_MachinePistol, Gun_MachinePistol

**ThingDef/Weapons_RangedNeolithic.xml**
BaseProjectileNeolithic

**Comment by Dimonasdf** [comment]
Requested pull #80. Проверяйте.

**Comment by Elevator89** [comment]
Перенесено в #111
