### ISSUE TITLE
Dialogs_Various.xml BillRequiresNutrition

### ISSUE THREAD

**Issue by fiziologus** [Ludeon/RimWorld-ru#685]
\<BillRequiresNutrition\>Requires {0} nutrition\</BillRequiresNutrition\>

_\<BillRequiresNutrition\>Требуется {0} ресурса\</BillRequiresNutrition\>_

Используется в заданиях для блюд. Нужно суммарно набрать продуктами столько _nutrition_, само количество продуктов может быть произвольным (в ваниле 10 единиц для простого блюда: 0.5=0.05х10).

**Comment by Arex-rus** [comment]
Из данного описания не понятно, что именно в текущей редакции не правильно и как нужно изменить. Мне, по крайней мере...
