### ISSUE TITLE
Drugs - наркотики?

### ISSUE THREAD

**Issue by Arex-rus** [Ludeon/RimWorld-ru#687]
Во многих местах drugs переведено как наркотики, но кое-где имеется их значение также как лекарство. Возможно, имеет смысл заменить "наркотики" на "препараты", кроме тех случаев, где явно подразумевается наркотический эффект?

**Comment by fiziologus** [comment]
Drugs уже препараты при #518, просто не везде синхронизировано.
Термин в игре (и в языке) многозначный: это и наркотики, и медпрепараты, и алкоголь -- и "кроме тех случаев, где явно подразумевается наркотический эффект" не всегда получится, люциферий не наркотик (это стимулятор), но обладает сильнейшей аддиктивностью, Psichite pekoe тоже не наркотик, как и "косяк" (хотя лучше "скрутка" (joint очень неоднозначный в переводе термин), дымолист в нынешнем состоянии что-то среднее между коноплёй и махрой, а "косяк" больше относится к первой), но оба могут вызвать привыкание (а это только ванила, если прихватить XML-моды (а на них тоже стоит посматривать: механику они не меняют и строки перевода встанут только так) может стать ещё веселее).

**Comment by Elevator89** [comment]
Пиво, дымолист, отвар, хлопья, порошок психина, Go-сок, люциферий, пеноскицилин - это всё "drugs".
Как перевести?
"Препараты"? Пиво, косяк и отвар психина - такие себе "препараты".
"Лекарства"? То же самое.
"Наркотики"? Пеноксицилин и люциферий несколько выбиваются из ряда.
"Вещества"? "Химия"?

**Comment by fratfoxid** [comment]
думаю "Препараты" подходят в точку. все наркотики изначально являлись именно препаратами, это и морфин и героин и уж тем более марихуана. препаратами являются и разнообразные отвары, вещества, и синтетического происхождения и природного происхождения, например травы. спирт, по сути, тоже препарат. он содержится в пиве, но пиво тут в меньшинстве, а все остальное даже по логике игры является препаратами. например от психических заболеваний или стрессов или как стимуляторы или болеутоляющие. даже описание нам об этом говорит, все дело в том, что они вызывают привыкание, а синдром отмены сами знаете что такое, это медицинский термин. но это лишь мое, скромное мнение.

**Comment by Elevator89** [comment]
Исравлено: 96ed328da1aebdcc443171253b7607f542c63ffc
