### ISSUE TITLE
Карибу -> северный олень?

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#688]
Предлагаю заменить экзотического "карибу" на привычного "северного оленя". В этом случае можно будет использовать краткие исторические названия для самцов, самок и детёнышей: рогач, важенка, пыжик.

**Comment by Elevator89** [comment]
Кстати, для детёнышей старше месяца есть не менее замечательное особое название — неблюй.

**Comment by Arex-rus** [comment]
> Кстати, для детёнышей старше месяца есть не менее замечательное особое название — неблюй

... или неплюй.

А пыжиком всё-таки обычно называют мех, а не самих детёнышей.

**Comment by Arex-rus** [comment]
то есть какие предлагаются варианты:
северный олень
северные олени
неплюй
молодой рогач
молодая важенка
рогач
важенка

**Comment by fiziologus** [comment]
Важенка (тёлая самка) и рогач -- взрослые (_lifestage.3_) особи.

> Кстати, для детёнышей старше месяца есть не менее замечательное особое название — неблюй.

_Сев. олень родится теленком, осенью он неблюй, или пыжик; перегодовав, лопанко и лоншак, а самка сыри́ца; отелившаяся, важенка, матка; яловая, молодая, вонделка, старая_
Тут простор большой, как-никак давно одомашненое животное.
