### ISSUE TITLE
Гигантский ленивец -> мегатерий?

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#689]
В патче 16 авторы игры переименовали "megatherium" (мегатерия) в "megasloth" (гигантского ленивца). Перевод также поменяли.
Однако "гигантский ленивец" слишком длинное и невыразительное сочетание (в отичие от оригинала, где второй вариант короче, чем изначальный).
Предлагаю переименовать его обратно в "мегатерия".

**Comment by fiziologus** [comment]
**мегаленивец**
Не надо лезть в холодную войну megatherium vs megasloth. (megasloth, как и дымолист позволили уйти от реальных примеров к более абстрагированным).

**Comment by Arex-rus** [comment]
Я тоже этот вариант предлагал, но Андрею он чем-то не нравится.

Выдержка из чата.
Arex, [21.12.17 20:31]
молодой мегаленивец?

Андрей Лёмин, [21.12.17 20:32]
лучше уж тогда мегатерия вернуть, как раньше было

Андрей Лёмин, [21.12.17 20:33]
ральше был "megatherium", а потом он стал "megasloth"

Arex, [21.12.17 20:33]
а переводился как?

Андрей Лёмин, [21.12.17 20:34]
"мегатерий" и "гигантский ленивец" соответственно

Андрей Лёмин, [21.12.17 20:36]
ну или "мегатерия" вернуть

Arex, [21.12.17 20:35]
так что думаешь насчёт мегаленивца?

Андрей Лёмин, [21.12.17 20:35]
плохо думаю

Андрей Лёмин, [21.12.17 20:36]
лучше уж сокращать до "гиг. ленивца", когда сокращение будет оправданным

**Comment by fiziologus** [comment]
> Я тоже этот вариант предлагал, но Андрею он чем-то не нравится.

Привыкайте, м-м мыслит только двумя критериями: моё и плохо -- искать золотую середину, либо, на худой конец, консенсус мы не приучены и не умеем. Оттого в команде и осталось, сколько осталось.

Не вижу ничего плохого в мегаленивце (если плохо, то и мегаскарабея надо менять): коротко, абстрагировано и, по сути, тот же мега-териум (более правильное имя), но обрусевший.

**Comment by Arex-rus** [comment]
> тот же мега-териум (более правильное имя)
латинские окончания -ium и -ius принято при переводе заменять на -ий, а -us вообще не переводить.
Исключения бывают (аквариум, террариум, стилус), но это именно исключения.

**Comment by Elevator89** [comment]
«Месье» Физиологус, кажется, всё так и не научится корректному общению. Не привнеся в проект практически ничего полезного, кроме срачей и неконструктивных комментариев, пытается выглядеть очень важным и навязать всем своё бесценное мнение, делает далеко идущие выводы о том, почему «в команде и осталось, сколько осталось». Пользуясь случаем, хочу сообщить, что участие в проекте полностью добровольное. Говоря простым языком, тебя здесь никто не держит. А хамство уважения к тебе тут точно не прибавит.

По делу. Делать совсем уж прямые кальки типа "мегаленивца" при наличии энциклопедически верного"гигантского ленивца" считаю ничем не оправданным. Итого, есть два приемлемых варианта: "мегатерий" и "гигантский ленивец".

**Comment by fiziologus** [comment]
> Не привнеся в проект практически ничего полезного, кроме срачей и неконструктивных комментариев

Которые появляются, когда в обсуждение вступает месье Лёмин. Без него, даже несмотря на наличие месье Физиологус, обсуждения идут, хоть и недолго, так как быстро закрываются месье Лёмин без всяких объяснений, во вполне конструктивном русле. И месье Физиологус пытался привнести в проект что-то полезное, но быстро понял, что для этого нужно вначале облобызать седалище месье Лёмин, что неприемлемо для месье Физиологус по идейным соображениям.
> пытается выглядеть очень важным и навязать всем своё бесценное мнение

Этим как раз занимается месье, что кстати видно из второго ответа в нитке. Месье Фисиологус как раз абсолютно всё равно примется его предложение или нет.
> Пользуясь случаем, хочу сообщить, что участие в проекте полностью добровольное. Говоря простым языком, тебя здесь никто не держит.

Ещё раз хочу напомнить страдающему выборочным сколерозом месье Лёмин, что не являюсь частью команды проекта, да и выводы относительно чего-либо могу делать любые, так как слобода мнения. И указывать, что я должен и не должен говорить мне никто не в силах. (Да проект добровольный, но я впервые увидел, чтобы почти вся команда так синхронно из него вышла, что наводит, вкупе с просмотренными старыми ишью, на нехорошие мысли, что против шерсти в текущей ситуации лучше не чесать. О чём и предупреждаю новоприбывшего).

Ладно перейдём от одних баранов к другим.
> Делать совсем уж прямые кальки типа "мегаленивца" при наличии энциклопедически верного"гигантского ленивца" считаю ничем не оправданным.

Megasloth, как и Megaspider -- названия существа (как, скажем, морской огурец, либо морской заяц), не имеюго (причём специально) привязки к какому-либо конкретному существу, в отличии от реально существовавших мегатериев (про прямые кальки можно напомнить про муффало, которые вполне узнаваемо переводятся, а насчёт энциклопедичности -- #688, это разные подвиды). То есть мегатерий (который, к слову, только один из трёх представителей гигантских ленивцев) сразу отпадает. Остаются абстрактный мегаленивец и чуть менее абстрактный ленивец гигантский, который и используется в текущий момент. Итого: имитация бурной деятельности как в #596.

**Comment by Elevator89** [comment]
> Которые появляются, когда в обсуждение вступает месье Лёмин. Без него, даже несмотря на наличие месье Физиологус, обсуждения идут, хоть и недолго

> выводы относительно чего-либо могу делать любые, так как слобода мнения. 

> И указывать, что я должен и не должен говорить мне никто не в силах.

Из поведения и слов месье Физиологуса становится всё более очевидно, что месье считает целью проекта не перевод, а обсуждение его, месье, инициатив.

> И месье Физиологус пытался привнести в проект что-то полезное

Месье Физиологус немного переоценивает полезность своих замечаний и гораздо более сильно — качество своего перевода.

> Месье Фисиологус как раз абсолютно всё равно примется его предложение или нет.

Правда? Тогда к чему все эти дискуссии длиной в сотни комментариев с переходом на личности?

> обсуждения идут, хоть и недолго, так как быстро закрываются месье Лёмин без всяких объяснений

Это уже прямая ложь. Ко всем закрываемым ишью были даны комментарии.

> нужно вначале облобызать седалище месье Лёмин, что неприемлемо для месье Физиологус по идейным соображениям

В третий раз напомню: тебя здесь никто не держит. Напротив, думаю, участники будут рады, если месье добровольно избавит проект от свеого непрекращающегося хамства.
Возвращаясь от фантазий месье Физиологуса к реальности, хочу напомнить, что в данном проекте есть человек, который занимается локализацией игры уже больше года. Который перевёл большую часть контента 15, 16, 17 и 18 версий игры. И, да, пока что именно он отвечает за итоговое качество перевода и мердж изменений, производимый другими участниками. Если ты считаешь такое положение вещей неприемлимым для себя, то возвращаемся к предыдущему пункту: тебя здесь никто не держит.

> Ещё раз хочу напомнить страдающему выборочным сколерозом месье Лёмин, что не являюсь частью команды проекта, да и выводы относительно чего-либо могу делать любые, так как слобода мнения. И указывать, что я должен и не должен говорить мне никто не в силах. (Да проект добровольный, но я впервые увидел, чтобы почти вся команда так синхронно из него вышла, что наводит, вкупе с просмотренными старыми ишью, на нехорошие мысли, что против шерсти в текущей ситуации лучше не чесать. О чём и предупреждаю новоприбывшего).

Напомню страдающему аналогичной формой склероза Физиологусу, что в данном проекте нет такого понятия как "команда". Есть участники, которые на протяжении уже долгого времени приходят и уходят, независимо друг от друга и каждый по своим личным причинам. Никого ни к чему принуждать и заставлять здесь никто не собирается.

**Comment by Elevator89** [comment]
Пусть останется как есть. Оно никому не мешает.
