### ISSUE TITLE
Traders

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#69]
**TraderKindDef/TraderKinds_Caravan_Neolithic.xml**
Caravan_Neolithic_Slaver

**TraderKindDef/TraderKinds_Orbital_Misc.xml**
Orbital_BulkGoods, Orbital_Exotic, Orbital_PirateMerchant

**TaleDefs/TalesDoublePawn**
TradedWith

**Comment by Dimonasdf** [comment]
Протестируем новообретённые знания.

**Comment by Dimonasdf** [comment]
Сделано.
