### ISSUE TITLE
Work Givers

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#70]
**WorkGiverDef/WorkGivers.xml**
Drill, DoBillsProduceDrugs, TakeBeerOutOfFermentingBarrel,
FillFermentingBarrel, DoBillsHaulCampfire

**Comment by Dinoabunai** [comment]
@Elevator89 
Можно это задание закрыть. Задача дублируется в https://github.com/Ludeon/RimWorld-ru/issues/112.

**Comment by Elevator89** [comment]
Ага
