### ISSUE TITLE
Backstories: повествование в настоящем времени

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#700]
Переход на настоящее время даст полную независимость от пола персонажа и избавит от необходимости пользоваться отвратительно выглядящими скобками вида (а), (ла), (ась).
Пример:
`После того, как NAME бросили родители, HE оказывается на улице. HECAP меняет полдюжины мест работы, прежде чем HIS берут юнгой на пиратский корабль, где HIM приходится заниматься всей грязной работой.`
Полезная статья по теме: http://www.bibliotekar.ru/russkiy-yazik-2/165.htm, искать "Настоящее информирующее"

**Comment by fiziologus** [comment]
Ась/лась (и рода с падежами) можно отдать на откуп движку (как в своё время отдали дни и часы): механика генерации текста (LanguageWorker) это позволяет -- но нужна реализация. Как временно-постоянная мера (сам подумывал, уж больно тяжело иногда строки собирать) очень даже.
