### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#72]
**JobDef/Jobs_Misc.xml** - @Elevator89
FillFermentingBarrel и TakeBeerOutOfFermentingBarrel

**JobDef/Jobs_Work.xml** - @Elevator89
OperateDeepDrill

**Comment by Dinoabunai** [comment]
@Elevator89 
Вроде сделано: https://github.com/Ludeon/RimWorld-ru/pull/76

**Comment by Ohar** [comment]
Помержено → к закрытию
