### ISSUE TITLE
Plants

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#75]
**ThingDef/Plants_Bases.xml**
TreeBase

**ThingDef/Plants_Cultivated_Farm.xml**
PlantCoca, PlantMarijuana

**Comment by Ohar** [comment]
`Plants_Cultivated_Farm.xml` вроде как [переведён](https://github.com/Ludeon/RimWorld-ru/blob/master/DefInjected/ThingDef/Plants_Cultivated_Farm.xml).

Взял на перевод `Plants_Bases.xml`

**Comment by Ohar** [comment]
Это всё?

**Comment by Dinoabunai** [comment]
@Ohar 

> Plants_Cultivated_Farm.xml вроде как переведён.

Нет, добавились новые растения. Нужно найти какие и добавить туда перевод.
По памяти это Psychoid и Smokeleaf. Может еще что-то. Проверь по оригинальным Defs.

> Это всё?

Если перевел эти файлы и потестил в игре, то да.

**Comment by Dinoabunai** [comment]
@Ohar 
Если надо чего подсказать - я в телеграме сейчас сижу. Заходи.

**Comment by Dinoabunai** [comment]
@Elevator89 
Может закрыть? Задание дублируется в #134.

**Comment by Elevator89** [comment]
> Может закрыть? Задание дублируется в #134.

Судя по количеству коммитов, видимо, нет

**Comment by Elevator89** [comment]
Закрываю. Действительно дублируется. См. пулреквест #125
