### ISSUE TITLE
Криптосон - криосон?

### ISSUE THREAD

**Issue by Apelsinka223** [Ludeon/RimWorld-ru#770]
https://ru.wiktionary.org/wiki/криосон

**Comment by Elevator89** [comment]
В оригинале - cryptosleep. Такой вот внутриигровой неологизм.

**Comment by Elevator89** [comment]
Это **крипто**сон Пруфы:
https://ludeon.com/forums/index.php?topic=2933.msg65862#msg65862
https://ludeon.com/forums/index.php?topic=18320.msg201174#msg201174
