### ISSUE TITLE
"Глубинное месторождение выработано..."

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#833]
В сообщениях вылезает слишком длинный текст, которые не помещается на экран. Надо написать Тайнену, чтобы заменили сообщение на другое.
![default](https://user-images.githubusercontent.com/21694533/42522966-1e18f464-8475-11e8-80bc-f84b5cba2732.png)

**Comment by Dimonasdf** [comment]
"это месте" - подставное? Если нет, то можно исправить.
"только обломок известняка" - видимо, подставное.
