### ISSUE TITLE
Налёт

### ISSUE THREAD

**Issue by Humort** [Ludeon/RimWorld-ru#837]
Хотел возмутиться по поводу файла "RaidStrategies", но видимо здесь я ничего не добьюсь, пойду писать свой мод...

**Comment by Elevator89** [comment]
Во-первых, в приказном тоне здесь не общаются. 
Во-вторых, хочешь изменений - создай пулреквест.
В третьих, в оригинале везде стоит "Raid". Для каждого типа налёта использовать разные слова, одинаковые по значению, не вижу ни малейшего смысла.

Кстати, "Siege" переведена как "Осада", так что не надо тут возмущаться.

**Comment by Elevator89** [comment]
Этот вопрос уже обсуждался: https://github.com/Ludeon/RimWorld-ru/issues/372

**Comment by Humort** [comment]
Давай лучше, продолжим ругаться здесь. Чем в твоём сообществе. Так будет правильней. Ещё раз говорю можешь удалить ту тему, она тебе не на руку.

**Comment by Humort** [comment]
Так вот, по поводу налётов.
Налёт это моментальное нападение, враги не будут тусоваться всю ночь в ожидании лучшего времени.  Они просто нападут, по этому данный вариант никак не подходит.
Я переводил этот момент и по этому имею право требовать вернуть его как было, при этом делал это дважды и каждый раз какой-то мудрец откатывает мои изменения.
В то время когда я переводил, там было больше тонкостей, и как раз таки это всё подчёркивалось, считаю этот примитивизм, упущением со стороны разработчиков. 
Рекомендую всё же вернуть мой вариант, он гораздо лучше и чётче описывает события, которые должны будут происходит во время нападения. Ну или раз уж так сильно ломает, то уж хотя бы изменить на более подходящее слово. Лично я ухожи разбираться с переводом в моде, Мне не прельщает каждый раз сраться с каждым новым переводчиком, из-за каждой строки....

**Comment by Elevator89** [comment]
Предыдущий комментарий был порезан. И впредь неадекватный поток сознания будет удаляться из обсуждений.

**Comment by Humort** [comment]
Да ради богов, твоё сообщество, твори в нём, что тебе вздумается,  только не считай себя Богом, а то уже говоришь как судья-палач, а ля "порезан", "будет удаляться!".... не тем меня пугаешь) тебе напугать меня вообще нечем) по этому будь по проще) и кстати, с социальными описаниями, как я посмотрю, ты захлебнулся? У меня скопируешь через пол часика или сам будешь ручками накатывать с других переводов?)

**Comment by Elevator89** [comment]
Историю комментариев теперь можно просматривать. Но откровенный мусор буду убирать для пользы проекту локализации.
Если ты считаешь себя официальным переводчиком и хочешь помочь в работе над локализацией, то советую убавить фамильярности в тоне и научиться вежливо общаться.
Если нет — тогда зачем ты сюда пришёл и отнимаешь своё и чужое время?
Пытаешься обвинить в плагиате? Пруфы — в студию!

**Comment by Humort** [comment]
Какой такой плагиат? Только не говори мне, что никто ни у кого не смотрит код, это нормально, учитывая что идёт разработка одного проекта. Я уже долопатил в своём моде, упавшую вкладку социума и прямо предлагаю взять этот код у меня, чтобы не делать лишние шаги, хотя тебе гордость вряд ли позволит это сделать...., 
А теперь, по поводу фамильярности...., ты ведёшь себя, как будто руководитель проекта, хотя являешься таким же переводчиком как и я, ничем не больше и ничем не лучше, это во первых. Во вторых, разве не фамильярность, общаться в таком тоне, с человеком, который как минимум на десяток лет старше тебя? В третьих, для начала сам научить общаться вежливо, а потом требуй этого от других.
Да, я потребовал чтобы мою работу не игнорировали! На это я имею полное право, Я никого не оскорблял на тот момент, пытался даже обращаться к тебе на "вы", но твоя напыщенность и завышенное самомнение, окончательно испортили моё мнение о тебе. Кстати, уже не в первый раз, в прошлый раз, я помню как ты пытался колонистов вернуть. Тогда тоже кромсались мои комментарии, увы ты не повзрослел с тех пор... Я понимаю что ты меня терпеть не можешь, поверь, я к тебе отношусь не лучше. Я рад что ты стараешься для проекта и всеми силами пытаюсь не мешать тебе, до тех моментов, когда вижу как окончательно портят перевод далеко не в лучшую сторону)
Опять же, учитывая модификацию, надеюсь что мне будет уже совсем по барабану на официальный перевод)

**Comment by Elevator89** [comment]
> Не, я не понял, кто в переводе примитивизмом болеет?

— наглость и хамство

> мне надоедает переправлять ваши косяки

> имею право требовать вернуть его как было

— необоснованно завышенное самомнение

> каждый раз какой-то мудрец откатывает мои изменения

— завуалированное оскорбление

> не тем меня пугаешь) тебе напугать меня вообще нечем) по этому будь по проще)

— насмешка

> Ржу, немогу, дети малые, теперь ещё и заминусуйте меня) подсиралы и понторезы) Мне ни горячо, ни холодно от ваших пальчиков)

— прямое оскорбление в адрес участников проекта

> тебе гордость вряд ли позволит это сделать....,

— переход на личности

> с человеком, который как минимум на десяток лет старше тебя? 

> ты не повзрослел с тех пор...

— аппеляция к возрасту с переходом на личности

> твоя напыщенность и завышенное самомнение, окончательно испортили моё мнение о тебе.

— опять переход на личности

> разве не фамильярность, общаться в таком тоне, 

В каком ещё тоне? Всё вышеперечисленное сказал ты, а не я.

**Comment by Humort** [comment]
Недолго музыка играла....

**Comment by Elevator89** [comment]
Уходя — уходи

**Comment by Elevator89** [comment]
Ещё раз. Уходя - уходи.
