### ISSUE TITLE
Нимб не жмёт?

### ISSUE THREAD

**Issue by Humort** [Ludeon/RimWorld-ru#839]
Ты слишком много на себя взял, Следующий шаг - удалить моё имя из перевод? Считаешь себя Богом? Давай, поступи как Бог, возьми и переведи всё сам, без моих наработок, откатись до версии 9 альфы и пиши код самостоятельно, Считаешь себя крутым - так сделай круто, вышиби меня из авторов на все 100%

А пока что ты чмо) - и это не оскорбление, а твоя сущность) то что ты есть на самом деле)

**Comment by Elevator89** [comment]
Вышибать из авторов никого не собираюсь. Проект перевода будет развиваться каждый раз не с нуля, а с версии, которая была на последний момент. Именно это и называется развитием. Модификации вносятся вне зависимости от того, кто был автором изначального текста. Цель проекта - создание качественной локализации игры, а не соответствие личным пожеланиям и амбициям кого-либо из текущих или бывших членов проекта. Подстраиваться под каждого внезапно возникшего бывшего переводчика с хамским и оскорбительным поведением нет ни желания, ни возможности.

**Comment by Humort** [comment]
Значит не жмёт) Ну всё с тобой ясно)
