### ISSUE TITLE
Длинные названия кнопок не помещаются в окно

### ISSUE THREAD

**Issue by An1onS** [Ludeon/RimWorld-ru#851]
В меню управления областями, названия кнопок "Переименовать" и "Инвертировать" не помещаются в окно и вытесняют кнопку удаления области.
![notok](https://user-images.githubusercontent.com/26001123/44297139-dcc66480-a2e5-11e8-98fe-1d90c3c69869.png)
![ok](https://user-images.githubusercontent.com/26001123/44297140-de902800-a2e5-11e8-98a7-c5748f92c91d.png)

**Comment by Elevator89** [comment]
Исправим

**Comment by Dimonasdf** [comment]
Можно "Переим." + "Инверт." или "Обратить".

**Comment by Elevator89** [comment]
Места хватает только на "Переим." и "Инв."

**Comment by Dimonasdf** [comment]
Почему закрыта? Это критический баг.
