### ISSUE TITLE
Beer+Wort- Update

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#86]
Привести пиво в соответствии с обновлением 0.15
Добавить перевод для Wort из Drugs/Beer.xml.

**Comment by Dinoabunai** [comment]
@Dimonasdf @Elevator89 
Сейчас пиво лежит в Items_Luxury.xml. Может стоит его перевести в Items_Drugs вместе с наркотиками. Коллеги из германии, например, так и сделали. Ваше мнение?

Мне кажется стоит перенести.

**Comment by Dimonasdf** [comment]
> Коллеги из Германии, например, так и сделали

Да.

**Comment by Ohar** [comment]
Вроде ок

**Comment by Dinoabunai** [comment]
Закрыто #93
