### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#863]
![photo5192973867751156221](https://user-images.githubusercontent.com/14166427/44706036-03845800-aaa9-11e8-8378-595ce46e23dd.jpg)

Есть предложение сделать по 3 или 4 в одну строчку, либо индивидуально. Займём местечка, но нам не жалко.

**Comment by Dimonasdf** [comment]
Надо полагать, что изменится вид и в главном меню. Всё же, по 4 было бы удобнее.

**Comment by Elevator89** [comment]
Исправлено в процессе вычитки
