### ISSUE TITLE
Не работают области

### ISSUE THREAD

**Issue by Ungaminga** [Ludeon/RimWorld-ru#866]
Менеджмент областей невозможен из-за вашей локализации. Чините или не переводите.
![image](https://user-images.githubusercontent.com/143675/45477427-39cd0300-b74a-11e8-91e7-bc0a04f578db.png)

**Comment by Elevator89** [comment]
Версия игры какая?

**Comment by Elevator89** [comment]
Качай последнюю версию локализации или не пиши неактуальные ишью.
![default](https://user-images.githubusercontent.com/21694533/45560192-18087480-b84d-11e8-82a6-baaaaed92a95.png)

**Comment by Ungaminga** [comment]
> Качай последнюю версию локализации или не пиши неактуальные ишью.
> ![default](https://user-images.githubusercontent.com/21694533/45560192-18087480-b84d-11e8-82a6-baaaaed92a95.png)

И как это делать?
