### ISSUE TITLE
Learning Helper (Tutorial)

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#87]
Перевод всего что касается Learning Helper. Видимо он лежит в папке Tutor.

**Comment by Dinoabunai** [comment]
@dankan0880 говорил что переводит это дело, однако от него давно не было известий.
Пока будем переводить другие вещи и возьмемся за эту только если @dankan0880 не объявится.

**Comment by Dimonasdf** [comment]
Этого не хватает? Обратите внимание на путь - DefInjected/InstructionDef/Instructions.xml.
https://github.com/dragomano/RimWorld-ru/blob/master/DefInjected/InstructionDef/Instructions.xml
Сам файл Instructions.xml - из папки Tutor.

**Comment by Dinoabunai** [comment]
Чего этого?
@dankan0880 перевел что-то. Ждем пула.

**Comment by Dimonasdf** [comment]
Переезд в #103.
