### ISSUE TITLE
GoJuice

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#88]
Перевести Drugs/GoJuice.xml
Наш любимый :)

**Comment by Dimonasdf** [comment]
Создадим подборку файлов после завершения основной работы. Пока что рабочее название - "энерго-сок".

**Comment by Elevator89** [comment]
"Энерго-сок" не катит по правилам русского языка. В правилах по дефисам нет такого случая. Это типичное сложное слово, и пишется без всяких дефисов: "Энегросок".

**Comment by Elevator89** [comment]
"Гоу-джус" - нормальный вариант

**Comment by Dimonasdf** [comment]
Affected files:

ChemicalDef\Drugs.xml
```
	<GoJuice.label>go-juice</GoJuice.label>

	<GoJuice.label>энерго-сок</GoJuice.label>
```
HediffDef\Hediffs_Global_Drugs.xml
```
	<GoJuiceHigh.label>high on go-juice</GoJuiceHigh.label>
	<GoJuiceTolerance.label>go-juice tolerance</GoJuiceTolerance.label>
	<GoJuiceAddiction.label>go-juice addiction</GoJuiceAddiction.label>
	<GoJuiceAddiction.stages.1.label>withdrawal</GoJuiceAddiction.stages.1.label>

	<GoJuiceHigh.label>под действием энерго-сока</GoJuiceHigh.label>
	<GoJuiceTolerance.label>толерантность к энерго-соку</GoJuiceTolerance.label>
	<GoJuiceAddiction.label>зависимость от энерго-сока</GoJuiceAddiction.label>
	<GoJuiceAddiction.stages.1.label>ломка</GoJuiceAddiction.stages.1.label>
```
NeedDef\Need_Drugs.xml
```
	<label>go-juice</label>
	<description>Because of a go-juice addiction, this person needs to regularly consume the drug to avoid withdrawal symptoms.</description>

	<Chemical_GoJuice.label>энерго-сок</Chemical_GoJuice.label>
	<Chemical_GoJuice.description>Из-за зависимости от энерго-сока этому человеку необходимо регулярно употреблять наркотик, чтобы избежать симптомов синдрома отмены.</Chemical_GoJuice.description>    
```
ThingDef\Items_Drugs.xml
```
	<label>go-juice</label>
	<description>A synthetic combat drug developed for space marines during the early days of interplanetary warfare. Go-juice blocks pain and increases the user's melee and shooting abilities. It also enhances movement speed.\n\nMilitary chemists who created it were never able to remove its addictiveness. Some saw this as a downside; others saw it as a benefit.</description>
	<ingestCommandString>Inject {0}</ingestCommandString>
	<ingestReportString>Injecting {0}.</ingestReportString>

Перевод отсутствует.
	<GoJuice.label></GoJuice.label>
	<GoJuice.description></GoJuice.description>
	<GoJuice.ingestible.ingestCommandString></GoJuice.ingestible.ingestCommandString>
	<GoJuice.ingestible.ingestReportString></GoJuice.ingestible.ingestReportString>
```
ResearchProjectDef\ResearchProjects_Tier2_Misc.xml
```
	<label>go-juice production</label>
	<description>Learn to produce the synthetic combat-performance-enhancing drug go-juice.</description>

 	<GoJuiceProduction.label>производство энерго-сока</GoJuiceProduction.label>
 	<GoJuiceProduction.description>Обучение созданию энерго-сока, синтетического наркотика, усиливающего боевые способности.</GoJuiceProduction.description>
 ```

**Comment by Ohar** [comment]
+1 «Энергосок» без дефиса

**Comment by Dinoabunai** [comment]
Проведу анализ по другим языкам.

**Comment by Dinoabunai** [comment]
[Венгерский](https://github.com/Ludeon/RimWorld-Hungarian/blob/master/DefInjected/ThingDef/Items_Drugs.xml) - gojuice
[Испанский](https://github.com/Ludeon/RimWorld-Spanish/blob/master/DefInjected/ThingDef/Items_Drugs.xml) - Zumo-Go (Сок-Go)
[Китайский (упрощенный)](https://github.com/Ludeon/RimWorld-ChineseSimplified/blob/master/DefInjected/ThingDefs/Drugs.xml) - для GoJuice переведены только **`<ingestible>`**
[Корейский](https://github.com/Ludeon/RimWorld-Korean/blob/master/DefInjected/ThingDefs/GoJuice.xml) - 고주스 - (Хо-Дзюси)
[Немецкий](https://github.com/Ludeon/RimWorld-de/blob/master/DefInjected/ThingDef/Items_Drugs.xml) - GoJuice
[Польский](https://github.com/Ludeon/RimWorld-Polish/blob/master/DefInjected/ThingDef/GoJuice.xml) - **go-juice**
[Японский](https://github.com/Ludeon/RimWorld-ja/blob/master/DefInjected/ThingDef/GoJuice.xml) - **ゴージュース** (ГО-ДЗЮСУ)

Резюме:
На сегодняшний день из 47 языков на гитхабе в игру попало только 26.
Из них только 7 вообще добрались до перевода наркотиков.
Из них GoJuice переведен отлично от оригинала только в 0,5 языках.

**Comment by Ohar** [comment]
Это интересно, но не говорит ничего о том, почему на это нужно обращать внимание

**Comment by Dinoabunai** [comment]
Потому что у нас нет нормального варианта. И зачем изобретать велосипед, если никто больше так не делает?

**Comment by Ohar** [comment]
Затем чтобы было норм. Не надо брать худшее за образец.

**Comment by Dinoabunai** [comment]
Не знаю чем Go-Juice не норм. И почему это худшее?

**Comment by dragomano** [comment]
Энерготоник. Хотя озверин всё-таки лучше — и звучит прикольно, и детьми нормально воспринимается, и на фоне других препаратов смотрится :)
В игре изображается в виде иконки с бутылочками, чем не напиток?

**Comment by Dinoabunai** [comment]
Пожалуйста, объясните мне откуда взялось слово "энерго-" он не имеет никакого отношения ни к названию, ни к действию Go-Juice. У меня уже зад дымится рассказывать что это боевой стимулятор, который вводят внутривенно и это написано у него в описании. И он не восстанавливает шкалу отдыха и не уменьшает потребность в нем.

**Comment by Dimonasdf** [comment]
То, что я привёл - просто текущее состояние дел. Для Items_Drugs.xml не нашёл перевода, потому что, видимо, он ещё не был перенесён откуда-то. Я же помню, что детали этого текста мы уже обсуждали.

Ни за какой вариант не топлю и не агитирую, но зато по некоторым имею соображения против.
Озверин - дичь.
Go-juice - без перевода оставлять нельзя.
Гоу-джус - уж лучше без перевода.
Энерготоник, энергосок - норм, но у всех от них горит.

Также пытаюсь добиться понимания, в каком месте описания сказано, что его "вводят внутривенно". Inject мы перевели как "ввести", но не как вколоть, и про вены там ничего нет.

Как насчёт названия:
Хуй-пойми-как-перевести-сок или, кодовое сокращение для игроков, - Х-сок?
Все думают, что читается "икс сок", но мы-то знаем, что он "х сок".

**Comment by Ohar** [comment]
> Также пытаюсь добиться понимания, в каком месте описания сказано, что его "вводят внутривенно". Inject мы перевели как "ввести", но не как вколоть, и про вены там ничего нет.

@Dimonasdf `Inject` в медицине имеет [строго определённое значение — введение в организм жидкости с помощью пустотелой иглы](https://en.wikipedia.org/wiki/Injection_(medicine)) и переводится на русский как *инъекция*.

Я за Озверин.

**Comment by Dinoabunai** [comment]
@Ohar 
Я продвигал идею с "Озверином". Она была люто отвергнута.

Просто Go-Juice и по-английски криво звучит. По-русски еще хуже.
Поэтому я и хотел бы оставить его без перевода.
Если уж игроки будут спрашивать - кто придумал такую смехоту, это хотя бы будет не наша вина :)
Плюс из-за языкового барьера это будет восприниматься спокойней.

**Comment by LatKrostov** [comment]
Всем доброе время суток. Внесу немного своей лепты.

Go juice это явно боевой стимулятор.

То есть возможные варианты, по моему мнению:

1) Боевой стимулятор
2) БС
3) БС "Берсерк"
4) Балтийский чай

Хотя последнее не совсем верно. Он все же пьётся, а не выкалывается.

**Comment by Elevator89** [comment]
"Озверин" не подходит, поскольку этот стимулятор не добавляет неконтролируемой злобы или жестокости, а совсем наоборот: "Я спокоен, и в то же время на взводе...".
"Энерогосок" тоже не очень, потому что это не энергетик.

**Comment by Elevator89** [comment]
Имена в виде торговых марок ("БС "Берсерк"") тут не катят, потому что поселенцы производят эту фигню не по лицензии, а сами, никого не спрашивая. Как и любую наркоту. По той же причине не им давать этому "соку" "рыночное" наименование.

**Comment by Elevator89** [comment]
Мои варианты:
"Go-стимулятор"
"Go-сок"

**Comment by LatKrostov** [comment]
Если это боевой успокоин, то ничего словами стимулятор точно не подойдет.
И "Берсерк" это не название торговой марки,а название типов стимулятора)
Хм, а назвать его "Джет"? Судя по эффекту что-то похожее.

**Comment by Elevator89** [comment]
> Если это боевой успокоин, то ничего словами стимулятор точно не подойдет.

Подойдёт. Стимулируются боевые способности, уходит страх, а не просто успокаиваются нервы.

> Хм, а назвать его "Джет"?

Ай-яй-яй! Засудят же.

**Comment by LatKrostov** [comment]
Не засудят. Не является товарным знаком)

**Comment by Elevator89** [comment]
Налицо плагиат. Любой юрист скажет, что нафиг так делать.

**Comment by LatKrostov** [comment]
Хоть бы погуглил для начала. Джет - реальный наркотик. Точнее куча наркоты имеет это слово в названии.

**Comment by Elevator89** [comment]
Тем более. Разрабы решили отказаться от реальных названий в пользу вымышленных.

**Comment by LatKrostov** [comment]
GO Juice это марка Квентина Тарантино. Чисто для инфы.

**Comment by Elevator89** [comment]
Чисто для инфы, этим словосочетанием много всего обозначается:
http://www.naturalprecepts.com/shop/go-juice/go-juice-energizer-bottle/
http://ru.urbandictionary.com/define.php?term=go-juice
http://dictionary.cambridge.org/ru/%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8C/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9/go-juice
http://www.gojuicenh.com/

**Comment by LatKrostov** [comment]
Что только подтверждает моё мнение, что наличие отсылок ничего не поменяет.
Они и так есть. Специально или нет.

среда, 12 октября 2016 г. пользователь Andrey Lemin написал:

**Comment by Elevator89** [comment]
Джет как наркотик - явный плагиат из Фоллаута, а не просто фраза, которой обзывают всё подряд. И это увидят подавляющее большинство игроков. Плюс, на него распространяется авторское право.
Более того, даже во вселенной Фоллаута, Джет - это нифига не боевой стимулятор, а наркота с диким эффектом привыкания.
Джет, как и Баффаут, и Психо, и даже Винт (который Джет от 1С), как и любые выдуманные наркотики из других игр, фильмов и книг, здесь не годятся. Точка.

**Comment by LatKrostov** [comment]
Нет ни одного наркотика, который бы не засветился в каком-либо произведение
искусства. А миксовать русское и английское название дикий бред.

Если разбить смысловую нагрузку, то можно получить:
Juice- сок. Но кроме этого ещё возможны переводы сущность, основа. В химии
так называют насыщенный раствор.

Go- слишком многообразный глагол. Так что модем подобрать любое начало,
как-то оно будет реагировать.

Боевой препарат. Сущность боя.




среда, 12 октября 2016 г. пользователь Andrey Lemin написал:

**Comment by Elevator89** [comment]
> Нет ни одного наркотика, который бы не засветился в каком-либо произведение искусства.

Есть. Это выдуманный наркотик. Мы как раз и занимаемся выдумыванием.

> А миксовать русское и английское название дикий бред

Аргументы будут?

Совершенно необязательно переводить дословно. Нужно название наркотика, имя собственное, которое не светилось нигде. При этом чтобы оно не походило на торговую марку, и чтобы не было слишком общим (вроде "боевого стимулятора"). Нужно в названии кратко и метафорически ёмко отразить действие и предназначение препарата.

**Comment by Elevator89** [comment]
Ребята, нужно больше вариантов. Перевод этого пресловутого Go-juice - очень важное задание. В воскресенье планируется релиз. Если не будет новых вариантов, придётся выбирать из:
_Go-стимулятор
Go-сок
Cок-Go
X-стимулятор
X-сок
Сок-X_

**Comment by Elevator89** [comment]
И то, "стимулятор" - слишком длинно. Можно заменить на "стимул". Имя собственное будет чуть более "собственным": _"Go-стимул"_

**Comment by Elevator89** [comment]
Пока самым близким к оригиналу остаётся "Go-сок"

**Comment by LatKrostov** [comment]
Мои варианты принципиально не попадают?

пятница, 14 октября 2016 г. пользователь Andrey Lemin написал:

**Comment by Elevator89** [comment]
Слово "стимулятор" - из твоего варианта.
А так, как я уже говорил:
1) Боевой стимулятор - слишком общо, нужно имя собственное
2) БС - то же самое, только еще и аббревиатура.
3) БС "Берсерк" - похоже на название торговой марки
4) Балтийский чай - ты сам сказал, чай пьют, а не вводят в вену.

**Comment by LatKrostov** [comment]
Боевой Коктейль "Сечевой".
Варианты с смешиванием английских и русских слов промтом отдают

14 октября 2016 г., 13:10 пользователь Andrey Lemin <
notifications@github.com> написал:

**Comment by Elevator89** [comment]
> Боевой Коктейль "Сечевой".

Не годится:
1. Похоже на торговую марку.
2. Слишком длинно.
Но "коктейль" - неплохое слово. Можно использовать для других вариантов. Как и слово "сечевой".
Официоза не нужно. Для вдохновения можно посмотреть [сюда](https://ru.wiktionary.org/wiki/%D0%9F%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5:%D0%A1%D0%BB%D0%B5%D0%BD%D0%B3_%D0%BD%D0%B0%D1%80%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%BE%D0%B2). Но и совсем сленговые варианты тоже не годятся.

> Варианты с смешиванием английских и русских слов промтом отдают

Во всех других языках почему-то берут и смешивают, или вообще без перевода оставляют. А тут, видите ли, промтом отдаёт. 
В таком "имени полусобственном" часть названия или название целиком может быть на языке оригинала. И это выглядит довольно естественно.

**Comment by Elevator89** [comment]
Все варианты сначала нужно примерять [сюда](https://github.com/Ludeon/RimWorld-ru/issues/88#issuecomment-246105208). И проверять удобство использования и общую естественность фраз. Это **очень** важный критерий.

**Comment by LatKrostov** [comment]
В качестве brainstorm:
1) Коктейль "Бейруби"
2) "Бейруби"
3) Коктейль "Бейбеги"
4) "Бейбеги"
5) СочОк
6) СочОК
7) Соч-Ок
8) Напит-Ок

**Comment by Dimonasdf** [comment]
Варианты и ход мысли @Elevator89 кажутся наиболее правильными.
Из вариантов @LatKrostov не один не впечатлил положительно. СочОК, конечно, норм, смешно, но всё же не то.

В ходе рассуждения о Go-стимуляторе упущено, что вариант содержит два раза часть, относящуюся к энергетичности, и ни разу не упоминает о сочности. Впрочем, если продолжить сокращение и получить _Go-стим_ - получается довольно интересно. Хотя мне видятся намёки на Steam и на "гостить - гостим".

_Сок-Х_ - да, я предлагал)
(Скрытый [`Сок Х`] вместо [`Сок Икс`])

Соединение частей на разных языках - не такая уж дурная практика, в _go-сок_е тоже не вижу ничего плохого. (В _сок_е-_Go_ - вижу.)

Ну и знаете, по сухому остатку, _энергосок_ кажется уже и не самым бредовым вариантом. Да, слишком дженериковое и не похожее на название слово, но всё же.

**Comment by Elevator89** [comment]
Да, мозговой штурм - это то, что нужно!
Правда "Ок" тут не к месту. Это боевой стимулятор, и его применяют, когда, мягко говоря, не "ок". СочОки и напитОки звучат как будто их пьют по праздникам, а не колят в вену перед тяжёлым боем. Ну, и непонятно, как их склонять.
Нужно что-то более боевое:
Go-коктейль
Бей-сок
Бей-коктейль

**Comment by Elevator89** [comment]
@Dimonasdf, _энергосок_ уже обсуждали. Отличный вариант для энергетика, но не для боевого стимулятора.
_Сок-Х_ - неплох, но это "Х" ни о чём не говорит. Невыразительно.

**Comment by Dimonasdf** [comment]
@Elevator89 ну так и подоплёка была, мол, военный, секретный, ни о чём не говорящее название вкупе с действенным эффектом. Не суть.

Мимо-попытка поскладывать кубики в разном порядке:
Стим-сок
Стим-джус
Энергостим
Стим-Х
X-Стим
Икс-Стим
Икс-Сок
Икс-Джус

**Comment by Elevator89** [comment]
Секретный военный сок не будут бодяжить поселенцы у себя в мастерской. Рецепт известен, раз поселенцы могут провести соответствующее исследование. Да купить/снять с трупа его можно. То есть, он ни разу не секретный.
О "стиме" лучше забыть, ибо и среднего игрока будут чёткие и стойкие ассоциации с паром, стимпанком, и, собственно, Steam'ом, через который игра распространяется. Но никак не с сокращением от "стимулятора".

**Comment by Dimonasdf** [comment]
@Elevator89 
В Deus Ex был гипостим
В Fallout 4 был стим что-то
Подозреваю, что и вообще широко это используется.
Беру слова про ассоциацию назад, эдак мы ни одного слова не сможем использовать. Нет ни у кого таких ассоциаций, это я чушь написал."Стим" стоит рассматривать как валидный элемент.

**Comment by Elevator89** [comment]
Я только дал три стойких ассоциации. Так что нифига не чушь ты написал. Со словом "стим" я бы не стал играться. Ненужных ассоциаций в обзывании наркоты надо избегать.

**Comment by Elevator89** [comment]
Более того, я не советую сильно удаляться от оригинала. Не забывайте, что сейчас народ играет с непереведённым "Go-juice" и более-менее привык к нему. Так что давайте не будем никого шокировать "коктейлями "Бейруби"".

**Comment by LatKrostov** [comment]
Так,  порывшись в английском слэнг нашёл ещё интересное значение.

Го-сок- так называют ещё алкоголь, который ты выпил перед походом в клуб, чтобы там платить меньше, но быть уже пьяным. Делается из водка+апельсиновый сок 1к1. Выпивается за 10-20 минут до входа в клуб.
Может это на мысли наведёт?


Или Ку-сок.
И КУ попытаться как-то расшифровать?

**Comment by Elevator89** [comment]
Думаю, прозвучало достаточно вариантов. Из них самые лучше на мой взгляд:
_go-juice
go-сок
стим-сок (стимсок)
бей-сок
КУ-сок (надо подобрать расшифровку)_
Давайте выбирать из них

**Comment by Elevator89** [comment]
Если до завтрашнего вечера никто ничего не выберет, я вставляю "Go-сок".

**Comment by LatKrostov** [comment]
КУ - Корректировщик Универсальный

**Comment by Elevator89** [comment]
Залил "Go-сок". Ишью не закрываю. Волны возмущения изливать сюда.
