### ISSUE TITLE
Доработать статью на вики про перевод

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#95]
Добавить информацию, о том как определить в какую директорию следует помещать перевод.

**Comment by Ohar** [comment]
А как определить?

**Comment by Dinoabunai** [comment]
Это величайшая проблема всех локализаторов RimWorld-а со всего мира.

**Comment by Dinoabunai** [comment]
Ну если у оригинала тэг в начале **`<ThingDef>`**, значит должно быть в русской папке **ThingDef**
```
<ThingDef>
    <name>Melon</name>
    <label>melon</label>
..
..
...
<ThingDef>
```

**Comment by Ohar** [comment]
охоспаде

**Comment by Dinoabunai** [comment]
А чего?

**Comment by Ohar** [comment]
Просто это *весьма неочевидно*

**Comment by Dinoabunai** [comment]
Я тебя не понял. Ты это с сарказмом или правда не понял?

**Comment by Ohar** [comment]
Без сарказма. Это и вправду путано.

**Comment by Dinoabunai** [comment]
Можешь описать что именно вызвало у тебя (или может вызвать у новичка) затруднения?
Я подумаю как это можно покрасивее описать...
Может просто на примере показать?

**Comment by Ohar** [comment]
1. Строка переведена криво. Где посмотреть оригинал? Английские файлы упорядочены весьма иначе, нежели прочие.
2. Строка в игре не переведена. Хочется перевести. Как её найти в файлах?
3. Открыл файл с кучей строк в XML. Как понять, какие из них надо перевести, а какие — служебные и их не надо трогать?
4. Нашёл/взял непереведённый файл. Перевёл. Как проверить его, если ты не знаешь, где эти строки видны в игре?

**Comment by Dinoabunai** [comment]
@Ohar 
Не, про перевод написано в вики. В статье "Перевод инъекций".
Тут я просто упомянул, что надо туда добавить информацию про расположение файлов.

> Строка переведена криво
Где посмотреть оригинал? Английские файлы упорядочены весьма иначе, нежели прочие.

Это величайшая проблема всех локализаторов RimWorld. В основном - по звездам.
Нет, это не шутка. Надо самому догадаться где это лежит. С помощью дедукции.
Вообще мы еще используем пару скриптов. Но в основном - по звездам.

> Строка в игре не переведена
Как её найти в файлах, чтобы перевести?

Если ты имеешь в виду что увидел в игре строку на английском. То... никак.
По звездам и с помощью дедукции :) Но если более реально - с помощью встроенных в твою ОС инструментов поиска. Либо - по звездам.

> Открыл файл с кучей строк в XML
Как понять, какие из них надо перевести, а какие — служебные и их не надо трогать?

Я наверное тебя утомил уже, но... Никак :) Просто постараться логически посмотреть.
Служебные строки, как правило начинаются с заглавной буквы.

> Перевёл файл
Как проверить его, если ты не знаешь, где эти строки видны в игре?

Выяснить, где эти строки в игре и проверить :) Если совсем плохо - я спрашиваю на форуме Ludeon. Но вообще - по звездам :)

Ну что, @Ohar, как тебе процесс локализации? Уже начинает нравится?  :)

**Comment by Ohar** [comment]
> по звездам
> по звездам
> по звездам
> по звездам
> как тебе процесс локализации? Уже начинает нравится? :)

[ГРОБ ГРОБ КЛАДБИЩЕ](http://apikabu.ru/img_n/2012-04_5/utf.jpg)
