### ISSUE TITLE
Подкорректируйте текст описания к химическому топливу 

### ISSUE THREAD

**Issue by Rem-u** [Ludeon/RimWorld-ru#958]
![изображение](https://user-images.githubusercontent.com/31742605/75612488-e5336880-5b34-11ea-92db-6f5c2b1fdb61.png)
Вот сюда {красная полоса} добавьте "или", без неё намного хуже воспринимается смысл

**Comment by motor-way** [comment]
Здесь три опции, перечисленные через запятую и союз, поэтому не вижу необходимости в этом

**Comment by Rem-u** [comment]
>Здесь три опции, перечисленные через запятую и союз, поэтому не вижу необходимости в этом
Я тебе пишу, как игрок, который только что это прочитал. Непонятно написано, не по русски как-то

**Comment by AloneFallen** [comment]
Действительно ли нужно указывать что-то порох?
