### ISSUE TITLE
RecipeDef: Внести изменения в Recipes_Drugs.xml

### ISSUE THREAD

**Issue by Dinoabunai** [Ludeon/RimWorld-ru#96]
**~Mods\Core\Languages\Russian\DefInjected\RecipeDef\Recipes_Drugs.xml**

Удалить перевод **BrewBeer**. Пиво теперь не варится.

Добавить перевод для **MakeWort** и **BurnDrugs**.
Оригинал: **~Mods\Core\Defs\RecipeDefs\Recipes_Drugs.xml**

**Comment by Dimonasdf** [comment]
В #107.
