### ISSUE TITLE
"Tortured artist" - "непонятый творец"

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#979]
Нужно привести везде в соответствие

**Comment by Blinnna** [comment]
Нашла в файле 
Core\DefInjected\ThoughtDef\Thoughts_Situation_TraitsPerm.xml

 
  <MoodOffsetTorturedArtist.stages.Tortured_artist.label>творческая натура</MoodOffsetTorturedArtist.stages.Tortured_artist.label>

Но там вроде как к месту. В остальном больше нигде нет.

**Comment by Elevator89** [comment]
Закрываем
