### ISSUE TITLE
BiomeDef-ChemicalDef

### ISSUE THREAD

**Issue by Dimonasdf** [Ludeon/RimWorld-ru#98]
Проверить все изменения текста:
BiomeDef
BodyDef
BodyPartDef
BodyPartGroupDef
ChemicalDef

Создать и перевести:
ChemicalDef\Drugs.xml

**Comment by Dimonasdf** [comment]
https://github.com/Ludeon/RimWorld-ru/tree/branch-1

**Comment by Dimonasdf** [comment]
BiomeDef - Done.

**Comment by Dimonasdf** [comment]
BodyDef, BodyPartDef, BodyPartGroupDefs -> Bodies
No changes in Def-tags.

BodyDef -> BodyPartGroupDefs - Done.

**Comment by Elevator89** [comment]
В Bodies_Animal_Quadruped.xml в 8 разных тегах перевод: "четвероногий". Косяк.

**Comment by Dimonasdf** [comment]
**BrokenStateDefs Empty!** Find missing files.

**Comment by Dimonasdf** [comment]
@Elevator89 Да?

![default](https://cloud.githubusercontent.com/assets/14166427/18410198/d4a19496-7763-11e6-9506-1ecfcc71ec46.PNG)

**Comment by Elevator89** [comment]
@Dimonasdf Да!
Похоже, это тот случай, когда тот, кто писал английский текст, недолго думая, накопипастил, а ты вслепую перевёл.

**Comment by Elevator89** [comment]
вместо того, чтобы вставить что-то более подходящее по смыслу, например для "QuadrupedAnimalWithHooves" можно было сделать "четвероногое копытное" вместо того, чтобы просто лепить "четвероногое везде".

**Comment by Elevator89** [comment]
Выполнено
