### ISSUE TITLE
Pikeman

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#980]
Как лучше перевести, чтобы с остальными видами механоидов сочеталось нормально.
Моё предложение - "рейтар". По аналогии с уланами, лёгкой кавалерией, рейтары - тяжелая кавалерия с огнестрельным оружием.
Очень хочется сохранить некую загадочность в названии. Среди других механоидов (сентипеда, жнец, улан), "рейтар" вполне соответствую этому критерию. А вот прямой перевод, "пикинёр", — не очень.

**Comment by kamadz** [comment]
Рейтар наиболее подходит по смыслу, однако, плохо сочетается с уланом, который является видом кавелерии нового времени. 
По стилистике, если противопоставлять нового механоида "улану", как более тяжёлую конницу лёгкой, подошёл бы **драгун** (как средняя кавалерия) или **кирасир** (как тяжёлая кавалерия). Кирасир может показаться странным вариантом, однако, если подумать, то всё сходится - более медлительная и защищённая подвижная кавалерия, в то время, как улан - очень мобильная, но рассыпается с одного плевка. 
Имхо, драгун и улан очень органично вместе смотрятся.

**Comment by Elevator89** [comment]
Вот на драгуне в итоге решили и остановиться.

**Comment by Elevator89** [comment]
Ишью неактуально. Вопрос уже решён. Был выбран вариант "драгун".
