### ISSUE TITLE
Royalty DefInjected/AbilityDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#983]
Автоформатированные файлы: [AbilityDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4484200/AbilityDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by PinGsamury** [comment]
беру

**Comment by Elevator89** [comment]
@PinGsamury забрал себе

**Comment by kamadz** [comment]
взял
