### ISSUE TITLE
Royalty ConceptDef-PawnKindDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#984]
Автоформатированные файлы: [ConceptDef-PawnKindDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4484205/ConceptDef-PawnKindDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by akeinhell** [comment]
Попробую взять
