### ISSUE TITLE
Royalty HediffDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#985]
Автоформатированные файлы: 
[HediffDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4327167/HediffDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by AWhiteFox** [comment]
Возьмусь
