### ISSUE TITLE
Royalty RoomRoleDef-TerrainDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#993]
Автоформатированные файлы: 
[RoomRoleDef-TerrainDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4327193/RoomRoleDef-TerrainDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by kamadz** [comment]
беру
