### ISSUE TITLE
Royalty RulePackDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#994]
Автоформатированные файлы: 
[RulePackDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4327200/RulePackDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by kamadz** [comment]
взял
