### ISSUE TITLE
Royalty ThoughtDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#998]
Автоформатированные файлы: 
[ThoughtDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4327208/ThoughtDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by kamadz** [comment]
Беру
