### ISSUE TITLE
Royalty TipSetDef-TraderKindDef

### ISSUE THREAD

**Issue by Elevator89** [Ludeon/RimWorld-ru#999]
Автоформатированные файлы: 
[TipSetDef-TraderKindDef.zip](https://github.com/Ludeon/RimWorld-ru/files/4327210/TipSetDef-TraderKindDef.zip)

Порядок действий:
1. Распаковать архив в директорию Royalty\DefInjected с заменой существующих файлов
2. Перевести все TODO в соответствии с английским текстом

**Comment by kamadz** [comment]
Беру
